
# Clase 6: Generación de Nuevas Columnas y Agregaciones

**MDS7202: Laboratorio de Programación Científica para Ciencia de Datos**

### Objetivos de la clase

- Crear nuevas columnas a partir de datos existentes.
- Transformación de columnas: Ranking, Cut, qCut, Apply
- Trabajo con fechas: datetime, timedeltas
- Comprender agregaciones en pandas: Groupby, agg.
- Set index, reset index

----

## 1. Pandas 🐼


`Pandas` una librería para python utilizada para manejar datos tabulares. 

<div align='center'>
<img src="https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/09-Pandas2/dataframe.png" alt="DataFrames" style="width: 800px;"/>
</div>


Está diseñada para proveer herramientas que faciliten la exploración, limpieza y procesamiento de los datos. Su enfoque es *simplicidad y eficiencia*. Es, al igual que las librerías anteriores, *open-source*.


La base de pandas son los `DataFrames`.

In [1]:
# para abrir archivos excel y visualizar hay que instalar esta dependencia extra
!uv add pandas openpyxl matplotlib plotly statsmodels

Resolved 59 packages in 30ms
Audited 53 packages in 397ms

Como convención, `Pandas` se importa de la siguiente manera:

In [2]:
import numpy as np
import pandas as pd

### Entrada / Salida (IO)

La lectura de datos en `pandas` es muy sencilla: `pandas` es compatible con muchos tipos de archivos y fuentes de datos de forma nativa:

- `CSV`
- `Excel`
- `SQL`
- `Json`
- ...

Los datos almacenados en estas fuentes pueden ser importados a `DataFrames` a través de las funcioes `read_*`

De la misma forma, es capaz de guardar los DataFrames en el formato que deseen usando las funciones `to_*`

<div align='center'>

<img src="https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/09-Pandas2/pandas_io.png" alt="DataFrames" style="width: 800px;"/>
</div>
    
Toda la información acerca de que puede o no leer la encuentran en la siguiente referencia: https://pandas.pydata.org/docs/user_guide/io.html

### Índices para una Vida Mejor

Para explicar `pandas`, analizaremos datos de la OECD, en particular de los índices para una Vida Mejor:


<img src="https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/09-Pandas2/oecd.png" alt="OECD Better life index"/>


http://www.oecdbetterlifeindex.org/

https://stats.oecd.org/Index.aspx?DataSetCode=BLI

Son 11 temas considerados como esenciales para el bienestar de la población. Cada crierio contiene uno o mas indicadores

| Tema | Indicador (Inglés) | Indicador (Español) | Unidad | Descripción |
|---|---|---|---|---|
| Vivienda 🏠 | Dwellings without basic facilities | Vivienda con Instalaciones Básicas | Porcentaje | Porcentaje de personas con inodoros de agua corriente dentro del hogar, año disponible más reciente |
|  | Housing expenditure | Gastos en Vivienda | Porcentaje | Proporción de costos de vivienda en el ingreso neto ajustado de las familias, año disponible más reciente |
|  | Rooms per person | Habitaciones por Persona | Ratio | Número promedio de habitaciones compartidas por persona en una vivienda, año disponible más reciente |
| Ingresos 💰 | Household net adjusted disposable income | Ingreso Familiar Disponible | US Dollar | Cantidad promedio de dinero que una familia gana al año, después de impuestos, año disponible más reciente |
|  | Household net wealth | Patrimonio Neto Familiar | US Dollar | Valor total promedio de los activos financieros de una familia (ahorros, acciones) menos sus pasivos (créditos), año disponible más reciente |
| Empleo ⚙️ | Labour market insecurity | Seguridad en el Empleo | Porcentaje | Pérdida esperada de ingresos cuando alguien queda desempleado, año disponible más reciente |
|  | Employment rate | Tasa de Empleo | Porcentaje | Porcentaje de personas, de 15 a 64 años de edad, actualmente con empleo remunerado, año disponible más reciente |
|  | Long-term unemployment rate | Tasa de Empleo a Largo Plazo | Porcentaje | Porcentaje de personas, de 15 a 64 años de edad, que no trabajan pero que han buscado empleo activamente durante más de un año, año disponible más reciente |
|  | Personal earnings | Ingresos Personales | US Dollar | Ingresos anuales promedio por empleado de tiempo completo, año disponible más reciente |
| Comunidad 🧑‍🤝‍🧑   | Quality of support network  | Calidad del Apoyo Social | Porcentaje | Porcentaje de personas con amigos o parientes en quienes confiar en caso de necesidad |
| Educación 📚 | Educational attainment | Nivel de Educación | Porcentaje | Porcentaje de personas, de 25 a 64 años de edad, graduadas por lo menos de educación media superior, año disponible más reciente |
|  | Student skills | Competencias de estudiantes en matemáticas, lectura y ciencias | Puntaje promedio | Desempeño promedio de estudiantes de 15 años de edad, según PISA (Programa para la Evaluación Internacional de Estudiantes) |
|  | Years in education  | Nivel de educación | Años | Duración promedio de la educación formal en la que un niño de cinco años de edad puede esperar matricularse durante su vida |
| Medio Ambiente 🌳 | Air pollution | Contaminación del Aire | Microgramos por metro cúbico | Concentración promedio de partículas (PM2.5) en ciudades con poblaciones mayores de 100,000 personas, medida en microgramos por metro cúbico, año disponible más reciente |
|  | Water quality | Calidad del Agua | Porcentaje | Porcentaje de personas que informan estar satisfechas con la calidad del agua local |
| Compromiso Cívico 🗳️  | Stakeholder engagement for developing regulations | Participación de los interesados en la elaboración de regulaciones | Puntaje promedio | Nivel de transparencia gubernamental al preparar las regulaciones, año disponible más reciente |
|  | Voter turnout | Participación electoral | Porcentaje | Porcentaje de votantes registrados que votaron durante las elecciones recientes, año disponible más reciente |
| Salud ⚕️ | Life expectancy | Esperanza de vida | Años | Número promedio de años que una persona puede esperar vivir, año disponible más reciente |
|  | Self-reported health | Salud según informan las personas | Porcentaje | Porcentaje de personas que informan que su salud es «buena o muy buena», año disponible más reciente |
| Satisfacción ✨ | Life satisfaction | Satisfacción ante la vida | Puntaje promedio | Autoevaluación promedio de satisfacción ante la vida, en una escala de 0 a 10 |
| Seguridad 🌃 | Feeling safe walking alone at night | Sentimiento de seguridad al caminar solos por la noche | Porcentaje | Porcentaje de personas que reportan sentirse seguras al caminar solas por la noche  |
|  | Homicide rate | Tasa de homicidios | Ratio | Número promedio de homicidios reportados por 100,000 personas, año disponible más reciente |
| Balance Vida Trabajo 🧘 | Employees working very long hours | Empleados que trabajan muchas horas | Porcentaje | Porcentaje de empleados que trabajan más de cincuenta horas a la semana en promedio, año disponible más reciente |
|  | Time devoted to leisure and personal care | Tiempo destinado al ocio y el cuidado personal | Horas | Número promedio de minutos al día dedicados al ocio y el cuidado personal, incluidos el sueño y la alimentación |

### Importar el Dataset

A continuacion, importaremos el dataset a un `DataFrame`. Noten la gran compatiblidad de `Jupyter` con los DataFrames (DF).

Cada DataFrame tiene **indices (Primera columna ) y columnas (primera fila)**. Comunmente se ocupan:

- En las columnas se ocupan `strings` que identifican el nombre de la variable.
- Enteros que identifican el número de la observación en las filas. 

Sin embargo, las filas también pueden ser identificadas por strings como las columnas por enteros

In [3]:
import pandas as pd

# utilidad para mostrar todas las columnas
pd.set_option("display.max_columns", None)

df = pd.read_excel(
    "../../recursos/2023-02/pandas-2/dataset.xlsx",
    header=1,
    index_col=0,
)
df

,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,Quality of support network,Educational attainment,Student skills,Years in education,Air pollution,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health,Life satisfaction,Feeling safe walking alone at night,Homicide rate,Employees working very long hours,Time devoted to leisure and personal care
Country,,,,,,,,,,,,,,,,,,,,,,,,
Australia,NaN,20.0,NaN,32759.0,427064.0,5.4,73,1.31,49126.0,95,81.0,502.0,21.0,5,93,2.7,91,82.5,85.0,7.3,63.5,1.1,13.04,14.35
Austria,0.9,21.0,1.6,33541.0,308325.0,3.5,72,1.84,50349.0,92,85.0,492.0,17.0,16,92,1.3,80,81.7,70.0,7.1,80.6,0.5,6.66,14.55
Belgium,1.9,21.0,2.2,30364.0,386006.0,3.7,63,3.54,49675.0,91,77.0,503.0,19.3,15,84,2.0,89,81.5,74.0,6.9,70.1,1.0,4.75,15.70
Canada,0.2,22.0,2.6,30854.0,423849.0,6.0,73,0.77,47622.0,93,91.0,523.0,17.3,7,91,2.9,68,81.9,88.0,7.4,82.2,1.3,3.69,14.56
Chile,9.4,18.0,1.2,NaN,100967.0,8.7,63,NaN,25879.0,85,65.0,443.0,17.5,16,71,1.3,47,79.9,57.0,6.5,47.9,4.2,9.72,NaN
Colombia,23.9,17.0,1.2,NaN,NaN,NaN,67,0.79,NaN,89,54.0,410.0,14.1,10,75,1.4,53,76.2,NaN,6.3,44.4,24.5,26.56,NaN
Czech Republic,0.7,24.0,1.4,21453.0,NaN,3.1,74,1.04,25372.0,91,94.0,491.0,17.9,20,87,1.6,61,79.1,60.0,6.7,72.3,0.5,5.65,NaN
Denmark,0.5,23.0,1.9,29606.0,118637.0,4.2,74,1.31,51466.0,95,81.0,504.0,19.5,9,95,2.0,86,80.9,71.0,7.6,83.5,0.6,2.34,15.87
Estonia,7.0,17.0,1.6,19697.0,159373.0,3.8,74,1.92,24336.0,92,89.0,524.0,17.7,8,84,2.7,64,77.8,53.0,5.7,69.0,3.1,2.42,14.90
Finland,0.5,23.0,1.9,29943.0,200827.0,3.9,70,2.13,42964.0,95,88.0,523.0,19.8,6,95,2.2,67,81.5,70.0,7.6,85.1,1.3,3.81,15.17
France,0.5,21.0,1.8,31304.0,280653.0,7.6,65,4.00,43755.0,90,78.0,496.0,16.5,13,81,2.1,75,82.4,66.0,6.5,70.5,0.5,7.67,16.36
Germany,0.2,20.0,1.8,34294.0,259667.0,2.7,75,1.57,47585.0,90,87.0,508.0,18.1,14,91,1.8,76,81.1,65.0,7.0,72.5,0.5,4.26,15.62
Greece,0.5,23.0,1.2,17700.0,150134.0,29.8,53,15.65,26064.0,80,73.0,458.0,19.0,18,69,1.8,64,81.5,74.0,5.4,60.0,0.8,6.42,NaN
Hungary,4.7,19.0,1.2,NaN,104458.0,4.7,68,1.72,22576.0,86,84.0,474.0,16.4,19,77,1.2,70,76.2,60.0,5.6,56.3,1.0,3.03,NaN
Iceland,0.0,24.0,1.6,NaN,NaN,0.7,86,0.26,61787.0,98,77.0,481.0,19.0,3,99,2.1,79,82.3,76.0,7.5,86.0,0.5,15.06,NaN
Ireland,1.0,20.0,2.1,25310.0,217130.0,7.8,67,3.23,47653.0,95,82.0,509.0,18.1,7,85,1.3,65,81.8,83.0,7.0,75.9,0.7,5.25,NaN
Israel,NaN,NaN,1.2,NaN,NaN,4.2,69,0.49,35067.0,88,87.0,472.0,15.6,21,67,2.5,72,82.5,84.0,7.2,69.8,1.8,15.45,NaN
Italy,0.7,23.0,1.4,26588.0,279889.0,12.3,58,6.59,36658.0,92,61.0,485.0,16.6,18,71,2.5,73,83.3,71.0,6.0,58.4,0.6,4.11,16.47
Japan,6.4,22.0,1.9,29798.0,305878.0,1.4,75,1.03,40863.0,89,NaN,529.0,16.4,14,87,1.4,53,84.1,36.0,5.9,72.5,0.2,NaN,NaN
Korea,2.5,15.0,1.5,21882.0,285980.0,2.6,67,0.05,35191.0,78,88.0,519.0,17.3,28,76,2.9,77,82.4,33.0,5.9,66.6,1.0,NaN,14.70
Latvia,13.9,23.0,1.2,16275.0,70160.0,9.6,70,3.35,23683.0,86,88.0,487.0,18.0,11,79,2.2,59,74.7,47.0,5.9,62.4,4.8,1.27,13.83
Lithuania,13.6,19.0,1.5,21660.0,NaN,NaN,70,2.69,24287.0,88,93.0,475.0,18.4,14,81,2.4,51,74.8,43.0,5.9,55.9,3.4,0.54,NaN
Luxembourg,0.5,21.0,1.9,39264.0,769053.0,1.7,66,2.35,63062.0,93,77.0,483.0,15.1,12,84,1.7,91,82.8,69.0,6.9,75.8,0.6,3.82,NaN
Mexico,25.5,20.0,1.0,NaN,NaN,5.5,61,0.07,15314.0,81,38.0,416.0,15.2,16,68,3.2,63,75.4,66.0,6.5,41.8,18.1,28.70,NaN
Netherlands,0.1,19.0,1.9,29333.0,157824.0,4.8,76,1.97,52877.0,91,78.0,508.0,18.7,14,93,2.6,82,81.6,76.0,7.4,82.0,0.6,0.42,NaN
New Zealand,NaN,26.0,2.4,NaN,388514.0,4.7,77,0.74,40043.0,96,79.0,506.0,17.7,5,89,2.5,80,81.7,88.0,7.3,65.7,1.3,15.11,14.87
Norway,0.0,17.0,2.1,35725.0,228936.0,NaN,74,0.66,51212.0,94,82.0,504.0,18.3,5,98,2.2,78,82.5,77.0,7.6,90.1,0.4,2.93,15.56
Poland,3.0,22.0,1.1,19814.0,210991.0,5.7,66,1.52,27046.0,86,92.0,504.0,17.6,22,82,2.6,55,78.0,58.0,6.1,67.3,0.7,5.95,14.42
Portugal,1.0,21.0,1.7,21203.0,232666.0,10.0,68,4.43,25367.0,88,48.0,497.0,16.9,10,86,1.5,56,81.2,48.0,5.4,73.4,1.0,8.27,NaN
Slovak Republic,1.2,23.0,1.1,20474.0,119696.0,9.9,66,4.78,24328.0,91,91.0,463.0,15.8,21,85,3.0,60,77.3,66.0,6.2,63.5,0.8,4.14,NaN
Slovenia,0.4,18.0,1.5,20820.0,203044.0,5.8,69,3.17,34933.0,92,88.0,509.0,18.3,16,90,2.5,53,81.3,64.0,5.9,86.1,0.6,4.39,14.75
Spain,0.1,21.0,1.9,23999.0,373548.0,23.1,62,7.66,38507.0,93,59.0,491.0,17.9,11,72,1.8,70,83.4,72.0,6.3,82.1,0.6,4.01,15.93
Sweden,0.0,19.0,1.7,31287.0,NaN,3.2,77,1.12,42393.0,91,83.0,496.0,19.3,6,96,2.0,86,82.4,75.0,7.3,75.6,0.9,1.07,15.18
Switzerland,0.1,22.0,1.9,37466.0,NaN,NaN,80,1.82,62283.0,93,88.0,506.0,17.5,15,95,2.3,49,83.7,78.0,7.5,85.3,0.6,0.37,NaN
Turkey,8.0,20.0,1.0,NaN,NaN,12.5,52,2.39,NaN,86,39.0,425.0,18.3,20,65,1.5,86,78.0,69.0,5.5,59.8,1.4,32.64,14.79
United Kingdom,0.3,26.0,1.9,28715.0,548392.0,4.5,75,1.13,43732.0,94,81.0,500.0,17.5,11,84,3.1,69,81.2,69.0,6.8,77.7,0.2,12.15,14.92
United States,0.1,19.0,2.4,45284.0,632100.0,7.7,70,0.66,60558.0,91,91.0,488.0,17.2,10,83,3.1,65,78.6,88.0,6.9,73.9,5.5,11.09,14.44
OECD - Total,4.4,20.0,1.8,33604.0,408376.0,7.0,68,1.78,43241.0,89,78.0,486.0,17.2,14,81,2.4,68,80.2,69.0,6.5,68.4,3.7,11.01,14.98
Brazil,6.7,NaN,NaN,NaN,NaN,NaN,61,NaN,NaN,90,49.0,395.0,16.2,10,73,2.2,79,74.8,NaN,6.4,35.6,26.7,7.13,NaN
Russia,14.8,18.0,0.9,NaN,NaN,NaN,70,1.59,NaN,89,94.0,492.0,16.2,15,55,NaN,68,71.8,43.0,5.8,52.8,9.6,0.14,NaN
South Africa,37.0,18.0,NaN,NaN,NaN,NaN,43,16.46,NaN,88,73.0,NaN,NaN,22,67,NaN,73,57.5,NaN,4.7,36.1,13.7,18.12,14.92

> **Pregunta ❓:** ¿Cómo puedo obtener solo los datos ambientales (columnas `"Water quality"`, `"Air pollution" y "Rooms per person"`) de todos los paises y guardarlo en un dataframe?

In [4]:
df_ambiental = df.loc[:, ["Water quality", "Air pollution", "Rooms per person"]]
df_ambiental

                 Water quality  Air pollution  Rooms per person
Country
Australia                   93              5               NaN
Austria                     92             16               1.6
Belgium                     84             15               2.2
Canada                      91              7               2.6
Chile                       71             16               1.2
Colombia                    75             10               1.2
Czech Republic              87             20               1.4
Denmark                     95              9               1.9
Estonia                     84              8               1.6
Finland                     95              6               1.9
France                      81             13               1.8
Germany                     91             14               1.8
Greece                      69             18               1.2
Hungary                     77             19               1.2
Iceland                     99              3               1.6
Ireland                     85              7               2.1
Israel                      67             21               1.2
Italy                       71             18               1.4
Japan                       87             14               1.9
Korea                       76             28               1.5
Latvia                      79             11               1.2
Lithuania                   81             14               1.5
Luxembourg                  84             12               1.9
Mexico                      68             16               1.0
Netherlands                 93             14               1.9
New Zealand                 89              5               2.4
Norway                      98              5               2.1
Poland                      82             22               1.1
Portugal                    86             10               1.7
Slovak Republic             85             21               1.1
Slovenia                    90             16               1.5
Spain                       72             11               1.9
Sweden                      96              6               1.7
Switzerland                 95             15               1.9
Turkey                      65             20               1.0
United Kingdom              84             11               1.9
United States               83             10               2.4
OECD - Total                81             14               1.8
Brazil                      73             10               NaN
Russia                      55             15               0.9
South Africa                67             22               NaN

> **Pregunta ❓**: Y ahora, ¿Cómo puedo obtener solo los datos de Chile?

In [5]:
df_ambiental.loc["Chile"]

Water quality       71.0
Air pollution       16.0
Rooms per person     1.2
Name: Chile, dtype: float64

In [6]:
df_ambiental.loc["Chile", "Air pollution"]

np.int64(16)

In [7]:
# Revisar tema indices con iloc
df_ambiental.iloc[0, 0]

np.int64(93)

---

## 1.- Generación de Nuevas Columnas

En esta sección aprenderemos como generar nuevas columnas a partir de la información existente en un dataframe.
En particular, veremos el cómo crear:

- Rankings
- Bins / Intervalos
- Cuantiles
- Funciones personalizadas

> **Pregunta ❓**: ¿Qué utilidad podría tener el saber generar nuevas columnas al momento de crear modelos predictivos?

### 1.1 Rankings

Un ranking es una clasificación que indica el órden (por defecto de mayor a menor) de los datos a partir de algún tipo de evaluación.

In [8]:
df_ambiental.loc[:, "Air pollution"]

Country
Australia           5
Austria            16
Belgium            15
Canada              7
Chile              16
Colombia           10
Czech Republic     20
Denmark             9
Estonia             8
Finland             6
France             13
Germany            14
Greece             18
Hungary            19
Iceland             3
Ireland             7
Israel             21
Italy              18
Japan              14
Korea              28
Latvia             11
Lithuania          14
Luxembourg         12
Mexico             16
Netherlands        14
New Zealand         5
Norway              5
Poland             22
Portugal           10
Slovak Republic    21
Slovenia           16
Spain              11
Sweden              6
Switzerland        15
Turkey             20
United Kingdom     11
United States      10
OECD - Total       14
Brazil             10
Russia             15
South Africa       22
Name: Air pollution, dtype: int64

In [9]:
air_pollution_rank = df_ambiental.loc[:, "Air pollution"].rank(
    ascending=True,
    method="min",
)
air_pollution_rank

Country
Australia           2.0
Austria            28.0
Belgium            25.0
Canada              7.0
Chile              28.0
Colombia           11.0
Czech Republic     35.0
Denmark            10.0
Estonia             9.0
Finland             5.0
France             19.0
Germany            20.0
Greece             32.0
Hungary            34.0
Iceland             1.0
Ireland             7.0
Israel             37.0
Italy              32.0
Japan              20.0
Korea              41.0
Latvia             15.0
Lithuania          20.0
Luxembourg         18.0
Mexico             28.0
Netherlands        20.0
New Zealand         2.0
Norway              2.0
Poland             39.0
Portugal           11.0
Slovak Republic    37.0
Slovenia           28.0
Spain              15.0
Sweden              5.0
Switzerland        25.0
Turkey             35.0
United Kingdom     15.0
United States      11.0
OECD - Total       20.0
Brazil             11.0
Russia             25.0
South Africa       39.0
Name: Air pollution, dtype: float64

> **Pregunta ❓** ¿Qué pasa cuando tenemos datos con el mismo valor?

Hint: [Documentación oficial de Rank](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rank.html).

In [10]:
# agrupacion de randk
air_pollution_rank.sort_values()

Country
Iceland             1.0
Australia           2.0
New Zealand         2.0
Norway              2.0
Finland             5.0
Sweden              5.0
Ireland             7.0
Canada              7.0
Estonia             9.0
Denmark            10.0
Colombia           11.0
Portugal           11.0
United States      11.0
Brazil             11.0
Spain              15.0
Latvia             15.0
United Kingdom     15.0
Luxembourg         18.0
France             19.0
OECD - Total       20.0
Netherlands        20.0
Lithuania          20.0
Japan              20.0
Germany            20.0
Switzerland        25.0
Russia             25.0
Belgium            25.0
Austria            28.0
Mexico             28.0
Slovenia           28.0
Chile              28.0
Greece             32.0
Italy              32.0
Hungary            34.0
Czech Republic     35.0
Turkey             35.0
Israel             37.0
Slovak Republic    37.0
South Africa       39.0
Poland             39.0
Korea              41.0
Name: Air pollution, dtype: float64


### 1.2 Dividir datos numéricos en intervalos

La función `pd.cut` permite separar los datos de una columna en bins/intervalos de igual tamaño, los cuales son calculados dividiendo el rango (maximo - mínimo) en la cantidad de bins indicada.

Los bins resultantes pueden ser interpretados como categorías.

> **Pregunta ❓**: ¿Cuántos datos quedan en cada bin? ¿Igual o distinta cantidad por bin?

In [11]:
df_ambiental.loc[:, "Air pollution"]

Country
Australia           5
Austria            16
Belgium            15
Canada              7
Chile              16
Colombia           10
Czech Republic     20
Denmark             9
Estonia             8
Finland             6
France             13
Germany            14
Greece             18
Hungary            19
Iceland             3
Ireland             7
Israel             21
Italy              18
Japan              14
Korea              28
Latvia             11
Lithuania          14
Luxembourg         12
Mexico             16
Netherlands        14
New Zealand         5
Norway              5
Poland             22
Portugal           10
Slovak Republic    21
Slovenia           16
Spain              11
Sweden              6
Switzerland        15
Turkey             20
United Kingdom     11
United States      10
OECD - Total       14
Brazil             10
Russia             15
South Africa       22
Name: Air pollution, dtype: int64

In [12]:
import plotly.express as px

px.histogram(df_ambiental, x="Air pollution", nbins=6)

> **Ejercicio 📝:** Calcular los bins de `Air pollution` al dividir el rango de la columna en 5 bins.

In [13]:
min_ = df_ambiental.loc[:, "Air pollution"].min()
min_

np.int64(3)

In [14]:
max_ = df_ambiental.loc[:, "Air pollution"].max()
max_

np.int64(28)

In [15]:
rango = max_ - min_
rango

np.int64(25)

In [16]:
n_bins = 5

print("Tamaño de cada intervalo =", rango / n_bins)

Tamaño de cada intervalo = 5.0

In [17]:
air_pollution_cut = pd.cut(df_ambiental.loc[:, "Air pollution"], bins=5,)
air_pollution_cut

Country
Australia          (2.975, 8.0]
Austria            (13.0, 18.0]
Belgium            (13.0, 18.0]
Canada             (2.975, 8.0]
Chile              (13.0, 18.0]
Colombia            (8.0, 13.0]
Czech Republic     (18.0, 23.0]
Denmark             (8.0, 13.0]
Estonia            (2.975, 8.0]
Finland            (2.975, 8.0]
France              (8.0, 13.0]
Germany            (13.0, 18.0]
Greece             (13.0, 18.0]
Hungary            (18.0, 23.0]
Iceland            (2.975, 8.0]
Ireland            (2.975, 8.0]
Israel             (18.0, 23.0]
Italy              (13.0, 18.0]
Japan              (13.0, 18.0]
Korea              (23.0, 28.0]
Latvia              (8.0, 13.0]
Lithuania          (13.0, 18.0]
Luxembourg          (8.0, 13.0]
Mexico             (13.0, 18.0]
Netherlands        (13.0, 18.0]
New Zealand        (2.975, 8.0]
Norway             (2.975, 8.0]
Poland             (18.0, 23.0]
Portugal            (8.0, 13.0]
Slovak Republic    (18.0, 23.0]
Slovenia           (13.0, 18.0]
Spain               (8.0, 13.0]
Sweden             (2.975, 8.0]
Switzerland        (13.0, 18.0]
Turkey             (18.0, 23.0]
United Kingdom      (8.0, 13.0]
United States       (8.0, 13.0]
OECD - Total       (13.0, 18.0]
Brazil              (8.0, 13.0]
Russia             (13.0, 18.0]
South Africa       (18.0, 23.0]
Name: Air pollution, dtype: category
Categories (5, interval[float64, right]): [(2.975, 8.0] < (8.0, 13.0] < (13.0, 18.0] < (18.0, 23.0] < (23.0, 28.0]]

In [18]:
# intervalos: [3, 8), (8, 13], (13, 17], (17, 23], (23, 28]

# chile -> (13, 17]
# korea -> (23, 28]

In [19]:
air_pollution_cut.values

[(2.975, 8.0], (13.0, 18.0], (13.0, 18.0], (2.975, 8.0], (13.0, 18.0], ..., (8.0, 13.0], (13.0, 18.0], (8.0, 13.0], (13.0, 18.0], (18.0, 23.0]]
Length: 41
Categories (5, interval[float64, right]): [(2.975, 8.0] < (8.0, 13.0] < (13.0, 18.0] < (18.0, 23.0] < (23.0, 28.0]]

> **Pregunta ❓**: ¿Podemos asignar los intervalos a mano?

In [20]:
air_pollution_cut = pd.cut(
    df_ambiental.loc[:, "Air pollution"], 
    bins=[0, 15, 20, 24, 28])
air_pollution_cut

Country
Australia           (0, 15]
Austria            (15, 20]
Belgium             (0, 15]
Canada              (0, 15]
Chile              (15, 20]
Colombia            (0, 15]
Czech Republic     (15, 20]
Denmark             (0, 15]
Estonia             (0, 15]
Finland             (0, 15]
France              (0, 15]
Germany             (0, 15]
Greece             (15, 20]
Hungary            (15, 20]
Iceland             (0, 15]
Ireland             (0, 15]
Israel             (20, 24]
Italy              (15, 20]
Japan               (0, 15]
Korea              (24, 28]
Latvia              (0, 15]
Lithuania           (0, 15]
Luxembourg          (0, 15]
Mexico             (15, 20]
Netherlands         (0, 15]
New Zealand         (0, 15]
Norway              (0, 15]
Poland             (20, 24]
Portugal            (0, 15]
Slovak Republic    (20, 24]
Slovenia           (15, 20]
Spain               (0, 15]
Sweden              (0, 15]
Switzerland         (0, 15]
Turkey             (15, 20]
United Kingdom      (0, 15]
United States       (0, 15]
OECD - Total        (0, 15]
Brazil              (0, 15]
Russia              (0, 15]
South Africa       (20, 24]
Name: Air pollution, dtype: category
Categories (4, interval[int64, right]): [(0, 15] < (15, 20] < (20, 24] < (24, 28]]

> **Pregunta ❓** ¿Qué problema presentan las categorías recién generadas?

In [21]:
#  [(2.975, 8.0] < (8.0, 13.0] < (13.0, 18.0] < (18.0, 23.0] < (23.0, 28.0]]
air_pollution_cut = pd.cut(
    df_ambiental.loc[:, "Air pollution"],
    bins=4,
    labels=["Bueno", "Medio", "Malo", "Deplorable"],
)
air_pollution_cut

Country
Australia               Bueno
Austria                  Malo
Belgium                 Medio
Canada                  Bueno
Chile                    Malo
Colombia                Medio
Czech Republic           Malo
Denmark                 Bueno
Estonia                 Bueno
Finland                 Bueno
France                  Medio
Germany                 Medio
Greece                   Malo
Hungary                  Malo
Iceland                 Bueno
Ireland                 Bueno
Israel                   Malo
Italy                    Malo
Japan                   Medio
Korea              Deplorable
Latvia                  Medio
Lithuania               Medio
Luxembourg              Medio
Mexico                   Malo
Netherlands             Medio
New Zealand             Bueno
Norway                  Bueno
Poland             Deplorable
Portugal                Medio
Slovak Republic          Malo
Slovenia                 Malo
Spain                   Medio
Sweden                  Bueno
Switzerland             Medio
Turkey                   Malo
United Kingdom          Medio
United States           Medio
OECD - Total            Medio
Brazil                  Medio
Russia                  Medio
South Africa       Deplorable
Name: Air pollution, dtype: category
Categories (4, str): ['Bueno' < 'Medio' < 'Malo' < 'Deplorable']

> **Pregunta ❓:** Entonces, ¿los bins quedaban con la misma o distinta cantidad de datos?

In [22]:
air_pollution_cut.value_counts()

Air pollution
Medio         17
Malo          11
Bueno         10
Deplorable     3
Name: count, dtype: int64

### 1.3 Dividir datos numéricos en cuantiles 

La función `pd.qcut` permite dividir los datos por cuantiles, los cuales a diferencia del anterior, tienen (_o intentan tener_) la misma cantidad de datos por cada intervalo generado.


Al igual que el caso anterior, podemos especificar como nombrar los cuantiles a través del atributo `labels`:

In [23]:
air_pollution_qcut = pd.qcut(
    df_ambiental.loc[:, "Air pollution"],
    q=4,
)

air_pollution_qcut

Country
Australia          (2.999, 10.0]
Austria             (14.0, 16.0]
Belgium             (14.0, 16.0]
Canada             (2.999, 10.0]
Chile               (14.0, 16.0]
Colombia           (2.999, 10.0]
Czech Republic      (16.0, 28.0]
Denmark            (2.999, 10.0]
Estonia            (2.999, 10.0]
Finland            (2.999, 10.0]
France              (10.0, 14.0]
Germany             (10.0, 14.0]
Greece              (16.0, 28.0]
Hungary             (16.0, 28.0]
Iceland            (2.999, 10.0]
Ireland            (2.999, 10.0]
Israel              (16.0, 28.0]
Italy               (16.0, 28.0]
Japan               (10.0, 14.0]
Korea               (16.0, 28.0]
Latvia              (10.0, 14.0]
Lithuania           (10.0, 14.0]
Luxembourg          (10.0, 14.0]
Mexico              (14.0, 16.0]
Netherlands         (10.0, 14.0]
New Zealand        (2.999, 10.0]
Norway             (2.999, 10.0]
Poland              (16.0, 28.0]
Portugal           (2.999, 10.0]
Slovak Republic     (16.0, 28.0]
Slovenia            (14.0, 16.0]
Spain               (10.0, 14.0]
Sweden             (2.999, 10.0]
Switzerland         (14.0, 16.0]
Turkey              (16.0, 28.0]
United Kingdom      (10.0, 14.0]
United States      (2.999, 10.0]
OECD - Total        (10.0, 14.0]
Brazil             (2.999, 10.0]
Russia              (14.0, 16.0]
South Africa        (16.0, 28.0]
Name: Air pollution, dtype: category
Categories (4, interval[float64, right]): [(2.999, 10.0] < (10.0, 14.0] < (14.0, 16.0] < (16.0, 28.0]]

In [24]:
water_quality_qcut = pd.qcut(
    df_ambiental["Water quality"],
    q=5,
)

water_quality_qcut

Country
Australia            (92.0, 99.0]
Austria              (85.0, 92.0]
Belgium              (81.0, 85.0]
Canada               (85.0, 92.0]
Chile              (54.999, 72.0]
Colombia             (72.0, 81.0]
Czech Republic       (85.0, 92.0]
Denmark              (92.0, 99.0]
Estonia              (81.0, 85.0]
Finland              (92.0, 99.0]
France               (72.0, 81.0]
Germany              (85.0, 92.0]
Greece             (54.999, 72.0]
Hungary              (72.0, 81.0]
Iceland              (92.0, 99.0]
Ireland              (81.0, 85.0]
Israel             (54.999, 72.0]
Italy              (54.999, 72.0]
Japan                (85.0, 92.0]
Korea                (72.0, 81.0]
Latvia               (72.0, 81.0]
Lithuania            (72.0, 81.0]
Luxembourg           (81.0, 85.0]
Mexico             (54.999, 72.0]
Netherlands          (92.0, 99.0]
New Zealand          (85.0, 92.0]
Norway               (92.0, 99.0]
Poland               (81.0, 85.0]
Portugal             (85.0, 92.0]
Slovak Republic      (81.0, 85.0]
Slovenia             (85.0, 92.0]
Spain              (54.999, 72.0]
Sweden               (92.0, 99.0]
Switzerland          (92.0, 99.0]
Turkey             (54.999, 72.0]
United Kingdom       (81.0, 85.0]
United States        (81.0, 85.0]
OECD - Total         (72.0, 81.0]
Brazil               (72.0, 81.0]
Russia             (54.999, 72.0]
South Africa       (54.999, 72.0]
Name: Water quality, dtype: category
Categories (5, interval[float64, right]): [(54.999, 72.0] < (72.0, 81.0] < (81.0, 85.0] < (85.0, 92.0] < (92.0, 99.0]]

In [25]:
water_quality_qcut.value_counts()

Water quality
(54.999, 72.0]    9
(72.0, 81.0]      8
(81.0, 85.0]      8
(85.0, 92.0]      8
(92.0, 99.0]      8
Name: count, dtype: int64

> **Pregunta ❓**: ¿Podemos asignar etiquetas en vez de intervalos (i.e., `"Excelente"`, `"Bueno"`, `"Medio"`, `"Malo"`, `"Deplorable"`)?

In [26]:
df_ambiental["Water quality"]

Country
Australia          93
Austria            92
Belgium            84
Canada             91
Chile              71
Colombia           75
Czech Republic     87
Denmark            95
Estonia            84
Finland            95
France             81
Germany            91
Greece             69
Hungary            77
Iceland            99
Ireland            85
Israel             67
Italy              71
Japan              87
Korea              76
Latvia             79
Lithuania          81
Luxembourg         84
Mexico             68
Netherlands        93
New Zealand        89
Norway             98
Poland             82
Portugal           86
Slovak Republic    85
Slovenia           90
Spain              72
Sweden             96
Switzerland        95
Turkey             65
United Kingdom     84
United States      83
OECD - Total       81
Brazil             73
Russia             55
South Africa       67
Name: Water quality, dtype: int64

In [27]:
water_quality_qcut = pd.qcut(
    df_ambiental["Water quality"],
    q=5,
    labels=["Deplorable", "Malo", "Medio", "Bueno", "Excelente"],
)

water_quality_qcut

Country
Australia           Excelente
Austria                 Bueno
Belgium                 Medio
Canada                  Bueno
Chile              Deplorable
Colombia                 Malo
Czech Republic          Bueno
Denmark             Excelente
Estonia                 Medio
Finland             Excelente
France                   Malo
Germany                 Bueno
Greece             Deplorable
Hungary                  Malo
Iceland             Excelente
Ireland                 Medio
Israel             Deplorable
Italy              Deplorable
Japan                   Bueno
Korea                    Malo
Latvia                   Malo
Lithuania                Malo
Luxembourg              Medio
Mexico             Deplorable
Netherlands         Excelente
New Zealand             Bueno
Norway              Excelente
Poland                  Medio
Portugal                Bueno
Slovak Republic         Medio
Slovenia                Bueno
Spain              Deplorable
Sweden              Excelente
Switzerland         Excelente
Turkey             Deplorable
United Kingdom          Medio
United States           Medio
OECD - Total             Malo
Brazil                   Malo
Russia             Deplorable
South Africa       Deplorable
Name: Water quality, dtype: category
Categories (5, str): ['Deplorable' < 'Malo' < 'Medio' < 'Bueno' < 'Excelente']

> **Pregunta ❓**: ¿Tienen sentido los bins generados? Para responder esto, interpretar el valor de la calidad de agua en Chile y su cuantil asociado.

In [28]:
water_quality_qcut.value_counts()

Water quality
Deplorable    9
Malo          8
Medio         8
Bueno         8
Excelente     8
Name: count, dtype: int64

### 1.4 Transformaciones personalizadas

También podemos aplicar funciones personalizadas que nosotros podemos definir. Esto permite aplicar funciones matemáticas, discretizaciones con bins no uniformes, agrupaciones, etc. Esto le da mucho más flexibilidad a la manipulación de columnas!

In [29]:
df_ambiental["Rooms per person"]

Country
Australia          NaN
Austria            1.6
Belgium            2.2
Canada             2.6
Chile              1.2
Colombia           1.2
Czech Republic     1.4
Denmark            1.9
Estonia            1.6
Finland            1.9
France             1.8
Germany            1.8
Greece             1.2
Hungary            1.2
Iceland            1.6
Ireland            2.1
Israel             1.2
Italy              1.4
Japan              1.9
Korea              1.5
Latvia             1.2
Lithuania          1.5
Luxembourg         1.9
Mexico             1.0
Netherlands        1.9
New Zealand        2.4
Norway             2.1
Poland             1.1
Portugal           1.7
Slovak Republic    1.1
Slovenia           1.5
Spain              1.9
Sweden             1.7
Switzerland        1.9
Turkey             1.0
United Kingdom     1.9
United States      2.4
OECD - Total       1.8
Brazil             NaN
Russia             0.9
South Africa       NaN
Name: Rooms per person, dtype: float64

In [30]:
df_ambiental["Rooms per person"].describe()

count    38.000000
mean      1.636842
std       0.426438
min       0.900000
25%       1.200000
50%       1.650000
75%       1.900000
max       2.600000
Name: Rooms per person, dtype: float64

In [31]:
df_ambiental["Rooms per person"].isna()

Country
Australia           True
Austria            False
Belgium            False
Canada             False
Chile              False
Colombia           False
Czech Republic     False
Denmark            False
Estonia            False
Finland            False
France             False
Germany            False
Greece             False
Hungary            False
Iceland            False
Ireland            False
Israel             False
Italy              False
Japan              False
Korea              False
Latvia             False
Lithuania          False
Luxembourg         False
Mexico             False
Netherlands        False
New Zealand        False
Norway             False
Poland             False
Portugal           False
Slovak Republic    False
Slovenia           False
Spain              False
Sweden             False
Switzerland        False
Turkey             False
United Kingdom     False
United States      False
OECD - Total       False
Brazil              True
Russia             False
South Africa        True
Name: Rooms per person, dtype: bool

In [32]:
df_ambiental["Rooms per person"].isna().sum()

np.int64(3)

`apply()` permite aplicar una función arbitraria a cada fila (`axis=1`) o columna (`axis=0`) de un DataFrame, o a cada elemento de una Serie.

> **⚠️ Advertencia de rendimiento**: `apply()` ejecuta la función en un bucle Python puro, por lo que es **significativamente más lento** que las operaciones vectorizadas nativas de pandas (como la aritmética entre columnas o `.str.method()`). Úsalo solo cuando no exista una alternativa vectorizada.

In [33]:
def crowding_index(rooms_per_person: int | pd.nan) -> int:
    if not pd.isna(rooms_per_person):
        return (rooms_per_person - 1) * 2
    else:
        return 0

In [42]:
crowding_index_col = df_ambiental["Rooms per person"].apply(crowding_index)
crowding_index_col

Country
Australia          0.0
Austria            1.2
Belgium            2.4
Canada             3.2
Chile              0.4
Colombia           0.4
Czech Republic     0.8
Denmark            1.8
Estonia            1.2
Finland            1.8
France             1.6
Germany            1.6
Greece             0.4
Hungary            0.4
Iceland            1.2
Ireland            2.2
Israel             0.4
Italy              0.8
Japan              1.8
Korea              1.0
Latvia             0.4
Lithuania          1.0
Luxembourg         1.8
Mexico             0.0
Netherlands        1.8
New Zealand        2.8
Norway             2.2
Poland             0.2
Portugal           1.4
Slovak Republic    0.2
Slovenia           1.0
Spain              1.8
Sweden             1.4
Switzerland        1.8
Turkey             0.0
United Kingdom     1.8
United States      2.8
OECD - Total       1.6
Brazil             0.0
Russia            -0.2
South Africa       0.0
Name: Rooms per person, dtype: float64

> Y si quisieramos identificar que países son sudamericanos?

### 1.5 Dividir datos categóricos

Veamos otro ejemplo de funciones personalizadas, esta vez para agruár datos categóricos pero que están presentes en el índice. Esto presenta varios desafíos, ya que un índice no tiene las mismas propiedades que una columna

In [43]:
paises_latinoamericanos = ["Chile",  "Brazil", "Colombia", "Mexico"]
df_ambiental.loc[paises_latinoamericanos]

          Water quality  Air pollution  Rooms per person
Country
Chile                71             16               1.2
Brazil               73             10               NaN
Colombia             75             10               1.2
Mexico               68             16               1.0

In [44]:
df_ambiental.index in paises_latinoamericanos

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [45]:
def es_latino(pais):
    if pais in paises_latinoamericanos:
        return True
    return False

In [47]:
df_ambiental.index.apply(es_latino)

AttributeError: 'Index' object has no attribute 'apply'

`.apply()` no aplica para índices. ¿Qué podemos hacer al respecto?

Podríamos, por ejemplo, transformar el índice en columna

In [49]:
df_ambiental.reset_index().head()

     Country  Water quality  Air pollution  Rooms per person
0  Australia             93              5               NaN
1    Austria             92             16               1.6
2    Belgium             84             15               2.2
3     Canada             91              7               2.6
4      Chile             71             16               1.2

In [51]:
es_latino_col = df_ambiental.reset_index()["Country"].apply(es_latino)
es_latino_col.head()

0    False
1    False
2    False
3    False
4     True
Name: Country, dtype: bool

Pero ¿Qué pasó con el índice? Esto ocurrió porque para obtener esta columna tuvimos que resetear el índice de la tabla

In [52]:
es_latino_col.index

RangeIndex(start=0, stop=41, step=1)

> Podemos asignar directamente esta serie a una columna de df_ambiental? Por qué?

In [53]:
# Guardamos para deshacer los cambios
df_ambiental["Es Latino"] = es_latino_col
df_ambiental.head()

           Water quality  Air pollution  Rooms per person Es Latino
Country
Australia             93              5               NaN       NaN
Austria               92             16               1.6       NaN
Belgium               84             15               2.2       NaN
Canada                91              7               2.6       NaN
Chile                 71             16               1.2       NaN

In [54]:
df_ambiental = df_ambiental.drop(columns=["Es Latino"])
df_ambiental.head()

           Water quality  Air pollution  Rooms per person
Country
Australia             93              5               NaN
Austria               92             16               1.6
Belgium               84             15               2.2
Canada                91              7               2.6
Chile                 71             16               1.2

Para asignar esto a una nueva columna deberíamos extraer los datos 'crudos' del DataSeries. Recordemos que también podemos asignar columnas con listas. Esto es:

```python
data_frame["Column"] = [value_1, value_2, ..., value_n]
```

En este caso, son datos sin índice ni información adicional, por lo que si son del mismo tamaño que la cantidad de filas de la tabla simplemente los asigna posicionalmente. Solo cuando existe información sobre índice pandas intenta utilizarlo para asignar qué valor va en qué fila. En python, se pueden extraer los datos crudos de un DataSeries utilizando `.values`. Es decir:

```python
data_frame["Column"] = data_series.values
```

O alternativamente para este caso de uso, podríamos usar `.isin()` directamente en el índice.

In [55]:
es_latino_col= df_ambiental.index.isin(paises_latinoamericanos)
es_latino_col

array([False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False])

In [56]:
df_ambiental["Es Latino"] = es_latino_col
df_ambiental.head()

           Water quality  Air pollution  Rooms per person  Es Latino
Country
Australia             93              5               NaN      False
Austria               92             16               1.6      False
Belgium               84             15               2.2      False
Canada                91              7               2.6      False
Chile                 71             16               1.2       True

### 1.6 Asignación de nuevas columnas a un DataFrame

Hasta el momento hemos generado nuevas columnas, pero no las hemos guardado en ningún dataframe. Sin embargo sería idea poder unir estas columnas con sus respectivos datos originales.

**Si los índices del dataframe son los mismos que el de la nueva columna**, podemos asignar una serie como una nueva columna de nuestro DataFrame de la siguiente forma:

In [57]:
df_ambiental.loc[:, "Air pollution Ranking"] = air_pollution_rank
df_ambiental

,Water quality,Air pollution,Rooms per person,Es Latino,Air pollution Ranking
Country,,,,,
Australia,93,5,NaN,False,2.0
Austria,92,16,1.6,False,28.0
Belgium,84,15,2.2,False,25.0
Canada,91,7,2.6,False,7.0
Chile,71,16,1.2,True,28.0
Colombia,75,10,1.2,True,11.0
Czech Republic,87,20,1.4,False,35.0
Denmark,95,9,1.9,False,10.0
Estonia,84,8,1.6,False,9.0
Finland,95,6,1.9,False,5.0
France,81,13,1.8,False,19.0
Germany,91,14,1.8,False,20.0
Greece,69,18,1.2,False,32.0
Hungary,77,19,1.2,False,34.0
Iceland,99,3,1.6,False,1.0
Ireland,85,7,2.1,False,7.0
Israel,67,21,1.2,False,37.0
Italy,71,18,1.4,False,32.0
Japan,87,14,1.9,False,20.0
Korea,76,28,1.5,False,41.0
Latvia,79,11,1.2,False,15.0
Lithuania,81,14,1.5,False,20.0
Luxembourg,84,12,1.9,False,18.0
Mexico,68,16,1.0,True,28.0
Netherlands,93,14,1.9,False,20.0
New Zealand,89,5,2.4,False,2.0
Norway,98,5,2.1,False,2.0
Poland,82,22,1.1,False,39.0
Portugal,86,10,1.7,False,11.0
Slovak Republic,85,21,1.1,False,37.0
Slovenia,90,16,1.5,False,28.0
Spain,72,11,1.9,False,15.0
Sweden,96,6,1.7,False,5.0
Switzerland,95,15,1.9,False,25.0
Turkey,65,20,1.0,False,35.0
United Kingdom,84,11,1.9,False,15.0
United States,83,10,2.4,False,11.0
OECD - Total,81,14,1.8,False,20.0
Brazil,73,10,NaN,True,11.0
Russia,55,15,0.9,False,25.0
South Africa,67,22,NaN,False,39.0

In [58]:
df_ambiental.loc[:, "Air pollution Ranking"] = air_pollution_rank
df_ambiental.loc[:, "Air pollution Bins"] = air_pollution_cut
df_ambiental.loc[:, "Air pollution Quintile"] = air_pollution_qcut
df_ambiental.loc[:, "Crowding Index"] = crowding_index_col
df_ambiental.loc[:, "Es Latino"] = es_latino_col

df_ambiental.sort_values(by="Air pollution Ranking")

,Water quality,Air pollution,Rooms per person,Es Latino,Air pollution Ranking,Air pollution Bins,Air pollution Quintile,Crowding Index
Country,,,,,,,,
Iceland,99,3,1.6,False,1.0,Bueno,"(2.999, 10.0]",1.2
Australia,93,5,NaN,False,2.0,Bueno,"(2.999, 10.0]",0.0
New Zealand,89,5,2.4,False,2.0,Bueno,"(2.999, 10.0]",2.8
Norway,98,5,2.1,False,2.0,Bueno,"(2.999, 10.0]",2.2
Finland,95,6,1.9,False,5.0,Bueno,"(2.999, 10.0]",1.8
Sweden,96,6,1.7,False,5.0,Bueno,"(2.999, 10.0]",1.4
Ireland,85,7,2.1,False,7.0,Bueno,"(2.999, 10.0]",2.2
Canada,91,7,2.6,False,7.0,Bueno,"(2.999, 10.0]",3.2
Estonia,84,8,1.6,False,9.0,Bueno,"(2.999, 10.0]",1.2
Denmark,95,9,1.9,False,10.0,Bueno,"(2.999, 10.0]",1.8
Colombia,75,10,1.2,True,11.0,Medio,"(2.999, 10.0]",0.4
Portugal,86,10,1.7,False,11.0,Medio,"(2.999, 10.0]",1.4
United States,83,10,2.4,False,11.0,Medio,"(2.999, 10.0]",2.8
Brazil,73,10,NaN,True,11.0,Medio,"(2.999, 10.0]",0.0
Spain,72,11,1.9,False,15.0,Medio,"(10.0, 14.0]",1.8
Latvia,79,11,1.2,False,15.0,Medio,"(10.0, 14.0]",0.4
United Kingdom,84,11,1.9,False,15.0,Medio,"(10.0, 14.0]",1.8
Luxembourg,84,12,1.9,False,18.0,Medio,"(10.0, 14.0]",1.8
France,81,13,1.8,False,19.0,Medio,"(10.0, 14.0]",1.6
OECD - Total,81,14,1.8,False,20.0,Medio,"(10.0, 14.0]",1.6
Netherlands,93,14,1.9,False,20.0,Medio,"(10.0, 14.0]",1.8
Lithuania,81,14,1.5,False,20.0,Medio,"(10.0, 14.0]",1.0
Japan,87,14,1.9,False,20.0,Medio,"(10.0, 14.0]",1.8
Germany,91,14,1.8,False,20.0,Medio,"(10.0, 14.0]",1.6
Switzerland,95,15,1.9,False,25.0,Medio,"(14.0, 16.0]",1.8
Russia,55,15,0.9,False,25.0,Medio,"(14.0, 16.0]",-0.2
Belgium,84,15,2.2,False,25.0,Medio,"(14.0, 16.0]",2.4
Austria,92,16,1.6,False,28.0,Malo,"(14.0, 16.0]",1.2
Mexico,68,16,1.0,True,28.0,Malo,"(14.0, 16.0]",0.0
Slovenia,90,16,1.5,False,28.0,Malo,"(14.0, 16.0]",1.0
Chile,71,16,1.2,True,28.0,Malo,"(14.0, 16.0]",0.4
Greece,69,18,1.2,False,32.0,Malo,"(16.0, 28.0]",0.4
Italy,71,18,1.4,False,32.0,Malo,"(16.0, 28.0]",0.8
Hungary,77,19,1.2,False,34.0,Malo,"(16.0, 28.0]",0.4
Czech Republic,87,20,1.4,False,35.0,Malo,"(16.0, 28.0]",0.8
Turkey,65,20,1.0,False,35.0,Malo,"(16.0, 28.0]",0.0
Israel,67,21,1.2,False,37.0,Malo,"(16.0, 28.0]",0.4
Slovak Republic,85,21,1.1,False,37.0,Malo,"(16.0, 28.0]",0.2
South Africa,67,22,NaN,False,39.0,Deplorable,"(16.0, 28.0]",0.0
Poland,82,22,1.1,False,39.0,Deplorable,"(16.0, 28.0]",0.2
Korea,76,28,1.5,False,41.0,Deplorable,"(16.0, 28.0]",1.0

---

## 2.- Trabajando con fechas

### Motivación: Dataset de Temperaturas Globales

![wbg_climate](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/09-Pandas2/wbg_climate.png)


https://climateknowledgeportal.worldbank.org/download-data

**Cargar Dataset de Temperaturas Globales**

In [59]:
import pandas as pd

In [60]:
temperaturas = pd.read_csv(
    "../../recursos/2023-02/pandas-2/temperature.csv")
temperaturas.head(20)

    Temperature  Year Month      Country ISO3
0      -0.03110  1991   Jan  Afghanistan  AFG
1       1.43654  1991   Feb  Afghanistan  AFG
2       6.88685  1991   Mar  Afghanistan  AFG
3      12.93970  1991   Apr  Afghanistan  AFG
4      17.07550  1991   May  Afghanistan  AFG
5      23.07770  1991   Jun  Afghanistan  AFG
6      25.57100  1991   Jul  Afghanistan  AFG
7      23.96730  1991   Aug  Afghanistan  AFG
8      19.38000  1991   Sep  Afghanistan  AFG
9      12.87790  1991   Oct  Afghanistan  AFG
10      7.31675  1991   Nov  Afghanistan  AFG
11      4.23571  1991   Dec  Afghanistan  AFG
12      0.74637  1992   Jan  Afghanistan  AFG
13      2.46018  1992   Feb  Afghanistan  AFG
14      5.71341  1992   Mar  Afghanistan  AFG
15     11.69260  1992   Apr  Afghanistan  AFG
16     16.11080  1992   May  Afghanistan  AFG
17     22.88750  1992   Jun  Afghanistan  AFG
18     24.70680  1992   Jul  Afghanistan  AFG
19     22.86330  1992   Aug  Afghanistan  AFG

In [61]:
temperaturas.Country.unique()

<StringArray>
[         'Afghanistan',              'Albania',              'Algeria',
              'Andorra',               'Angola',  'Antigua and Barbuda',
            'Argentina',              'Armenia',            'Australia',
              'Austria',
 ...
               'Tuvalu',               'Uganda',              'Ukraine',
 'United Arab Emirates',       'United Kingdom',        'United States',
              'Uruguay',           'Uzbekistan',              'Vanuatu',
            'Venezuela']
Length: 192, dtype: str

In [62]:
temperaturas['Country'].unique()

<StringArray>
[         'Afghanistan',              'Albania',              'Algeria',
              'Andorra',               'Angola',  'Antigua and Barbuda',
            'Argentina',              'Armenia',            'Australia',
              'Austria',
 ...
               'Tuvalu',               'Uganda',              'Ukraine',
 'United Arab Emirates',       'United Kingdom',        'United States',
              'Uruguay',           'Uzbekistan',              'Vanuatu',
            'Venezuela']
Length: 192, dtype: str

In [63]:
temperaturas.shape

(59904, 5)

In [64]:
temperaturas.columns

Index(['Temperature', 'Year', 'Month', 'Country', 'ISO3'], dtype='str')

**Filtrar solo los de Chile**

In [65]:
temperaturas

       Temperature  Year Month      Country ISO3
0         -0.03110  1991   Jan  Afghanistan  AFG
1          1.43654  1991   Feb  Afghanistan  AFG
2          6.88685  1991   Mar  Afghanistan  AFG
3         12.93970  1991   Apr  Afghanistan  AFG
4         17.07550  1991   May  Afghanistan  AFG
...            ...   ...   ...          ...  ...
59899     26.09480  2016   Aug    Venezuela  VEN
59900     26.22090  2016   Sep    Venezuela  VEN
59901     26.62850  2016   Oct    Venezuela  VEN
59902     26.27680  2016   Nov    Venezuela  VEN
59903     26.12860  2016   Dec    Venezuela  VEN

[59904 rows x 5 columns]

In [66]:
temperaturas.loc[:, "Country"] == "Chile"

0        False
1        False
2        False
3        False
4        False
         ...
59899    False
59900    False
59901    False
59902    False
59903    False
Name: Country, Length: 59904, dtype: bool

In [67]:
t_chile = temperaturas.loc[temperaturas.loc[:, "Country"] == "Chile", :]
t_chile

       Temperature  Year Month Country ISO3
10608     12.53860  1991   Jan   Chile  CHL
10609     12.29140  1991   Feb   Chile  CHL
10610     11.13730  1991   Mar   Chile  CHL
10611      8.85700  1991   Apr   Chile  CHL
10612      6.70605  1991   May   Chile  CHL
...            ...   ...   ...     ...  ...
10915      5.83910  2016   Aug   Chile  CHL
10916      7.19059  2016   Sep   Chile  CHL
10917      8.81492  2016   Oct   Chile  CHL
10918     10.71450  2016   Nov   Chile  CHL
10919     12.39610  2016   Dec   Chile  CHL

[312 rows x 5 columns]

In [68]:
import plotly.express as px

px.line(t_chile, x="Month", y="Temperature", color="Year", height=600)

> Cómo podemos transformar el año y mes en una fecha en un formato operable?

### Módulo `Datetime`

El módulo datetime en Python es una librería estándar (built-in) que proporciona clases y métodos para trabajar con fechas y horas los cuales simplifican la manipulación y cálculos ellos.

In [69]:
import datetime

#### Date

Objeto que almacena día, mes y año.

In [70]:
date_object = datetime.date.today()
print(date_object)

2026-03-29

In [71]:
date_object

datetime.date(2026, 3, 29)

In [72]:
type(date_object)

datetime.date

In [73]:
date_object.day

29

In [74]:
date_object.month

3

In [75]:
date_object.year

2026

#### Datetime

Almacena segundos, minutos, hora, día, mes y año. También puede contener timezone.

In [76]:
datetime_object = datetime.datetime.now()
print(datetime_object)

2026-03-29 19:21:12.092048

#### Instanciar nuevos Date y Datetimes

In [77]:
d = datetime.date(2021, 9, 9)
print(d)

2021-09-09

In [78]:
str(d)

'2021-09-09'

> Cómo se define esto internamente considerando lo que sabemos hasta hoy de python?

In [79]:
print(datetime.date)

<class 'datetime.date'>

In [80]:
# __str__(self)
    # self.year + "-" + self.day

In [81]:
type(d)

datetime.date

In [82]:
print("Año:", d.year)
print("Mes:", d.month)
print("Día:", d.day)

Año: 2021
Mes: 9
Día: 9

In [83]:
d = datetime.datetime(
    year=2021, 
    month=4, 
    day=19, 
    hour=10, 
    minute=59, 
    second=55
)
print(d)

2021-04-19 10:59:55

In [84]:
print("Hora:", d.hour)
print("Minuto:", d.minute)
print("Segundo:", d.second)
print("Microsegundo:", d.microsecond)

Hora: 10
Minuto: 59
Segundo: 55
Microsegundo: 0

Obviamente, estos objetos cuentan con las restricciones pertinentes

In [85]:
datetime.datetime(-1, 4, 19, 10, 59, 55)

ValueError: year must be in 1..9999, not -1

In [86]:
datetime.datetime(999999, 4, 19, 10, 59, 55)

ValueError: year must be in 1..9999, not 999999

Relacionado: https://es.wikipedia.org/wiki/Problema_del_a%C3%B1o_2000


El problema del año 2000, fue un bug o error de software causado por la costumbre que habían adoptado los programadores de omitir la centuria en el año para el almacenamiento de fechas (generalmente para economizar memoria), asumiendo que el software solo funcionaría durante los años cuyos números comenzaran con 19XX


![Antes](https://www.sopitas.com/wp-content/uploads/2016/04/ss.gif)

In [87]:
datetime.datetime(999999, 4, 19, 10, 59, 55)

ValueError: year must be in 1..9999, not 999999

In [88]:
datetime.datetime(2020, 4, 19, 10, 60, 55)

ValueError: minute must be in 0..59, not 60

¿Y los años bisiestos?

In [89]:
datetime.datetime(2020, 2, 29)

datetime.datetime(2020, 2, 29, 0, 0)

In [90]:
datetime.datetime(2021, 2, 29)

ValueError: day 29 must be in range 1..28 for month 2 in year 2021

##### Desde timestamp

`A Unix timestamp is the number of seconds between a particular date and January 1, 1970 at UTC.`

In [91]:
timestamp = datetime.date.fromtimestamp(0)
print("Date =", timestamp)

Date = 1969-12-31

> **Pregunta ❓**: ¿Podemos sumar o restar fechas?

In [92]:
delta = datetime.datetime(1, 1, 1)
delta

datetime.datetime(1, 1, 1, 0, 0)

In [93]:
d

datetime.datetime(2021, 4, 19, 10, 59, 55)

In [94]:
datetime.datetime.now()

datetime.datetime(2026, 3, 29, 19, 21, 25, 506598)

In [95]:
datetime.datetime.now() + delta

TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'datetime.datetime'

#### TimeDelta

Permide sumar semanas, días, horas, etc... a objetos `date` y `datetime`.

In [96]:
d = datetime.datetime.now()
d

datetime.datetime(2026, 3, 29, 19, 21, 27, 257033)

In [97]:
d + 30

TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'int'

In [98]:
from datetime import timedelta

t1 = timedelta(weeks=2)
t1

datetime.timedelta(days=14)

In [99]:
d + t1

datetime.datetime(2026, 4, 12, 19, 21, 27, 257033)

In [100]:
d - t1

datetime.datetime(2026, 3, 15, 19, 21, 27, 257033)

¿Y tiempos negativos?

In [101]:
t2 = timedelta(days=-1)

In [102]:
d

datetime.datetime(2026, 3, 29, 19, 21, 27, 257033)

In [103]:
d + t2

datetime.datetime(2026, 3, 28, 19, 21, 27, 257033)

In [104]:
d - t2

datetime.datetime(2026, 3, 30, 19, 21, 27, 257033)

¿Cambios de mes?

In [105]:
t3 = timedelta(days=5)

In [106]:
datetime.date(2021, 2, 28) + t3

datetime.date(2021, 3, 5)

In [107]:
# notar que también funciona para años bisiestos
datetime.date(2020, 2, 28) + t3

datetime.date(2020, 3, 4)

#### Formatear a string con `.strftime`

Permite convertir un objeto datetime a una cadena de caracteres que siga un patrón específico para representar la fecha y la hora.

In [108]:
d

datetime.datetime(2026, 3, 29, 19, 21, 27, 257033)

In [109]:
s1 = d.strftime("%A %d/%m/%Y, %H:%M:%S")
# dd/mm/YY H:M:S format
s1

'Sunday 29/03/2026, 19:21:27'

In [110]:
s1 = d.strftime("%m/%d/%Y, %H:%M:%S")
# dd/mm/YY H:M:S format
s1

'03/29/2026, 19:21:27'

In [111]:
s1 = d.strftime("%d/%m/%Y")
# dd/mm/YY H:M:S format
s1

'29/03/2026'

In [112]:
s2 = d.strftime("%A %d %B %Y, %X")
# dd/mm/YY H:M:S format
s2

'Sunday 29 March 2026, 19:21:27'

Referencia completa de formateo de fechas:

https://www.programiz.com/python-programming/datetime/strftime

---


###  Datos temporales en Pandas

Pandas implementa su propio sistema de datetimes.
`pd.to_datetimes` nos permite convertir una `Serie` o un `DataFrame` en una `Serie` de datetimes.

In [113]:
t_chile.head(3)

       Temperature  Year Month Country ISO3
10608      12.5386  1991   Jan   Chile  CHL
10609      12.2914  1991   Feb   Chile  CHL
10610      11.1373  1991   Mar   Chile  CHL

In [114]:
dates = t_chile.loc[:, ["Year", "Month"]]
dates

       Year Month
10608  1991   Jan
10609  1991   Feb
10610  1991   Mar
10611  1991   Apr
10612  1991   May
...     ...   ...
10915  2016   Aug
10916  2016   Sep
10917  2016   Oct
10918  2016   Nov
10919  2016   Dec

[312 rows x 2 columns]

In [115]:
dates.loc[:, "Day"] = 1
dates

       Year Month  Day
10608  1991   Jan    1
10609  1991   Feb    1
10610  1991   Mar    1
10611  1991   Apr    1
10612  1991   May    1
...     ...   ...  ...
10915  2016   Aug    1
10916  2016   Sep    1
10917  2016   Oct    1
10918  2016   Nov    1
10919  2016   Dec    1

[312 rows x 3 columns]

In [116]:
dates.dtypes

Year     int64
Month      str
Day      int64
dtype: object

In [117]:
dates = dates.astype(str)
concat_dates = (
    dates.loc[:, 'Year']
    + ' '
    +  dates.loc[:, 'Month'] 
    + ' '
    + dates.loc[:, 'Day']
)

concat_dates

10608    1991 Jan 1
10609    1991 Feb 1
10610    1991 Mar 1
10611    1991 Apr 1
10612    1991 May 1
            ...
10915    2016 Aug 1
10916    2016 Sep 1
10917    2016 Oct 1
10918    2016 Nov 1
10919    2016 Dec 1
Length: 312, dtype: str

In [118]:
parsed_dates = pd.to_datetime(concat_dates)
parsed_dates

10608   1991-01-01
10609   1991-02-01
10610   1991-03-01
10611   1991-04-01
10612   1991-05-01
           ...
10915   2016-08-01
10916   2016-09-01
10917   2016-10-01
10918   2016-11-01
10919   2016-12-01
Length: 312, dtype: datetime64[us]

In [119]:
parsed_dates.dtype

dtype('<M8[us]')

In [120]:
# aquí le dimos el formato con el cuál queríamos leer la fecha.

parsed_dates_2 = pd.to_datetime(concat_dates, format="%Y %b %d")

In [121]:
parsed_dates_2

10608   1991-01-01
10609   1991-02-01
10610   1991-03-01
10611   1991-04-01
10612   1991-05-01
           ...
10915   2016-08-01
10916   2016-09-01
10917   2016-10-01
10918   2016-11-01
10919   2016-12-01
Length: 312, dtype: datetime64[us]

In [122]:
pd.to_datetime(concat_dates, format="%Y %b %d") > "2016 01 01"

10608    False
10609    False
10610    False
10611    False
10612    False
         ...
10915     True
10916     True
10917     True
10918     True
10919     True
Length: 312, dtype: bool

In [123]:
t_chile.loc[:, 'dates'] = parsed_dates

In [124]:
t_chile.info()

<class 'pandas.DataFrame'>
RangeIndex: 312 entries, 10608 to 10919
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  312 non-null    float64
 1   Year         312 non-null    int64
 2   Month        312 non-null    str
 3   Country      312 non-null    str
 4   ISO3         312 non-null    str
 5   dates        312 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 14.8 KB

In [125]:
import plotly.express as px

px.line(t_chile, x="dates", y="Temperature", height=600)

#### Valores Inválidos

Puede ocurrir que tengamos algún dato inválido que no podamos transformar a `datetime`.

`pd.to_datetime` ofrece el siguiente parámetro para manejar estos problemas:

`errors{‘ignore’, ‘raise’, ‘coerce’}, default ‘raise’`

- If `raise`, then invalid parsing will raise an exception.

- If `coerce`, then invalid parsing will be set as NaT.

- If `ignore`, then invalid parsing will return the input.


**Nota:** NaT = Not a Time

In [126]:
pd.to_datetime(["2009/07/31", "asd"], errors="coerce")

DatetimeIndex(['2009-07-31', 'NaT'], dtype='datetime64[us]', freq=None)

#### Comparaciones y consultas

Se puede especificar directamente filtros booleanos usando datetimes como también strings:

In [127]:
t_chile.loc[:, "dates"]

10608   1991-01-01
10609   1991-02-01
10610   1991-03-01
10611   1991-04-01
10612   1991-05-01
           ...
10915   2016-08-01
10916   2016-09-01
10917   2016-10-01
10918   2016-11-01
10919   2016-12-01
Name: dates, Length: 312, dtype: datetime64[us]

In [128]:
t_chile.loc[:, "dates"] > datetime.datetime(2010, 1, 1)

10608    False
10609    False
10610    False
10611    False
10612    False
         ...
10915     True
10916     True
10917     True
10918     True
10919     True
Name: dates, Length: 312, dtype: bool

#### Indexado

Podemos fijar las fechas como índices y luego indexar por rangos de estas

In [129]:
temperaturas_por_fecha = t_chile.set_index("dates")
temperaturas_por_fecha

            Temperature  Year Month Country ISO3
dates
1991-01-01     12.53860  1991   Jan   Chile  CHL
1991-02-01     12.29140  1991   Feb   Chile  CHL
1991-03-01     11.13730  1991   Mar   Chile  CHL
1991-04-01      8.85700  1991   Apr   Chile  CHL
1991-05-01      6.70605  1991   May   Chile  CHL
...                 ...   ...   ...     ...  ...
2016-08-01      5.83910  2016   Aug   Chile  CHL
2016-09-01      7.19059  2016   Sep   Chile  CHL
2016-10-01      8.81492  2016   Oct   Chile  CHL
2016-11-01     10.71450  2016   Nov   Chile  CHL
2016-12-01     12.39610  2016   Dec   Chile  CHL

[312 rows x 5 columns]

In [130]:
# Rango 1995-1-1 al 199-12-1
temperaturas_por_fecha.loc["1995-1-1":"1999-12-1"]

            Temperature  Year Month Country ISO3
dates
1995-01-01     12.33850  1995   Jan   Chile  CHL
1995-02-01     11.84780  1995   Feb   Chile  CHL
1995-03-01     10.63670  1995   Mar   Chile  CHL
1995-04-01      9.11017  1995   Apr   Chile  CHL
1995-05-01      6.80263  1995   May   Chile  CHL
1995-06-01      4.16912  1995   Jun   Chile  CHL
1995-07-01      2.62724  1995   Jul   Chile  CHL
1995-08-01      3.64301  1995   Aug   Chile  CHL
1995-09-01      6.32269  1995   Sep   Chile  CHL
1995-10-01      8.33436  1995   Oct   Chile  CHL
1995-11-01     10.45440  1995   Nov   Chile  CHL
1995-12-01     13.27430  1995   Dec   Chile  CHL
1996-01-01     11.93590  1996   Jan   Chile  CHL
1996-02-01     11.56990  1996   Feb   Chile  CHL
1996-03-01     11.25920  1996   Mar   Chile  CHL
1996-04-01      7.99297  1996   Apr   Chile  CHL
1996-05-01      7.19890  1996   May   Chile  CHL
1996-06-01      3.54486  1996   Jun   Chile  CHL
1996-07-01      4.34828  1996   Jul   Chile  CHL
1996-08-01      5.41100  1996   Aug   Chile  CHL
1996-09-01      6.91179  1996   Sep   Chile  CHL
1996-10-01      8.49536  1996   Oct   Chile  CHL
1996-11-01     10.22810  1996   Nov   Chile  CHL
1996-12-01     11.64740  1996   Dec   Chile  CHL
1997-01-01     12.74460  1997   Jan   Chile  CHL
1997-02-01     11.15750  1997   Feb   Chile  CHL
1997-03-01     11.60880  1997   Mar   Chile  CHL
1997-04-01      9.48273  1997   Apr   Chile  CHL
1997-05-01      6.90652  1997   May   Chile  CHL
1997-06-01      4.84893  1997   Jun   Chile  CHL
1997-07-01      4.80792  1997   Jul   Chile  CHL
1997-08-01      5.09215  1997   Aug   Chile  CHL
1997-09-01      6.72262  1997   Sep   Chile  CHL
1997-10-01      7.99191  1997   Oct   Chile  CHL
1997-11-01     10.18290  1997   Nov   Chile  CHL
1997-12-01     11.97140  1997   Dec   Chile  CHL
1998-01-01     12.73960  1998   Jan   Chile  CHL
1998-02-01     12.74520  1998   Feb   Chile  CHL
1998-03-01     11.12040  1998   Mar   Chile  CHL
1998-04-01      9.02652  1998   Apr   Chile  CHL
1998-05-01      7.43721  1998   May   Chile  CHL
1998-06-01      5.62819  1998   Jun   Chile  CHL
1998-07-01      5.82987  1998   Jul   Chile  CHL
1998-08-01      5.45415  1998   Aug   Chile  CHL
1998-09-01      5.71679  1998   Sep   Chile  CHL
1998-10-01      8.84985  1998   Oct   Chile  CHL
1998-11-01     10.19320  1998   Nov   Chile  CHL
1998-12-01     12.10560  1998   Dec   Chile  CHL
1999-01-01     12.81570  1999   Jan   Chile  CHL
1999-02-01     12.74090  1999   Feb   Chile  CHL
1999-03-01     10.73130  1999   Mar   Chile  CHL
1999-04-01      8.12245  1999   Apr   Chile  CHL
1999-05-01      6.31238  1999   May   Chile  CHL
1999-06-01      3.63432  1999   Jun   Chile  CHL
1999-07-01      3.65039  1999   Jul   Chile  CHL
1999-08-01      5.12151  1999   Aug   Chile  CHL
1999-09-01      6.75440  1999   Sep   Chile  CHL
1999-10-01      8.70829  1999   Oct   Chile  CHL
1999-11-01     10.32940  1999   Nov   Chile  CHL
1999-12-01     11.55970  1999   Dec   Chile  CHL

In [131]:
temperaturas_por_fecha.loc["1999-11-1":"1999-12-1"]

            Temperature  Year Month Country ISO3
dates
1999-11-01      10.3294  1999   Nov   Chile  CHL
1999-12-01      11.5597  1999   Dec   Chile  CHL

#### Timedeltas

`pd.Timedelta` permite utilizar una interfaz similar a los `datetime.timedelta` para ejecutar cálculos sobre las fechas:

`weeks, days, hours, minutes, seconds, milliseconds, microseconds, nanoseconds`

In [132]:
ptd1 = pd.Timedelta(weeks=2)
ptd1

Timedelta('14 days 00:00:00')

In [133]:
t_chile.loc[:, "dates"] + ptd1

10608   1991-01-15
10609   1991-02-15
10610   1991-03-15
10611   1991-04-15
10612   1991-05-15
           ...
10915   2016-08-15
10916   2016-09-15
10917   2016-10-15
10918   2016-11-15
10919   2016-12-15
Name: dates, Length: 312, dtype: datetime64[us]

Y podemos también hacer Broadcasting con `datetime.timedeltas`

In [134]:
t_chile.loc[:, "dates"] + datetime.timedelta(days=-1)

10608   1990-12-31
10609   1991-01-31
10610   1991-02-28
10611   1991-03-31
10612   1991-04-30
           ...
10915   2016-07-31
10916   2016-08-31
10917   2016-09-30
10918   2016-10-31
10919   2016-11-30
Name: dates, Length: 312, dtype: datetime64[us]

In [135]:
datetime.datetime.now()

datetime.datetime(2026, 3, 29, 19, 22, 12, 425554)

In [136]:
datetime.datetime.now() - t_chile.loc[:, "dates"]

10608   12871 days 19:22:12.964384
10609   12840 days 19:22:12.964384
10610   12812 days 19:22:12.964384
10611   12781 days 19:22:12.964384
10612   12751 days 19:22:12.964384
                   ...
10915    3527 days 19:22:12.964384
10916    3496 days 19:22:12.964384
10917    3466 days 19:22:12.964384
10918    3435 days 19:22:12.964384
10919    3405 days 19:22:12.964384
Name: dates, Length: 312, dtype: timedelta64[us]

In [137]:
(datetime.datetime.now() - t_chile.loc[:, "dates"]).dt.days

10608    12871
10609    12840
10610    12812
10611    12781
10612    12751
         ...
10915     3527
10916     3496
10917     3466
10918     3435
10919     3405
Name: dates, Length: 312, dtype: int64

---

> **Pregunta ❓:** ¿Cómo podría saber el promedio de temperaturas por año?

## 3.- Agregaciones

Una de las principales operaciones de datos son las agrupaciones, que permiten agrupar por alguna columna agregando el resto de las columnas con alguna operación. Por ejemplo, podemos agrupar por año y aplicar alguna función de agregación a la temperatura, obteniendo el promedio por año, maximo por año, desviacion estandar, etc.

In [138]:
t_chile

       Temperature  Year Month Country ISO3      dates
10608     12.53860  1991   Jan   Chile  CHL 1991-01-01
10609     12.29140  1991   Feb   Chile  CHL 1991-02-01
10610     11.13730  1991   Mar   Chile  CHL 1991-03-01
10611      8.85700  1991   Apr   Chile  CHL 1991-04-01
10612      6.70605  1991   May   Chile  CHL 1991-05-01
...            ...   ...   ...     ...  ...        ...
10915      5.83910  2016   Aug   Chile  CHL 2016-08-01
10916      7.19059  2016   Sep   Chile  CHL 2016-09-01
10917      8.81492  2016   Oct   Chile  CHL 2016-10-01
10918     10.71450  2016   Nov   Chile  CHL 2016-11-01
10919     12.39610  2016   Dec   Chile  CHL 2016-12-01

[312 rows x 6 columns]

In [139]:
t_chile.loc[:, "Year"].unique()

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016])

In [140]:
t_chile[t_chile.loc[:, "Year"] == 1991]

       Temperature  Year Month Country ISO3      dates
10608     12.53860  1991   Jan   Chile  CHL 1991-01-01
10609     12.29140  1991   Feb   Chile  CHL 1991-02-01
10610     11.13730  1991   Mar   Chile  CHL 1991-03-01
10611      8.85700  1991   Apr   Chile  CHL 1991-04-01
10612      6.70605  1991   May   Chile  CHL 1991-05-01
10613      4.64511  1991   Jun   Chile  CHL 1991-06-01
10614      3.67834  1991   Jul   Chile  CHL 1991-07-01
10615      4.05806  1991   Aug   Chile  CHL 1991-08-01
10616      6.60080  1991   Sep   Chile  CHL 1991-09-01
10617      7.41883  1991   Oct   Chile  CHL 1991-10-01
10618      9.96322  1991   Nov   Chile  CHL 1991-11-01
10619     10.20070  1991   Dec   Chile  CHL 1991-12-01

In [141]:
t_chile[t_chile.loc[:, "Year"] == 1991].loc[:, "Temperature"].mean()

np.float64(8.174617499999998)

In [142]:
t_chile[t_chile.loc[:, "Year"] == 1992].loc[:, "Temperature"].mean()

np.float64(8.132774166666666)

In [143]:
t_chile[t_chile.loc[:, "Year"] == 1993].loc[:, "Temperature"].mean()

np.float64(8.435058333333332)

---

### 3.1 Agregaciones con `GroupBy`


![Group By](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/09-Pandas2/group_by.png)

**Group by** es un proceso que implica uno o más de los siguientes pasos:


- **Separar** los datos bajo algún criterio o grupo.

- **Aplicar** esta función a estos datos agrupados.

- **Combinar** los resultados en un nuevo `DataFrame`.


Luego, definimos agregar como calcular alguna métrica o estadístico por grupo.

<div align='center'>
<img src="https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/09-Pandas2/aggregations.png" alt="Agregaciones" width=500px/>
</div>

#### Paso 1: Separar

En esta parte veremos el primer paso del group-by: **Separar** por grupos.


![Group By](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/09-Pandas2/group_by.png)

Para esto, agrupamos temperaturas de Chile por mes:

#### Cantidad de Grupos

In [144]:
t_chile.head(15)

       Temperature  Year Month Country ISO3      dates
10608     12.53860  1991   Jan   Chile  CHL 1991-01-01
10609     12.29140  1991   Feb   Chile  CHL 1991-02-01
10610     11.13730  1991   Mar   Chile  CHL 1991-03-01
10611      8.85700  1991   Apr   Chile  CHL 1991-04-01
10612      6.70605  1991   May   Chile  CHL 1991-05-01
10613      4.64511  1991   Jun   Chile  CHL 1991-06-01
10614      3.67834  1991   Jul   Chile  CHL 1991-07-01
10615      4.05806  1991   Aug   Chile  CHL 1991-08-01
10616      6.60080  1991   Sep   Chile  CHL 1991-09-01
10617      7.41883  1991   Oct   Chile  CHL 1991-10-01
10618      9.96322  1991   Nov   Chile  CHL 1991-11-01
10619     10.20070  1991   Dec   Chile  CHL 1991-12-01
10620     13.35360  1992   Jan   Chile  CHL 1992-01-01
10621     11.47090  1992   Feb   Chile  CHL 1992-02-01
10622     11.54690  1992   Mar   Chile  CHL 1992-03-01

In [145]:
t_chile.groupby("Year")

In [146]:
t_chile.groupby("Year").groups

{1991: [10608, 10609, 10610, 10611, 10612, 10613, 10614, 10615, 10616, 10617, 10618, 10619], 1992: [10620, 10621, 10622, 10623, 10624, 10625, 10626, 10627, 10628, 10629, 10630, 10631], 1993: [10632, 10633, 10634, 10635, 10636, 10637, 10638, 10639, 10640, 10641, 10642, 10643], 1994: [10644, 10645, 10646, 10647, 10648, 10649, 10650, 10651, 10652, 10653, 10654, 10655], 1995: [10656, 10657, 10658, 10659, 10660, 10661, 10662, 10663, 10664, 10665, 10666, 10667], 1996: [10668, 10669, 10670, 10671, 10672, 10673, 10674, 10675, 10676, 10677, 10678, 10679], 1997: [10680, 10681, 10682, 10683, 10684, 10685, 10686, 10687, 10688, 10689, 10690, 10691], 1998: [10692, 10693, 10694, 10695, 10696, 10697, 10698, 10699, 10700, 10701, 10702, 10703], 1999: [10704, 10705, 10706, 10707, 10708, 10709, 10710, 10711, 10712, 10713, 10714, 10715], 2000: [10716, 10717, 10718, 10719, 10720, 10721, 10722, 10723, 10724, 10725, 10726, 10727], 2001: [10728, 10729, 10730, 10731, 10732, 10733, 10734, 10735, 10736, 10737, 10738, 10739], 2002: [10740, 10741, 10742, 10743, 10744, 10745, 10746, 10747, 10748, 10749, 10750, 10751], 2003: [10752, 10753, 10754, 10755, 10756, 10757, 10758, 10759, 10760, 10761, 10762, 10763], 2004: [10764, 10765, 10766, 10767, 10768, 10769, 10770, 10771, 10772, 10773, 10774, 10775], 2005: [10776, 10777, 10778, 10779, 10780, 10781, 10782, 10783, 10784, 10785, 10786, 10787], 2006: [10788, 10789, 10790, 10791, 10792, 10793, 10794, 10795, 10796, 10797, 10798, 10799], 2007: [10800, 10801, 10802, 10803, 10804, 10805, 10806, 10807, 10808, 10809, 10810, 10811], 2008: [10812, 10813, 10814, 10815, 10816, 10817, 10818, 10819, 10820, 10821, 10822, 10823], 2009: [10824, 10825, 10826, 10827, 10828, 10829, 10830, 10831, 10832, 10833, 10834, 10835], 2010: [10836, 10837, 10838, 10839, 10840, 10841, 10842, 10843, 10844, 10845, 10846, 10847], 2011: [10848, 10849, 10850, 10851, 10852, 10853, 10854, 10855, 10856, 10857, 10858, 10859], 2012: [10860, 10861, 10862, 10863, 10864, 10865, 10866, 10867, 10868, 10869, 10870, 10871], 2013: [10872, 10873, 10874, 10875, 10876, 10877, 10878, 10879, 10880, 10881, 10882, 10883], 2014: [10884, 10885, 10886, 10887, 10888, 10889, 10890, 10891, 10892, 10893, 10894, 10895], 2015: [10896, 10897, 10898, 10899, 10900, 10901, 10902, 10903, 10904, 10905, 10906, 10907], 2016: [10908, 10909, 10910, 10911, 10912, 10913, 10914, 10915, 10916, 10917, 10918, 10919]}

In [147]:
t_chile.loc[
    [10608, 10609, 10610, 10611, 10612, 10613, 10614, 10615, 10616, 10617, 10618, 10619]
]

       Temperature  Year Month Country ISO3      dates
10608     12.53860  1991   Jan   Chile  CHL 1991-01-01
10609     12.29140  1991   Feb   Chile  CHL 1991-02-01
10610     11.13730  1991   Mar   Chile  CHL 1991-03-01
10611      8.85700  1991   Apr   Chile  CHL 1991-04-01
10612      6.70605  1991   May   Chile  CHL 1991-05-01
10613      4.64511  1991   Jun   Chile  CHL 1991-06-01
10614      3.67834  1991   Jul   Chile  CHL 1991-07-01
10615      4.05806  1991   Aug   Chile  CHL 1991-08-01
10616      6.60080  1991   Sep   Chile  CHL 1991-09-01
10617      7.41883  1991   Oct   Chile  CHL 1991-10-01
10618      9.96322  1991   Nov   Chile  CHL 1991-11-01
10619     10.20070  1991   Dec   Chile  CHL 1991-12-01

#### Obtener algún grupo en particular

In [148]:
t_chile[t_chile.loc[:, "Year"] == 1991]

       Temperature  Year Month Country ISO3      dates
10608     12.53860  1991   Jan   Chile  CHL 1991-01-01
10609     12.29140  1991   Feb   Chile  CHL 1991-02-01
10610     11.13730  1991   Mar   Chile  CHL 1991-03-01
10611      8.85700  1991   Apr   Chile  CHL 1991-04-01
10612      6.70605  1991   May   Chile  CHL 1991-05-01
10613      4.64511  1991   Jun   Chile  CHL 1991-06-01
10614      3.67834  1991   Jul   Chile  CHL 1991-07-01
10615      4.05806  1991   Aug   Chile  CHL 1991-08-01
10616      6.60080  1991   Sep   Chile  CHL 1991-09-01
10617      7.41883  1991   Oct   Chile  CHL 1991-10-01
10618      9.96322  1991   Nov   Chile  CHL 1991-11-01
10619     10.20070  1991   Dec   Chile  CHL 1991-12-01

In [149]:
t_chile.groupby("Year").get_group(1991)

       Temperature  Year Month Country ISO3      dates
10608     12.53860  1991   Jan   Chile  CHL 1991-01-01
10609     12.29140  1991   Feb   Chile  CHL 1991-02-01
10610     11.13730  1991   Mar   Chile  CHL 1991-03-01
10611      8.85700  1991   Apr   Chile  CHL 1991-04-01
10612      6.70605  1991   May   Chile  CHL 1991-05-01
10613      4.64511  1991   Jun   Chile  CHL 1991-06-01
10614      3.67834  1991   Jul   Chile  CHL 1991-07-01
10615      4.05806  1991   Aug   Chile  CHL 1991-08-01
10616      6.60080  1991   Sep   Chile  CHL 1991-09-01
10617      7.41883  1991   Oct   Chile  CHL 1991-10-01
10618      9.96322  1991   Nov   Chile  CHL 1991-11-01
10619     10.20070  1991   Dec   Chile  CHL 1991-12-01

#### Paso 2: Aplicar

En este paso veremos las distintas opciones que tenemos en el paso **aplicar**: agregar, transformar o filtrar.

![Group By](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/09-Pandas2/group_by.png)

#### Agregar

Las funciones que ofrece pandas son:

<div align='center'>
<img src="https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/09-Pandas2/aggregations.png" alt="Agregaciones" width=500px/>
</div>

##### Tamaño

In [150]:
t_chile.groupby("Year").size()

Year
1991    12
1992    12
1993    12
1994    12
1995    12
1996    12
1997    12
1998    12
1999    12
2000    12
2001    12
2002    12
2003    12
2004    12
2005    12
2006    12
2007    12
2008    12
2009    12
2010    12
2011    12
2012    12
2013    12
2014    12
2015    12
2016    12
dtype: int64

##### Promedio

**Por  Mes**

In [151]:
t_chile

       Temperature  Year Month Country ISO3      dates
10608     12.53860  1991   Jan   Chile  CHL 1991-01-01
10609     12.29140  1991   Feb   Chile  CHL 1991-02-01
10610     11.13730  1991   Mar   Chile  CHL 1991-03-01
10611      8.85700  1991   Apr   Chile  CHL 1991-04-01
10612      6.70605  1991   May   Chile  CHL 1991-05-01
...            ...   ...   ...     ...  ...        ...
10915      5.83910  2016   Aug   Chile  CHL 2016-08-01
10916      7.19059  2016   Sep   Chile  CHL 2016-09-01
10917      8.81492  2016   Oct   Chile  CHL 2016-10-01
10918     10.71450  2016   Nov   Chile  CHL 2016-11-01
10919     12.39610  2016   Dec   Chile  CHL 2016-12-01

[312 rows x 6 columns]

In [152]:
t_chile_prom_mes = t_chile.groupby("Year").mean()
t_chile_prom_mes

TypeError: dtype 'str' does not support operation 'mean'

In [153]:
temperaturas.groupby("Year").mean(numeric_only=True)

      Temperature
Year
1991    18.716174
1992    18.651461
1993    18.632208
1994    18.944268
1995    18.937594
1996    18.630084
1997    18.922807
1998    19.273504
1999    19.085536
2000    19.083361
2001    19.177183
2002    19.296718
2003    19.208448
2004    19.167283
2005    19.185109
2006    19.228243
2007    19.311888
2008    19.172404
2009    19.327523
2010    19.365938
2011    19.184153
2012    19.197032
2013    19.259569
2014    19.464966
2015    19.581111
2016    19.642927

In [154]:
temperaturas.groupby("Year")["Temperature"].mean()

Year
1991    18.716174
1992    18.651461
1993    18.632208
1994    18.944268
1995    18.937594
1996    18.630084
1997    18.922807
1998    19.273504
1999    19.085536
2000    19.083361
2001    19.177183
2002    19.296718
2003    19.208448
2004    19.167283
2005    19.185109
2006    19.228243
2007    19.311888
2008    19.172404
2009    19.327523
2010    19.365938
2011    19.184153
2012    19.197032
2013    19.259569
2014    19.464966
2015    19.581111
2016    19.642927
Name: Temperature, dtype: float64

In [155]:
px.line(temperaturas.groupby("Year").mean(numeric_only=True).reset_index(), x='Year', y='Temperature')

> Ejercicio: Agrupar por paises y ver como se mueve la media.

**Por Año**

In [156]:
t_chile_prom_año = t_chile.groupby("Year").mean(numeric_only=True)
t_chile_prom_año

      Temperature
Year
1991     8.174618
1992     8.132774
1993     8.435058
1994     8.583360
1995     8.296743
1996     8.378638
1997     8.626498
1998     8.903882
1999     8.373395
2000     7.910688
2001     8.227404
2002     8.072337
2003     8.561853
2004     8.775460
2005     8.271038
2006     8.648243
2007     7.908262
2008     8.683983
2009     8.509471
2010     8.187509
2011     8.494979
2012     8.631189
2013     8.723325
2014     8.548038
2015     8.821257
2016     8.936417

In [157]:
px.line(
    t_chile_prom_año,
    title="Temperatura Promedio en Chile por Año",
)


#### Describe

In [185]:
t_chile["Temperature"].describe()

count    312.000000
mean       8.454478
std        3.126838
min        2.529410
25%        5.569280
50%        8.488035
75%       11.543375
max       13.929600
Name: Temperature, dtype: float64

> Qué tipo de dato tiene como output la función .describe()?

Por mes:

In [158]:
MESES = t_chile['Month'].unique()

In [ ]:
chile_t_stats = t_chile.groupby("Month").describe()["Temperature"]
chile_t_stats = chile_t_stats.loc[MESES]
chile_t_stats

,count,mean,min,25%,50%,75%,max,std
Month,,,,,,,,
Jan,26.0,12.890127,11.93590,12.552500,12.747900,13.157900,13.92960,0.489691
Feb,26.0,12.331531,11.15750,11.855550,12.459100,12.744125,13.63310,0.634695
Mar,26.0,11.175054,10.13310,10.753150,11.198250,11.646675,12.18950,0.583369
Apr,26.0,8.632918,7.82234,8.197055,8.531000,8.853077,9.87860,0.561895
May,26.0,6.305406,4.75968,5.735210,6.363575,6.760283,7.43721,0.658122
Jun,26.0,4.566924,2.61044,4.182020,4.681900,5.105257,5.62819,0.731938
Jul,26.0,3.990776,2.52941,3.643715,3.995465,4.568388,5.82987,0.782743
Aug,26.0,4.874367,3.25353,4.381372,5.060210,5.360117,6.08457,0.694196
Sep,26.0,6.479313,5.11566,6.202398,6.596555,6.762740,7.26955,0.492104
Oct,26.0,8.313173,7.41883,8.022638,8.346980,8.678900,9.11434,0.443089
Nov,26.0,10.031982,8.91301,9.827340,10.085450,10.339450,10.93300,0.487848
Dec,26.0,11.862162,10.20070,11.546575,11.749950,12.355850,13.27430,0.669272

In [160]:
px.line(
    chile_t_stats.reset_index(),
    x="Month",
    y="mean",
    error_y="std",
    title="Temperatura por Mes",
)

#### Multi-indice

También podemos ejecutar la agregación sobre varias columnas. Esto generará un DataFrame multi-indice.
Los multi-indices pueden aparecer tanto en las filas como en las columnas.

In [211]:
stats_general = temperaturas.groupby(
    ["Year", "Country"]
).mean(numeric_only=True)

stats_general

                    Temperature
Year Country
1991 Afghanistan      12.894488
     Albania          11.037649
     Algeria          22.513458
     Andorra          11.188148
     Angola           21.716883
...                         ...
2016 United States     9.030837
     Uruguay          17.658226
     Uzbekistan       14.219507
     Vanuatu          24.532208
     Venezuela        26.478200

[4992 rows x 1 columns]

In [212]:
stats_general.index

MultiIndex([(1991,          'Afghanistan'),
            (1991,              'Albania'),
            (1991,              'Algeria'),
            (1991,              'Andorra'),
            (1991,               'Angola'),
            (1991,  'Antigua and Barbuda'),
            (1991,            'Argentina'),
            (1991,              'Armenia'),
            (1991,            'Australia'),
            (1991,              'Austria'),
            ...
            (2016,               'Tuvalu'),
            (2016,               'Uganda'),
            (2016,              'Ukraine'),
            (2016, 'United Arab Emirates'),
            (2016,       'United Kingdom'),
            (2016,        'United States'),
            (2016,              'Uruguay'),
            (2016,           'Uzbekistan'),
            (2016,              'Vanuatu'),
            (2016,            'Venezuela')],
           names=['Year', 'Country'], length=4992)

In [213]:
stats_general.loc[1991]

               Temperature
Country
Afghanistan      12.894488
Albania          11.037649
Algeria          22.513458
Andorra          11.188148
Angola           21.716883
...                    ...
United States     7.565832
Uruguay          18.009783
Uzbekistan       12.679177
Vanuatu          23.859533
Venezuela        25.475858

[192 rows x 1 columns]

In [214]:
stats_general = temperaturas.groupby(["Country", "Year"]).mean(numeric_only=True)
stats_general

                  Temperature
Country     Year
Afghanistan 1991    12.894488
            1992    12.544548
            1993    12.977138
            1994    13.080018
            1995    13.040895
...                       ...
Venezuela   2012    25.764883
            2013    25.922492
            2014    26.028775
            2015    26.438175
            2016    26.478200

[4992 rows x 1 columns]

In [216]:
stats_general.loc["Chile"]

      Temperature
Year
1991     8.174618
1992     8.132774
1993     8.435058
1994     8.583360
1995     8.296743
1996     8.378638
1997     8.626498
1998     8.903882
1999     8.373395
2000     7.910688
2001     8.227404
2002     8.072337
2003     8.561853
2004     8.775460
2005     8.271038
2006     8.648243
2007     7.908262
2008     8.683983
2009     8.509471
2010     8.187509
2011     8.494979
2012     8.631189
2013     8.723325
2014     8.548038
2015     8.821257
2016     8.936417

Noten que esta operación retorna una serie con un multi-índice en los índices.

In [217]:
stats_general.index

MultiIndex([('Afghanistan', 1991),
            ('Afghanistan', 1992),
            ('Afghanistan', 1993),
            ('Afghanistan', 1994),
            ('Afghanistan', 1995),
            ('Afghanistan', 1996),
            ('Afghanistan', 1997),
            ('Afghanistan', 1998),
            ('Afghanistan', 1999),
            ('Afghanistan', 2000),
            ...
            (  'Venezuela', 2007),
            (  'Venezuela', 2008),
            (  'Venezuela', 2009),
            (  'Venezuela', 2010),
            (  'Venezuela', 2011),
            (  'Venezuela', 2012),
            (  'Venezuela', 2013),
            (  'Venezuela', 2014),
            (  'Venezuela', 2015),
            (  'Venezuela', 2016)],
           names=['Country', 'Year'], length=4992)

Pueden acceder a un sub-índice usando los mismos indexadores que hemos visto hasta el momento.

In [218]:
stats_general.loc["Chile"].head()

      Temperature
Year
1991     8.174618
1992     8.132774
1993     8.435058
1994     8.583360
1995     8.296743

Y podemos acceder a una medición en particular usando tuplas:

In [220]:
stats_general.loc[("Chile", 2015)]

Temperature    8.821257
Name: (Chile, 2015), dtype: float64

In [221]:
stats_general.loc[("Chile", 2016)]

Temperature    8.936417
Name: (Chile, 2016), dtype: float64

Con `item` se obtiene el dato nativo dentro del iterador siempre que tenga un único elemento. Aplica también para numpy y torch

In [228]:
stats_general.loc[("Chile", 2016)].item()

8.936416666666666

In [229]:
stats_general.loc[("Chile", 2016), "Temperature"]

np.float64(8.936416666666666)

In [230]:
stats_general.loc[("Chile", 2016), "Temperature"].item()

8.936416666666666

Para aplanar el dataframe, pueden usar el método `reset_index()`

In [232]:
stats_general = stats_general.reset_index()
stats_general

          Country  Year  Temperature
0     Afghanistan  1991    12.894488
1     Afghanistan  1992    12.544548
2     Afghanistan  1993    12.977138
3     Afghanistan  1994    13.080018
4     Afghanistan  1995    13.040895
...           ...   ...          ...
4987    Venezuela  2012    25.764883
4988    Venezuela  2013    25.922492
4989    Venezuela  2014    26.028775
4990    Venezuela  2015    26.438175
4991    Venezuela  2016    26.478200

[4992 rows x 3 columns]

In [236]:
mascara = stats_general["Country"].isin(
    ["Argentina", "Chile", "Peru", "Paraguay", "Uruguay"]
)
mascara

0       False
1       False
2       False
3       False
4       False
        ...
4987    False
4988    False
4989    False
4990    False
4991    False
Name: Country, Length: 4992, dtype: bool

In [237]:
# filtramos para obtener solo los valores en la lista a través del método .isin
temperature_stats_general_filtrado = stats_general.loc[mascara, :]
temperature_stats_general_filtrado

        Country  Year  Temperature
156   Argentina  1991    14.434009
157   Argentina  1992    14.101930
158   Argentina  1993    14.460730
159   Argentina  1994    15.015298
160   Argentina  1995    14.436392
...         ...   ...          ...
4909    Uruguay  2012    18.457469
4910    Uruguay  2013    17.766600
4911    Uruguay  2014    18.327175
4912    Uruguay  2015    18.386833
4913    Uruguay  2016    17.658226

[130 rows x 3 columns]

In [238]:
px.line(
    temperature_stats_general_filtrado.reset_index(),
    x="Year",
    y="Temperature",
    color="Country",
    height=400,
)

### `agg`

`agg` permite agregar datos por grupo usando una o más operaciones a través de un diccionario.
El resultado también será un dataframe multi-índice, pero por columnas:

In [256]:
stats_general.head()

       Country  Year  Temperature
0  Afghanistan  1991    12.894488
1  Afghanistan  1992    12.544548
2  Afghanistan  1993    12.977138
3  Afghanistan  1994    13.080018
4  Afghanistan  1995    13.040895

In [272]:
stats_general[stats_general["Temperature"] == stats_general["Temperature"].min()]#.min()

        Country  Year  Temperature
1743  Greenland  1992   -18.711308

In [311]:
stats_temperatura_globales = temperaturas.groupby(["Country", "Year"]).agg(
    {
        "Temperature": ["mean", "min", "max"]
    }
)
stats_temperatura_globales

                 Temperature
                        mean       min      max
Country     Year
Afghanistan 1991   12.894488  -0.03110  25.5710
            1992   12.544548   0.74637  24.7068
            1993   12.977138  -0.08350  24.6320
            1994   13.080018   1.11415  25.0045
            1995   13.040895   0.92358  25.7798
...                      ...       ...      ...
Venezuela   2012   25.764883  25.21710  26.4330
            2013   25.922492  25.29310  27.1409
            2014   26.028775  25.39520  26.9757
            2015   26.438175  25.63690  27.0908
            2016   26.478200  25.84420  27.3357

[4992 rows x 3 columns]

In [312]:
stats_temperatura_globales.columns

MultiIndex([('Temperature', 'mean'),
            ('Temperature',  'min'),
            ('Temperature',  'max')],
           )

In [313]:
stats_temperatura_globales

                 Temperature
                        mean       min      max
Country     Year
Afghanistan 1991   12.894488  -0.03110  25.5710
            1992   12.544548   0.74637  24.7068
            1993   12.977138  -0.08350  24.6320
            1994   13.080018   1.11415  25.0045
            1995   13.040895   0.92358  25.7798
...                      ...       ...      ...
Venezuela   2012   25.764883  25.21710  26.4330
            2013   25.922492  25.29310  27.1409
            2014   26.028775  25.39520  26.9757
            2015   26.438175  25.63690  27.0908
            2016   26.478200  25.84420  27.3357

[4992 rows x 3 columns]

Al igual que el caso de los multi-índices en los índices de las filas, podemos acceder a ciertas series con multi-indices en las columnas a partir de indexadores basados en tuplas.

In [314]:
stats_temperatura_globales.loc[:, ("Temperature", "mean")]

Country      Year
Afghanistan  1991    12.894488
             1992    12.544548
             1993    12.977138
             1994    13.080018
             1995    13.040895
                       ...
Venezuela    2012    25.764883
             2013    25.922492
             2014    26.028775
             2015    26.438175
             2016    26.478200
Name: (Temperature, mean), Length: 4992, dtype: float64

In [315]:
stats_temperatura_globales.loc["Chile", ("Temperature", "mean")]

Year
1991    8.174618
1992    8.132774
1993    8.435058
1994    8.583360
1995    8.296743
1996    8.378638
1997    8.626498
1998    8.903882
1999    8.373395
2000    7.910688
2001    8.227404
2002    8.072337
2003    8.561853
2004    8.775460
2005    8.271038
2006    8.648243
2007    7.908262
2008    8.683983
2009    8.509471
2010    8.187509
2011    8.494979
2012    8.631189
2013    8.723325
2014    8.548038
2015    8.821257
2016    8.936417
Name: (Temperature, mean), dtype: float64

In [316]:
stats_temperatura_globales.reset_index()

          Country  Year Temperature
                               mean       min      max
0     Afghanistan  1991   12.894488  -0.03110  25.5710
1     Afghanistan  1992   12.544548   0.74637  24.7068
2     Afghanistan  1993   12.977138  -0.08350  24.6320
3     Afghanistan  1994   13.080018   1.11415  25.0045
4     Afghanistan  1995   13.040895   0.92358  25.7798
...           ...   ...         ...       ...      ...
4987    Venezuela  2012   25.764883  25.21710  26.4330
4988    Venezuela  2013   25.922492  25.29310  27.1409
4989    Venezuela  2014   26.028775  25.39520  26.9757
4990    Venezuela  2015   26.438175  25.63690  27.0908
4991    Venezuela  2016   26.478200  25.84420  27.3357

[4992 rows x 5 columns]

In [318]:
stats_temperatura_años = stats_temperatura_globales.reset_index().groupby("Year").mean(numeric_only=True)
stats_temperatura_años

C:\Users\Legion4\AppData\Local\Temp\ipykernel_41108\1891896585.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  stats_temperatura_años = stats_temperatura_globales.reset_index().groupby("Year").mean(numeric_only=True)

     Temperature
            mean        min        max
Year
1991   18.716174  12.425384  24.593071
1992   18.651461  12.507192  24.736719
1993   18.632208  12.493521  24.319204
1994   18.944268  12.570835  24.969120
1995   18.937594  12.627499  24.959977
1996   18.630084  12.272468  24.482047
1997   18.922807  12.764943  24.780524
1998   19.273504  12.932765  25.140768
1999   19.085536  13.013959  24.908065
2000   19.083361  12.680137  24.821184
2001   19.177183  12.496451  25.094451
2002   19.296718  12.664616  25.055435
2003   19.208448  12.622125  25.350939
2004   19.167283  12.880217  24.896655
2005   19.185109  12.663865  25.128376
2006   19.228243  12.365998  25.298118
2007   19.311888  12.909805  24.986664
2008   19.172404  12.561335  24.933642
2009   19.327523  12.830872  25.111082
2010   19.365938  12.834823  25.616825
2011   19.184153  12.725442  25.035411
2012   19.197032  12.133187  25.276800
2013   19.259569  12.926394  25.205186
2014   19.464966  13.266000  25.138391
2015   19.581111  13.448540  25.511547
2016   19.642927  13.267694  25.497076

In [319]:
stats_temperatura_años.droplevel(0, axis=1)

           mean        min        max
Year
1991  18.716174  12.425384  24.593071
1992  18.651461  12.507192  24.736719
1993  18.632208  12.493521  24.319204
1994  18.944268  12.570835  24.969120
1995  18.937594  12.627499  24.959977
1996  18.630084  12.272468  24.482047
1997  18.922807  12.764943  24.780524
1998  19.273504  12.932765  25.140768
1999  19.085536  13.013959  24.908065
2000  19.083361  12.680137  24.821184
2001  19.177183  12.496451  25.094451
2002  19.296718  12.664616  25.055435
2003  19.208448  12.622125  25.350939
2004  19.167283  12.880217  24.896655
2005  19.185109  12.663865  25.128376
2006  19.228243  12.365998  25.298118
2007  19.311888  12.909805  24.986664
2008  19.172404  12.561335  24.933642
2009  19.327523  12.830872  25.111082
2010  19.365938  12.834823  25.616825
2011  19.184153  12.725442  25.035411
2012  19.197032  12.133187  25.276800
2013  19.259569  12.926394  25.205186
2014  19.464966  13.266000  25.138391
2015  19.581111  13.448540  25.511547
2016  19.642927  13.267694  25.497076

In [326]:


px.line(
    stats_temperatura_años.droplevel(0, axis=1).reset_index(), 
    x="Year", 
    y=["mean", "max", "min"],
)

In [329]:

px.line(
    stats_temperatura_años.droplevel(0, axis=1).reset_index(), 
    x="Year", 
    y="mean"
)

In [330]:

px.line(
    stats_temperatura_años.droplevel(0, axis=1).reset_index(), 
    x="Year", 
    y="max"
)

In [331]:

px.line(
    stats_temperatura_años.droplevel(0, axis=1).reset_index(), 
    x="Year", 
    y="min"
)