# Clase 7: Concatenación, Combinación de Múltiples Fuentes de Datos y Pivoteo

**MDS7202: Laboratorio de Programación Científica para Ciencia de Datos**

## Objetivos de la Clase

- Comprender como fusionar fuentes de datos usando `concatenaciones` y `merge`.
- Profundizar uso de set_index y reset_index para combinar fuentes.
- Reorganizar los datos usando `pivot`, `melt` y `transpose`.
- Profundizar el uso de los multi-índices de pandas.

## Datasets de Hoy

### Índices para una Vida Mejor

Nuevamente, seguiremos usando los datos de índices para una Vida Mejor de la OECD:


<img src="https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/oecd.png" alt="OECD Better life index"/>


http://www.oecdbetterlifeindex.org/

https://stats.oecd.org/index.aspx?DataSetCode=BLI

Son 11 temas considerados como esenciales para el bienestar de la población. Cada crierio contiene uno o mas indicadores

| Tema | Indicador (Inglés) | Indicador (Español) | Unidad | Descripción |
|---|---|---|---|---|
| Vivienda 🏠 | Dwellings without basic facilities | Vivienda con Instalaciones Básicas | Porcentaje | Porcentaje de personas con inodoros de agua corriente dentro del hogar, año disponible más reciente |
|  | Housing expenditure | Gastos en Vivienda | Porcentaje | Proporción de costos de vivienda en el ingreso neto ajustado de las familias, año disponible más reciente |
|  | Rooms per person | Habitaciones por Persona | Ratio | Número promedio de habitaciones compartidas por persona en una vivienda, año disponible más reciente |
| Ingresos 💰 | Household net adjusted disposable income | Ingreso Familiar Disponible | US Dollar | Cantidad promedio de dinero que una familia gana al año, después de impuestos, año disponible más reciente |
|  | Household net wealth | Patrimonio Neto Familiar | US Dollar | Valor total promedio de los activos financieros de una familia (ahorros, acciones) menos sus pasivos (créditos), año disponible más reciente |
| Empleo ⚙️ | Labour market insecurity | Seguridad en el Empleo | Porcentaje | Pérdida esperada de ingresos cuando alguien queda desempleado, año disponible más reciente |
|  | Employment rate | Tasa de Empleo | Porcentaje | Porcentaje de personas, de 15 a 64 años de edad, actualmente con empleo remunerado, año disponible más reciente |
|  | Long-term unemployment rate | Tasa de Empleo a Largo Plazo | Porcentaje | Porcentaje de personas, de 15 a 64 años de edad, que no trabajan pero que han buscado empleo activamente durante más de un año, año disponible más reciente |
|  | Personal earnings | Ingresos Personales | US Dollar | Ingresos anuales promedio por empleado de tiempo completo, año disponible más reciente |
| Comunidad 🧑‍🤝‍🧑   | Quality of support network  | Calidad del Apoyo Social | Porcentaje | Porcentaje de personas con amigos o parientes en quienes confiar en caso de necesidad |
| Educación 📚 | Educational attainment | Nivel de Educación | Porcentaje | Porcentaje de personas, de 25 a 64 años de edad, graduadas por lo menos de educación media superior, año disponible más reciente |
|  | Student skills | Competencias de estudiantes en matemáticas, lectura y ciencias | Puntaje promedio | Desempeño promedio de estudiantes de 15 años de edad, según PISA (Programa para la Evaluación Internacional de Estudiantes) |
|  | Years in education  | Nivel de educación | Años | Duración promedio de la educación formal en la que un niño de cinco años de edad puede esperar matricularse durante su vida |
| Medio Ambiente 🌳 | Air pollution | Contaminación del Aire | Microgramos por metro cúbico | Concentración promedio de partículas (PM2.5) en ciudades con poblaciones mayores de 100,000 personas, medida en microgramos por metro cúbico, año disponible más reciente |
|  | Water quality | Calidad del Agua | Porcentaje | Porcentaje de personas que informan estar satisfechas con la calidad del agua local |
| Compromiso Cívico 🗳️  | Stakeholder engagement for developing regulations | Participación de los interesados en la elaboración de regulaciones | Puntaje promedio | Nivel de transparencia gubernamental al preparar las regulaciones, año disponible más reciente |
|  | Voter turnout | Participación electoral | Porcentaje | Porcentaje de votantes registrados que votaron durante las elecciones recientes, año disponible más reciente |
| Salud ⚕️ | Life expectancy | Esperanza de vida | Años | Número promedio de años que una persona puede esperar vivir, año disponible más reciente |
|  | Self-reported health | Salud según informan las personas | Porcentaje | Porcentaje de personas que informan que su salud es «buena o muy buena», año disponible más reciente |
| Satisfacción ✨ | Life satisfaction | Satisfacción ante la vida | Puntaje promedio | Autoevaluación promedio de satisfacción ante la vida, en una escala de 0 a 10 |
| Seguridad 🌃 | Feeling safe walking alone at night | Sentimiento de seguridad al caminar solos por la noche | Porcentaje | Porcentaje de personas que reportan sentirse seguras al caminar solas por la noche  |
|  | Homicide rate | Tasa de homicidios | Ratio | Número promedio de homicidios reportados por 100,000 personas, año disponible más reciente |
| Balance Vida Trabajo 🧘 | Employees working very long hours | Empleados que trabajan muchas horas | Porcentaje | Porcentaje de empleados que trabajan más de cincuenta horas a la semana en promedio, año disponible más reciente |
|  | Time devoted to leisure and personal care | Tiempo destinado al ocio y el cuidado personal | Horas | Número promedio de minutos al día dedicados al ocio y el cuidado personal, incluidos el sueño y la alimentación |

In [10]:
import pandas as pd

bli_df = pd.read_excel("../../recursos/2023-02/pandas-2/dataset.xlsx", header=1, index_col=0)

bli_df.head()

,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,Quality of support network,...,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health,Life satisfaction,Feeling safe walking alone at night,Homicide rate,Employees working very long hours,Time devoted to leisure and personal care
Country,,,,,,,,,,,,,,,,,,,,,
Australia,NaN,20.0,NaN,32759.0,427064.0,5.4,73,1.31,49126.0,95,...,93,2.7,91,82.5,85.0,7.3,63.5,1.1,13.04,14.35
Austria,0.9,21.0,1.6,33541.0,308325.0,3.5,72,1.84,50349.0,92,...,92,1.3,80,81.7,70.0,7.1,80.6,0.5,6.66,14.55
Belgium,1.9,21.0,2.2,30364.0,386006.0,3.7,63,3.54,49675.0,91,...,84,2.0,89,81.5,74.0,6.9,70.1,1.0,4.75,15.70
Canada,0.2,22.0,2.6,30854.0,423849.0,6.0,73,0.77,47622.0,93,...,91,2.9,68,81.9,88.0,7.4,82.2,1.3,3.69,14.56
Chile,9.4,18.0,1.2,NaN,100967.0,8.7,63,NaN,25879.0,85,...,71,1.3,47,79.9,57.0,6.5,47.9,4.2,9.72,NaN

In [14]:
bli_df.shape

(41, 24)

### Dataset de Temperaturas Globales

![wbg_climate](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/wbg_climate.png)


https://climateknowledgeportal.worldbank.org/download-data

In [15]:
temp_df = pd.read_csv(
    "../../recursos/2023-02/pandas-2/temperature.csv")
temp_df.head(20)

    Temperature  Year Month      Country ISO3
0      -0.03110  1991   Jan  Afghanistan  AFG
1       1.43654  1991   Feb  Afghanistan  AFG
2       6.88685  1991   Mar  Afghanistan  AFG
3      12.93970  1991   Apr  Afghanistan  AFG
4      17.07550  1991   May  Afghanistan  AFG
5      23.07770  1991   Jun  Afghanistan  AFG
6      25.57100  1991   Jul  Afghanistan  AFG
7      23.96730  1991   Aug  Afghanistan  AFG
8      19.38000  1991   Sep  Afghanistan  AFG
9      12.87790  1991   Oct  Afghanistan  AFG
10      7.31675  1991   Nov  Afghanistan  AFG
11      4.23571  1991   Dec  Afghanistan  AFG
12      0.74637  1992   Jan  Afghanistan  AFG
13      2.46018  1992   Feb  Afghanistan  AFG
14      5.71341  1992   Mar  Afghanistan  AFG
15     11.69260  1992   Apr  Afghanistan  AFG
16     16.11080  1992   May  Afghanistan  AFG
17     22.88750  1992   Jun  Afghanistan  AFG
18     24.70680  1992   Jul  Afghanistan  AFG
19     22.86330  1992   Aug  Afghanistan  AFG

In [16]:
temp_df.shape

(59904, 5)

----

## 1.- Concatenación


> Según Wikipedia: *Es la operación por la cual dos caracteres se unen para formar una cadena de caracteres (o string). También se pueden concatenar dos cadenas de caracteres o un carácter con una cadena para formar una cadena de mayor tamaño*. Ejemplo:

In [17]:
a = "Hola "

b = "a todos 🤗"


a + b

'Hola a todos 🤗'

La idea general de concatenar es unir 2 o más `Dataframes` por filas o columnas.

<div align='center'>
    <img src='https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/concat.png' width=900/>
</div>


Todas las operaciones se hacen a través de la operación sobre los índices de los `DataFrames`.

### 1.1 Caso 1: Concatenar Filas

En el caso de contactenar por filas `(axis=0)`, los `DataFrames` se unen al final a través de los índices.

<div align='center'>
    <img src='https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/merging_concat_basic.png' width=500/>
</div>

In [18]:
bli_df.head(5)

,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,Quality of support network,...,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health,Life satisfaction,Feeling safe walking alone at night,Homicide rate,Employees working very long hours,Time devoted to leisure and personal care
Country,,,,,,,,,,,,,,,,,,,,,
Australia,NaN,20.0,NaN,32759.0,427064.0,5.4,73,1.31,49126.0,95,...,93,2.7,91,82.5,85.0,7.3,63.5,1.1,13.04,14.35
Austria,0.9,21.0,1.6,33541.0,308325.0,3.5,72,1.84,50349.0,92,...,92,1.3,80,81.7,70.0,7.1,80.6,0.5,6.66,14.55
Belgium,1.9,21.0,2.2,30364.0,386006.0,3.7,63,3.54,49675.0,91,...,84,2.0,89,81.5,74.0,6.9,70.1,1.0,4.75,15.70
Canada,0.2,22.0,2.6,30854.0,423849.0,6.0,73,0.77,47622.0,93,...,91,2.9,68,81.9,88.0,7.4,82.2,1.3,3.69,14.56
Chile,9.4,18.0,1.2,NaN,100967.0,8.7,63,NaN,25879.0,85,...,71,1.3,47,79.9,57.0,6.5,47.9,4.2,9.72,NaN

In [19]:
bli_df = bli_df.reset_index()

In [20]:
bli_df

,Country,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,...,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health,Life satisfaction,Feeling safe walking alone at night,Homicide rate,Employees working very long hours,Time devoted to leisure and personal care
0,Australia,NaN,20.0,NaN,32759.0,427064.0,5.4,73,1.31,49126.0,...,93,2.7,91,82.5,85.0,7.3,63.5,1.1,13.04,14.35
1,Austria,0.9,21.0,1.6,33541.0,308325.0,3.5,72,1.84,50349.0,...,92,1.3,80,81.7,70.0,7.1,80.6,0.5,6.66,14.55
2,Belgium,1.9,21.0,2.2,30364.0,386006.0,3.7,63,3.54,49675.0,...,84,2.0,89,81.5,74.0,6.9,70.1,1.0,4.75,15.70
3,Canada,0.2,22.0,2.6,30854.0,423849.0,6.0,73,0.77,47622.0,...,91,2.9,68,81.9,88.0,7.4,82.2,1.3,3.69,14.56
4,Chile,9.4,18.0,1.2,NaN,100967.0,8.7,63,NaN,25879.0,...,71,1.3,47,79.9,57.0,6.5,47.9,4.2,9.72,NaN
5,Colombia,23.9,17.0,1.2,NaN,NaN,NaN,67,0.79,NaN,...,75,1.4,53,76.2,NaN,6.3,44.4,24.5,26.56,NaN
6,Czech Republic,0.7,24.0,1.4,21453.0,NaN,3.1,74,1.04,25372.0,...,87,1.6,61,79.1,60.0,6.7,72.3,0.5,5.65,NaN
7,Denmark,0.5,23.0,1.9,29606.0,118637.0,4.2,74,1.31,51466.0,...,95,2.0,86,80.9,71.0,7.6,83.5,0.6,2.34,15.87
8,Estonia,7.0,17.0,1.6,19697.0,159373.0,3.8,74,1.92,24336.0,...,84,2.7,64,77.8,53.0,5.7,69.0,3.1,2.42,14.90
9,Finland,0.5,23.0,1.9,29943.0,200827.0,3.9,70,2.13,42964.0,...,95,2.2,67,81.5,70.0,7.6,85.1,1.3,3.81,15.17
10,France,0.5,21.0,1.8,31304.0,280653.0,7.6,65,4.00,43755.0,...,81,2.1,75,82.4,66.0,6.5,70.5,0.5,7.67,16.36
11,Germany,0.2,20.0,1.8,34294.0,259667.0,2.7,75,1.57,47585.0,...,91,1.8,76,81.1,65.0,7.0,72.5,0.5,4.26,15.62
12,Greece,0.5,23.0,1.2,17700.0,150134.0,29.8,53,15.65,26064.0,...,69,1.8,64,81.5,74.0,5.4,60.0,0.8,6.42,NaN
13,Hungary,4.7,19.0,1.2,NaN,104458.0,4.7,68,1.72,22576.0,...,77,1.2,70,76.2,60.0,5.6,56.3,1.0,3.03,NaN
14,Iceland,0.0,24.0,1.6,NaN,NaN,0.7,86,0.26,61787.0,...,99,2.1,79,82.3,76.0,7.5,86.0,0.5,15.06,NaN
15,Ireland,1.0,20.0,2.1,25310.0,217130.0,7.8,67,3.23,47653.0,...,85,1.3,65,81.8,83.0,7.0,75.9,0.7,5.25,NaN
16,Israel,NaN,NaN,1.2,NaN,NaN,4.2,69,0.49,35067.0,...,67,2.5,72,82.5,84.0,7.2,69.8,1.8,15.45,NaN
17,Italy,0.7,23.0,1.4,26588.0,279889.0,12.3,58,6.59,36658.0,...,71,2.5,73,83.3,71.0,6.0,58.4,0.6,4.11,16.47
18,Japan,6.4,22.0,1.9,29798.0,305878.0,1.4,75,1.03,40863.0,...,87,1.4,53,84.1,36.0,5.9,72.5,0.2,NaN,NaN
19,Korea,2.5,15.0,1.5,21882.0,285980.0,2.6,67,0.05,35191.0,...,76,2.9,77,82.4,33.0,5.9,66.6,1.0,NaN,14.70
20,Latvia,13.9,23.0,1.2,16275.0,70160.0,9.6,70,3.35,23683.0,...,79,2.2,59,74.7,47.0,5.9,62.4,4.8,1.27,13.83
21,Lithuania,13.6,19.0,1.5,21660.0,NaN,NaN,70,2.69,24287.0,...,81,2.4,51,74.8,43.0,5.9,55.9,3.4,0.54,NaN
22,Luxembourg,0.5,21.0,1.9,39264.0,769053.0,1.7,66,2.35,63062.0,...,84,1.7,91,82.8,69.0,6.9,75.8,0.6,3.82,NaN
23,Mexico,25.5,20.0,1.0,NaN,NaN,5.5,61,0.07,15314.0,...,68,3.2,63,75.4,66.0,6.5,41.8,18.1,28.70,NaN
24,Netherlands,0.1,19.0,1.9,29333.0,157824.0,4.8,76,1.97,52877.0,...,93,2.6,82,81.6,76.0,7.4,82.0,0.6,0.42,NaN
25,New Zealand,NaN,26.0,2.4,NaN,388514.0,4.7,77,0.74,40043.0,...,89,2.5,80,81.7,88.0,7.3,65.7,1.3,15.11,14.87
26,Norway,0.0,17.0,2.1,35725.0,228936.0,NaN,74,0.66,51212.0,...,98,2.2,78,82.5,77.0,7.6,90.1,0.4,2.93,15.56
27,Poland,3.0,22.0,1.1,19814.0,210991.0,5.7,66,1.52,27046.0,...,82,2.6,55,78.0,58.0,6.1,67.3,0.7,5.95,14.42
28,Portugal,1.0,21.0,1.7,21203.0,232666.0,10.0,68,4.43,25367.0,...,86,1.5,56,81.2,48.0,5.4,73.4,1.0,8.27,NaN
29,Slovak Republic,1.2,23.0,1.1,20474.0,119696.0,9.9,66,4.78,24328.0,...,85,3.0,60,77.3,66.0,6.2,63.5,0.8,4.14,NaN
30,Slovenia,0.4,18.0,1.5,20820.0,203044.0,5.8,69,3.17,34933.0,...,90,2.5,53,81.3,64.0,5.9,86.1,0.6,4.39,14.75
31,Spain,0.1,21.0,1.9,23999.0,373548.0,23.1,62,7.66,38507.0,...,72,1.8,70,83.4,72.0,6.3,82.1,0.6,4.01,15.93
32,Sweden,0.0,19.0,1.7,31287.0,NaN,3.2,77,1.12,42393.0,...,96,2.0,86,82.4,75.0,7.3,75.6,0.9,1.07,15.18
33,Switzerland,0.1,22.0,1.9,37466.0,NaN,NaN,80,1.82,62283.0,...,95,2.3,49,83.7,78.0,7.5,85.3,0.6,0.37,NaN
34,Turkey,8.0,20.0,1.0,NaN,NaN,12.5,52,2.39,NaN,...,65,1.5,86,78.0,69.0,5.5,59.8,1.4,32.64,14.79
35,United Kingdom,0.3,26.0,1.9,28715.0,548392.0,4.5,75,1.13,43732.0,...,84,3.1,69,81.2,69.0,6.8,77.7,0.2,12.15,14.92
36,United States,0.1,19.0,2.4,45284.0,632100.0,7.7,70,0.66,60558.0,...,83,3.1,65,78.6,88.0,6.9,73.9,5.5,11.09,14.44
37,OECD - Total,4.4,20.0,1.8,33604.0,408376.0,7.0,68,1.78,43241.0,...,81,2.4,68,80.2,69.0,6.5,68.4,3.7,11.01,14.98
38,Brazil,6.7,NaN,NaN,NaN,NaN,NaN,61,NaN,NaN,...,73,2.2,79,74.8,NaN,6.4,35.6,26.7,7.13,NaN
39,Russia,14.8,18.0,0.9,NaN,NaN,NaN,70,1.59,NaN,...,55,NaN,68,71.8,43.0,5.8,52.8,9.6,0.14,NaN
40,South Africa,37.0,18.0,NaN,NaN,NaN,NaN,43,16.46,NaN,...,67,NaN,73,57.5,NaN,4.7,36.1,13.7,18.12,14.92

In [21]:
sudamerica_df = bli_df.loc[
    bli_df["Country"].isin(
        [
            "Chile",
            "Brazil",
            "Colombia",
        ]
    ),
    :,
]

sudamerica_df

,Country,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,...,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health,Life satisfaction,Feeling safe walking alone at night,Homicide rate,Employees working very long hours,Time devoted to leisure and personal care
4,Chile,9.4,18.0,1.2,NaN,100967.0,8.7,63,NaN,25879.0,...,71,1.3,47,79.9,57.0,6.5,47.9,4.2,9.72,NaN
5,Colombia,23.9,17.0,1.2,NaN,NaN,NaN,67,0.79,NaN,...,75,1.4,53,76.2,NaN,6.3,44.4,24.5,26.56,NaN
38,Brazil,6.7,NaN,NaN,NaN,NaN,NaN,61,NaN,NaN,...,73,2.2,79,74.8,NaN,6.4,35.6,26.7,7.13,NaN

In [22]:
norteamerica_df = bli_df[
    bli_df["Country"].isin(
        [
            "Canada",
            "United States",
            "Mexico",
        ]
    )
]

norteamerica_df

,Country,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,...,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health,Life satisfaction,Feeling safe walking alone at night,Homicide rate,Employees working very long hours,Time devoted to leisure and personal care
3,Canada,0.2,22.0,2.6,30854.0,423849.0,6.0,73,0.77,47622.0,...,91,2.9,68,81.9,88.0,7.4,82.2,1.3,3.69,14.56
23,Mexico,25.5,20.0,1.0,NaN,NaN,5.5,61,0.07,15314.0,...,68,3.2,63,75.4,66.0,6.5,41.8,18.1,28.70,NaN
36,United States,0.1,19.0,2.4,45284.0,632100.0,7.7,70,0.66,60558.0,...,83,3.1,65,78.6,88.0,6.9,73.9,5.5,11.09,14.44

In [23]:
oceania_df = bli_df.loc[bli_df["Country"].isin(["New Zealand", "Australia"]), :]
oceania_df

,Country,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,...,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health,Life satisfaction,Feeling safe walking alone at night,Homicide rate,Employees working very long hours,Time devoted to leisure and personal care
0,Australia,NaN,20.0,NaN,32759.0,427064.0,5.4,73,1.31,49126.0,...,93,2.7,91,82.5,85.0,7.3,63.5,1.1,13.04,14.35
25,New Zealand,NaN,26.0,2.4,NaN,388514.0,4.7,77,0.74,40043.0,...,89,2.5,80,81.7,88.0,7.3,65.7,1.3,15.11,14.87

Para ejecutar la concatenación, usamos el método `pd.concat` sobre un arreglo con los `DataFrames` por concatenar.

In [24]:
df_concatenado_filas = pd.concat(
    [
        sudamerica_df, 
        norteamerica_df, 
        oceania_df
    ]
    , axis=0)
df_concatenado_filas

,Country,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,...,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health,Life satisfaction,Feeling safe walking alone at night,Homicide rate,Employees working very long hours,Time devoted to leisure and personal care
4,Chile,9.4,18.0,1.2,NaN,100967.0,8.7,63,NaN,25879.0,...,71,1.3,47,79.9,57.0,6.5,47.9,4.2,9.72,NaN
5,Colombia,23.9,17.0,1.2,NaN,NaN,NaN,67,0.79,NaN,...,75,1.4,53,76.2,NaN,6.3,44.4,24.5,26.56,NaN
38,Brazil,6.7,NaN,NaN,NaN,NaN,NaN,61,NaN,NaN,...,73,2.2,79,74.8,NaN,6.4,35.6,26.7,7.13,NaN
3,Canada,0.2,22.0,2.6,30854.0,423849.0,6.0,73,0.77,47622.0,...,91,2.9,68,81.9,88.0,7.4,82.2,1.3,3.69,14.56
23,Mexico,25.5,20.0,1.0,NaN,NaN,5.5,61,0.07,15314.0,...,68,3.2,63,75.4,66.0,6.5,41.8,18.1,28.70,NaN
36,United States,0.1,19.0,2.4,45284.0,632100.0,7.7,70,0.66,60558.0,...,83,3.1,65,78.6,88.0,6.9,73.9,5.5,11.09,14.44
0,Australia,NaN,20.0,NaN,32759.0,427064.0,5.4,73,1.31,49126.0,...,93,2.7,91,82.5,85.0,7.3,63.5,1.1,13.04,14.35
25,New Zealand,NaN,26.0,2.4,NaN,388514.0,4.7,77,0.74,40043.0,...,89,2.5,80,81.7,88.0,7.3,65.7,1.3,15.11,14.87

### 1.2 Caso 2: Concatenar Columnas

En este caso, los `DataFrames` se unen por los índices y las columnas.


<div align='center'>
    <img src='https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/merging_concat_mixed_ndim.png' width=700/>
</div>

In [25]:
env_df = bli_df.loc[:, ["Country", "Air pollution", "Water quality"]]
env_df.head()

     Country  Air pollution  Water quality
0  Australia              5             93
1    Austria             16             92
2    Belgium             15             84
3     Canada              7             91
4      Chile             16             71

In [26]:
health_df = bli_df.loc[
    :, [
        "Country", 
        "Self-reported health", 
        "Life expectancy", 
        "Life satisfaction",
    ]
]

health_df.head()

     Country  Self-reported health  Life expectancy  Life satisfaction
0  Australia                  85.0             82.5                7.3
1    Austria                  70.0             81.7                7.1
2    Belgium                  74.0             81.5                6.9
3     Canada                  88.0             81.9                7.4
4      Chile                  57.0             79.9                6.5

In [27]:
env_heatlh_df = pd.concat(
    [env_df, health_df],
    axis=1
)

env_heatlh_df.head()

,Country,Air pollution,Water quality,Country,Self-reported health,Life expectancy,Life satisfaction
0,Australia,5,93,Australia,85.0,82.5,7.3
1,Austria,16,92,Austria,70.0,81.7,7.1
2,Belgium,15,84,Belgium,74.0,81.5,6.9
3,Canada,7,91,Canada,88.0,81.9,7.4
4,Chile,16,71,Chile,57.0,79.9,6.5

In [28]:
env_heatlh_df.columns

Index(['Country', 'Air pollution', 'Water quality', 'Country',
       'Self-reported health', 'Life expectancy', 'Life satisfaction'],
      dtype='str')

In [29]:
env_heatlh_df.loc[:, "Country"]

            Country          Country
0         Australia        Australia
1           Austria          Austria
2           Belgium          Belgium
3            Canada           Canada
4             Chile            Chile
5          Colombia         Colombia
6    Czech Republic   Czech Republic
7           Denmark          Denmark
8           Estonia          Estonia
9           Finland          Finland
10           France           France
11          Germany          Germany
12           Greece           Greece
13          Hungary          Hungary
14          Iceland          Iceland
15          Ireland          Ireland
16           Israel           Israel
17            Italy            Italy
18            Japan            Japan
19            Korea            Korea
20           Latvia           Latvia
21        Lithuania        Lithuania
22       Luxembourg       Luxembourg
23           Mexico           Mexico
24      Netherlands      Netherlands
25      New Zealand      New Zealand
26           Norway           Norway
27           Poland           Poland
28         Portugal         Portugal
29  Slovak Republic  Slovak Republic
30         Slovenia         Slovenia
31            Spain            Spain
32           Sweden           Sweden
33      Switzerland      Switzerland
34           Turkey           Turkey
35   United Kingdom   United Kingdom
36    United States    United States
37     OECD - Total     OECD - Total
38           Brazil           Brazil
39           Russia           Russia
40     South Africa     South Africa

Nota: La unión sigue siendo por filas. Por ende, una columna repetida aparecerá dos veces en el `DataFrame` resultante, como en el caso anterior con `Country`

> **Nota**: Para facilitar la práctica, solo dejaremos una columna `Country`

In [30]:
env_heatlh_df.columns

Index(['Country', 'Air pollution', 'Water quality', 'Country',
       'Self-reported health', 'Life expectancy', 'Life satisfaction'],
      dtype='str')

In [31]:
~env_heatlh_df.columns.duplicated()

array([ True,  True,  True, False,  True,  True,  True])

In [46]:
env_heatlh_df = env_heatlh_df.loc[:, ~env_heatlh_df.columns.duplicated()]
env_heatlh_df.head()

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction
0,Australia,5,93,85.0,82.5,7.3
1,Austria,16,92,70.0,81.7,7.1
2,Belgium,15,84,74.0,81.5,6.9
3,Canada,7,91,88.0,81.9,7.4
4,Chile,16,71,57.0,79.9,6.5

### 1.3 Un `DataFrame` tiene menos datos que el otro

En este caso, rellena los valores de las filas sin valor con `np.nan`.

<div align='center'>
    <img src='https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/merging_concat_axis1.png' width=800/>
</div>

In [47]:
env_df_reducido = env_df[0:7]
env_df_reducido

          Country  Air pollution  Water quality
0       Australia              5             93
1         Austria             16             92
2         Belgium             15             84
3          Canada              7             91
4           Chile             16             71
5        Colombia             10             75
6  Czech Republic             20             87

In [48]:
health_df

            Country  Self-reported health  Life expectancy  Life satisfaction
0         Australia                  85.0             82.5                7.3
1           Austria                  70.0             81.7                7.1
2           Belgium                  74.0             81.5                6.9
3            Canada                  88.0             81.9                7.4
4             Chile                  57.0             79.9                6.5
5          Colombia                   NaN             76.2                6.3
6    Czech Republic                  60.0             79.1                6.7
7           Denmark                  71.0             80.9                7.6
8           Estonia                  53.0             77.8                5.7
9           Finland                  70.0             81.5                7.6
10           France                  66.0             82.4                6.5
11          Germany                  65.0             81.1                7.0
12           Greece                  74.0             81.5                5.4
13          Hungary                  60.0             76.2                5.6
14          Iceland                  76.0             82.3                7.5
15          Ireland                  83.0             81.8                7.0
16           Israel                  84.0             82.5                7.2
17            Italy                  71.0             83.3                6.0
18            Japan                  36.0             84.1                5.9
19            Korea                  33.0             82.4                5.9
20           Latvia                  47.0             74.7                5.9
21        Lithuania                  43.0             74.8                5.9
22       Luxembourg                  69.0             82.8                6.9
23           Mexico                  66.0             75.4                6.5
24      Netherlands                  76.0             81.6                7.4
25      New Zealand                  88.0             81.7                7.3
26           Norway                  77.0             82.5                7.6
27           Poland                  58.0             78.0                6.1
28         Portugal                  48.0             81.2                5.4
29  Slovak Republic                  66.0             77.3                6.2
30         Slovenia                  64.0             81.3                5.9
31            Spain                  72.0             83.4                6.3
32           Sweden                  75.0             82.4                7.3
33      Switzerland                  78.0             83.7                7.5
34           Turkey                  69.0             78.0                5.5
35   United Kingdom                  69.0             81.2                6.8
36    United States                  88.0             78.6                6.9
37     OECD - Total                  69.0             80.2                6.5
38           Brazil                   NaN             74.8                6.4
39           Russia                  43.0             71.8                5.8
40     South Africa                   NaN             57.5                4.7

In [49]:
pd.concat(
    [
        env_df_reducido, 
        health_df
    ], axis=1).head(15)

,Country,Air pollution,Water quality,Country,Self-reported health,Life expectancy,Life satisfaction
0,Australia,5.0,93.0,Australia,85.0,82.5,7.3
1,Austria,16.0,92.0,Austria,70.0,81.7,7.1
2,Belgium,15.0,84.0,Belgium,74.0,81.5,6.9
3,Canada,7.0,91.0,Canada,88.0,81.9,7.4
4,Chile,16.0,71.0,Chile,57.0,79.9,6.5
5,Colombia,10.0,75.0,Colombia,NaN,76.2,6.3
6,Czech Republic,20.0,87.0,Czech Republic,60.0,79.1,6.7
7,NaN,NaN,NaN,Denmark,71.0,80.9,7.6
8,NaN,NaN,NaN,Estonia,53.0,77.8,5.7
9,NaN,NaN,NaN,Finland,70.0,81.5,7.6
10,NaN,NaN,NaN,France,66.0,82.4,6.5
11,NaN,NaN,NaN,Germany,65.0,81.1,7.0
12,NaN,NaN,NaN,Greece,74.0,81.5,5.4
13,NaN,NaN,NaN,Hungary,60.0,76.2,5.6
14,NaN,NaN,NaN,Iceland,76.0,82.3,7.5

In [53]:
env_df_reducido_2 = env_df[10:20].reset_index()

pd.concat(
    [
        env_df_reducido_2, 
        health_df
    ], axis=1).head(15)

,index,Country,Air pollution,Water quality,Country,Self-reported health,Life expectancy,Life satisfaction
0,10.0,France,13.0,81.0,Australia,85.0,82.5,7.3
1,11.0,Germany,14.0,91.0,Austria,70.0,81.7,7.1
2,12.0,Greece,18.0,69.0,Belgium,74.0,81.5,6.9
3,13.0,Hungary,19.0,77.0,Canada,88.0,81.9,7.4
4,14.0,Iceland,3.0,99.0,Chile,57.0,79.9,6.5
5,15.0,Ireland,7.0,85.0,Colombia,NaN,76.2,6.3
6,16.0,Israel,21.0,67.0,Czech Republic,60.0,79.1,6.7
7,17.0,Italy,18.0,71.0,Denmark,71.0,80.9,7.6
8,18.0,Japan,14.0,87.0,Estonia,53.0,77.8,5.7
9,19.0,Korea,28.0,76.0,Finland,70.0,81.5,7.6
10,NaN,NaN,NaN,NaN,France,66.0,82.4,6.5
11,NaN,NaN,NaN,NaN,Germany,65.0,81.1,7.0
12,NaN,NaN,NaN,NaN,Greece,74.0,81.5,5.4
13,NaN,NaN,NaN,NaN,Hungary,60.0,76.2,5.6
14,NaN,NaN,NaN,NaN,Iceland,76.0,82.3,7.5

### 1.4 Error en parámetro `axis`

In [54]:
# concatenamos correctamente al igual que el ejemplo anterior
pd.concat([
    env_df.head(), 
    health_df.head()
], axis=1)

,Country,Air pollution,Water quality,Country,Self-reported health,Life expectancy,Life satisfaction
0,Australia,5,93,Australia,85.0,82.5,7.3
1,Austria,16,92,Austria,70.0,81.7,7.1
2,Belgium,15,84,Belgium,74.0,81.5,6.9
3,Canada,7,91,Canada,88.0,81.9,7.4
4,Chile,16,71,Chile,57.0,79.9,6.5

> **Pregunta ❓**: ¿Qué sucede si nos equivocamos con el parámetro `axis`?

In [55]:
env_df.head()

     Country  Air pollution  Water quality
0  Australia              5             93
1    Austria             16             92
2    Belgium             15             84
3     Canada              7             91
4      Chile             16             71

In [56]:
health_df.head()

     Country  Self-reported health  Life expectancy  Life satisfaction
0  Australia                  85.0             82.5                7.3
1    Austria                  70.0             81.7                7.1
2    Belgium                  74.0             81.5                6.9
3     Canada                  88.0             81.9                7.4
4      Chile                  57.0             79.9                6.5

In [57]:
pd.concat([env_df.head(), health_df.head()], axis=0)

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction
0,Australia,5.0,93.0,NaN,NaN,NaN
1,Austria,16.0,92.0,NaN,NaN,NaN
2,Belgium,15.0,84.0,NaN,NaN,NaN
3,Canada,7.0,91.0,NaN,NaN,NaN
4,Chile,16.0,71.0,NaN,NaN,NaN
0,Australia,NaN,NaN,85.0,82.5,7.3
1,Austria,NaN,NaN,70.0,81.7,7.1
2,Belgium,NaN,NaN,74.0,81.5,6.9
3,Canada,NaN,NaN,88.0,81.9,7.4
4,Chile,NaN,NaN,57.0,79.9,6.5

Incluso, en el caso que los índices no sean útiles para unir filas, pueden especificar `ignore_index` como `True`.

In [58]:
pd.concat([env_df.head(), health_df.head()], ignore_index=True)

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction
0,Australia,5.0,93.0,NaN,NaN,NaN
1,Austria,16.0,92.0,NaN,NaN,NaN
2,Belgium,15.0,84.0,NaN,NaN,NaN
3,Canada,7.0,91.0,NaN,NaN,NaN
4,Chile,16.0,71.0,NaN,NaN,NaN
5,Australia,NaN,NaN,85.0,82.5,7.3
6,Austria,NaN,NaN,70.0,81.7,7.1
7,Belgium,NaN,NaN,74.0,81.5,6.9
8,Canada,NaN,NaN,88.0,81.9,7.4
9,Chile,NaN,NaN,57.0,79.9,6.5

---

## 2.- Agregaciones:  Breve repaso y preparación de nuevos datos

Recordemos que podemos agregar datos según algún grupo y calcular estadísticas sobre estos.

El proceso consiste en tres pasos: 

1. Separar
2. Aplicar la función.
3. Juntar.

<div align='center'>
    <img src='https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/group_by.png' width=900/>
</div>

In [59]:
temp_df.head(10)

   Temperature  Year Month      Country ISO3
0     -0.03110  1991   Jan  Afghanistan  AFG
1      1.43654  1991   Feb  Afghanistan  AFG
2      6.88685  1991   Mar  Afghanistan  AFG
3     12.93970  1991   Apr  Afghanistan  AFG
4     17.07550  1991   May  Afghanistan  AFG
5     23.07770  1991   Jun  Afghanistan  AFG
6     25.57100  1991   Jul  Afghanistan  AFG
7     23.96730  1991   Aug  Afghanistan  AFG
8     19.38000  1991   Sep  Afghanistan  AFG
9     12.87790  1991   Oct  Afghanistan  AFG

In [60]:
prom = temp_df.groupby("Country").mean(numeric_only=True)
prom = prom.drop(columns=["Year"])
prom = prom.rename(columns={'Temperature': 'promedio'})
prom

                promedio
Country
Afghanistan    13.545609
Albania        12.106435
Algeria        23.439610
Andorra        11.953746
Angola         22.133815
...                  ...
United States   7.617000
Uruguay        17.941855
Uzbekistan     13.158793
Vanuatu        24.123163
Venezuela      25.865055

[192 rows x 1 columns]

In [29]:
std = temp_df.groupby("Country").std(numeric_only=True).drop(columns=["Year"])
std = std.rename(columns={'Temperature': 'std'})
std

                     std
Country
Afghanistan     8.695203
Albania         7.101392
Algeria         7.473115
Andorra         6.014903
Angola          1.710757
...                  ...
United States   9.077944
Uruguay         4.505184
Uzbekistan     10.837303
Vanuatu         1.204321
Venezuela       0.621697

[192 rows x 1 columns]

> **Pregunta ❓**: ¿Cómo podríamos usar concat para juntar los promedios y desviaciones estándar?

In [30]:
df_unido = pd.concat([prom, std], axis=1)
df_unido

                promedio        std
Country
Afghanistan    13.545609   8.695203
Albania        12.106435   7.101392
Algeria        23.439610   7.473115
Andorra        11.953746   6.014903
Angola         22.133815   1.710757
...                  ...        ...
United States   7.617000   9.077944
Uruguay        17.941855   4.505184
Uzbekistan     13.158793  10.837303
Vanuatu        24.123163   1.204321
Venezuela      25.865055   0.621697

[192 rows x 2 columns]

### 2.1 `agg`

Recordemos el método `agg`, el cuál permite agregar datos por grupo usando una o más operaciones:

In [82]:
t_agg_df = temp_df.groupby("Country").agg(
    {"Temperature": ["median", "min", "max"]}
)
t_agg_df

              Temperature
                   median       min      max
Country
Afghanistan     14.227900  -4.17370  26.7011
Albania         11.624400  -0.42090  23.9754
Algeria         23.802400  10.67800  34.6643
Andorra         11.140150   0.84661  23.3238
Angola          22.825000  18.12080  24.7819
...                   ...       ...      ...
United States    7.385775  -6.84690  21.3749
Uruguay         18.048250   8.80987  25.8511
Uzbekistan      13.710350 -12.05100  29.1871
Vanuatu         24.326050  21.51750  26.8351
Venezuela       25.825800  24.28350  27.9478

[192 rows x 3 columns]

Este, como vimos anteriormente, retorna un multi-índice en las columnas:

In [83]:
t_agg_df.columns

MultiIndex([('Temperature', 'median'),
            ('Temperature',    'min'),
            ('Temperature',    'max')],
           )

Haremos un pequeño _fix_ didáctico: eliminaremos los multiíndices de las filas y columnas para dejar listo el dataset para lo que viene.

In [97]:
t_agg_df_norm = t_agg_df.droplevel(0, axis=1).reset_index()
t_agg_df_norm.columns = ["Country", "t_median", "t_min", "t_max"]
t_agg_df_norm

           Country   t_median     t_min    t_max
0      Afghanistan  14.227900  -4.17370  26.7011
1          Albania  11.624400  -0.42090  23.9754
2          Algeria  23.802400  10.67800  34.6643
3          Andorra  11.140150   0.84661  23.3238
4           Angola  22.825000  18.12080  24.7819
..             ...        ...       ...      ...
187  United States   7.385775  -6.84690  21.3749
188        Uruguay  18.048250   8.80987  25.8511
189     Uzbekistan  13.710350 -12.05100  29.1871
190        Vanuatu  24.326050  21.51750  26.8351
191      Venezuela  25.825800  24.28350  27.9478

[192 rows x 4 columns]

In [96]:
env_heatlh_df.head(10)

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction
0,Australia,5,93,85.0,82.5,7.3
1,Austria,16,92,70.0,81.7,7.1
2,Belgium,15,84,74.0,81.5,6.9
3,Canada,7,91,88.0,81.9,7.4
4,Chile,16,71,57.0,79.9,6.5
5,Colombia,10,75,NaN,76.2,6.3
6,Czech Republic,20,87,60.0,79.1,6.7
7,Denmark,9,95,71.0,80.9,7.6
8,Estonia,8,84,53.0,77.8,5.7
9,Finland,6,95,70.0,81.5,7.6

In [98]:
t_agg_df_norm.head(10)

               Country  t_median     t_min    t_max
0          Afghanistan  14.22790  -4.17370  26.7011
1              Albania  11.62440  -0.42090  23.9754
2              Algeria  23.80240  10.67800  34.6643
3              Andorra  11.14015   0.84661  23.3238
4               Angola  22.82500  18.12080  24.7819
5  Antigua and Barbuda  26.32650  23.71270  27.7904
6            Argentina  14.78025   5.24201  22.5712
7              Armenia   8.88245 -12.24700  23.0867
8            Australia  22.74305  13.40350  29.4761
9              Austria   7.01461  -5.73770  19.3133

### DataFrames Desalineados

> **Pregunta ❓**: ¿Qué pasará al combinar el Dataset de *Better Life Index* con el de Temperaturas usando `concat`?

In [87]:
env_heatlh_df

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction
0,Australia,5,93,85.0,82.5,7.3
1,Austria,16,92,70.0,81.7,7.1
2,Belgium,15,84,74.0,81.5,6.9
3,Canada,7,91,88.0,81.9,7.4
4,Chile,16,71,57.0,79.9,6.5
5,Colombia,10,75,NaN,76.2,6.3
6,Czech Republic,20,87,60.0,79.1,6.7
7,Denmark,9,95,71.0,80.9,7.6
8,Estonia,8,84,53.0,77.8,5.7
9,Finland,6,95,70.0,81.5,7.6
10,France,13,81,66.0,82.4,6.5
11,Germany,14,91,65.0,81.1,7.0
12,Greece,18,69,74.0,81.5,5.4
13,Hungary,19,77,60.0,76.2,5.6
14,Iceland,3,99,76.0,82.3,7.5
15,Ireland,7,85,83.0,81.8,7.0
16,Israel,21,67,84.0,82.5,7.2
17,Italy,18,71,71.0,83.3,6.0
18,Japan,14,87,36.0,84.1,5.9
19,Korea,28,76,33.0,82.4,5.9
20,Latvia,11,79,47.0,74.7,5.9
21,Lithuania,14,81,43.0,74.8,5.9
22,Luxembourg,12,84,69.0,82.8,6.9
23,Mexico,16,68,66.0,75.4,6.5
24,Netherlands,14,93,76.0,81.6,7.4
25,New Zealand,5,89,88.0,81.7,7.3
26,Norway,5,98,77.0,82.5,7.6
27,Poland,22,82,58.0,78.0,6.1
28,Portugal,10,86,48.0,81.2,5.4
29,Slovak Republic,21,85,66.0,77.3,6.2
30,Slovenia,16,90,64.0,81.3,5.9
31,Spain,11,72,72.0,83.4,6.3
32,Sweden,6,96,75.0,82.4,7.3
33,Switzerland,15,95,78.0,83.7,7.5
34,Turkey,20,65,69.0,78.0,5.5
35,United Kingdom,11,84,69.0,81.2,6.8
36,United States,10,83,88.0,78.6,6.9
37,OECD - Total,14,81,69.0,80.2,6.5
38,Brazil,10,73,NaN,74.8,6.4
39,Russia,15,55,43.0,71.8,5.8
40,South Africa,22,67,NaN,57.5,4.7

In [99]:
t_agg_df_norm.head(10)

               Country  t_median     t_min    t_max
0          Afghanistan  14.22790  -4.17370  26.7011
1              Albania  11.62440  -0.42090  23.9754
2              Algeria  23.80240  10.67800  34.6643
3              Andorra  11.14015   0.84661  23.3238
4               Angola  22.82500  18.12080  24.7819
5  Antigua and Barbuda  26.32650  23.71270  27.7904
6            Argentina  14.78025   5.24201  22.5712
7              Armenia   8.88245 -12.24700  23.0867
8            Australia  22.74305  13.40350  29.4761
9              Austria   7.01461  -5.73770  19.3133

In [89]:
df_concat = pd.concat([env_heatlh_df, t_agg_df], axis=1)
df_concat

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction,"(Temperature, median)","(Temperature, min)","(Temperature, max)"
0,Australia,5.0,93.0,85.0,82.5,7.3,NaN,NaN,NaN
1,Austria,16.0,92.0,70.0,81.7,7.1,NaN,NaN,NaN
2,Belgium,15.0,84.0,74.0,81.5,6.9,NaN,NaN,NaN
3,Canada,7.0,91.0,88.0,81.9,7.4,NaN,NaN,NaN
4,Chile,16.0,71.0,57.0,79.9,6.5,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
United States,NaN,NaN,NaN,NaN,NaN,NaN,7.385775,-6.84690,21.3749
Uruguay,NaN,NaN,NaN,NaN,NaN,NaN,18.048250,8.80987,25.8511
Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,13.710350,-12.05100,29.1871
Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,24.326050,21.51750,26.8351
Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,25.825800,24.28350,27.9478

Parece que no funcionó muy bien...

---

## 3.- Merge / Combinar usando un identificador común

Es una forma de combinar dos `DataFrames` en la que usamos los valores de columna como identificador comunes para concatenar el resto de los valores:

![Idea del Merge](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/merge.png)


Es equivalente a las sentencias `JOIN` de SQL. Existen varios tipos. `Pandas` implementa 5 a través de la función `pd.merge`.

En los siguientes ejemplos uniremos los datasets de la OECD y de temperatura agregada según los distintos tipos de `Merge`. Será de mucha utilidad pensar los `Merge` como operaciones sobre conjuntos.

In [90]:
# Paises en el primer dataset
bli_df["Country"].unique()

<StringArray>
[      'Australia',         'Austria',         'Belgium',          'Canada',
           'Chile',        'Colombia',  'Czech Republic',         'Denmark',
         'Estonia',         'Finland',          'France',         'Germany',
          'Greece',         'Hungary',         'Iceland',         'Ireland',
          'Israel',           'Italy',           'Japan',           'Korea',
          'Latvia',       'Lithuania',      'Luxembourg',          'Mexico',
     'Netherlands',     'New Zealand',          'Norway',          'Poland',
        'Portugal', 'Slovak Republic',        'Slovenia',           'Spain',
          'Sweden',     'Switzerland',          'Turkey',  'United Kingdom',
   'United States',    'OECD - Total',          'Brazil',          'Russia',
    'South Africa']
Length: 41, dtype: str

In [100]:
t_agg_df_norm

           Country   t_median     t_min    t_max
0      Afghanistan  14.227900  -4.17370  26.7011
1          Albania  11.624400  -0.42090  23.9754
2          Algeria  23.802400  10.67800  34.6643
3          Andorra  11.140150   0.84661  23.3238
4           Angola  22.825000  18.12080  24.7819
..             ...        ...       ...      ...
187  United States   7.385775  -6.84690  21.3749
188        Uruguay  18.048250   8.80987  25.8511
189     Uzbekistan  13.710350 -12.05100  29.1871
190        Vanuatu  24.326050  21.51750  26.8351
191      Venezuela  25.825800  24.28350  27.9478

[192 rows x 4 columns]

In [101]:
# Paises en el segundo dataset
t_agg_df_norm["Country"].unique()

<StringArray>
[         'Afghanistan',              'Albania',              'Algeria',
              'Andorra',               'Angola',  'Antigua and Barbuda',
            'Argentina',              'Armenia',            'Australia',
              'Austria',
 ...
               'Tuvalu',               'Uganda',              'Ukraine',
 'United Arab Emirates',       'United Kingdom',        'United States',
              'Uruguay',           'Uzbekistan',              'Vanuatu',
            'Venezuela']
Length: 192, dtype: str

---

### Inner

Combina los elementos que se encuentren en ambas tablas. Descarta todo el resto

![Inner](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/inner.png)

In [75]:
env_heatlh_df.shape

(41, 6)

In [103]:
t_agg_df_norm.shape

(192, 4)

In [104]:
inner_merged = pd.merge(
    left=env_heatlh_df,
    right=t_agg_df_norm,
    left_on="Country",
    right_on="Country",
    how="inner",
    sort=True,
)
inner_merged

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction,t_median,t_min,t_max
0,Australia,5,93,85.0,82.5,7.3,22.743050,13.40350,29.4761
1,Austria,16,92,70.0,81.7,7.1,7.014610,-5.73770,19.3133
2,Belgium,15,84,74.0,81.5,6.9,10.097550,-1.07770,21.7403
3,Brazil,10,73,NaN,74.8,6.4,25.753850,22.74970,27.3481
4,Canada,7,91,88.0,81.9,7.4,-5.484650,-27.10300,12.9856
5,Chile,16,71,57.0,79.9,6.5,8.488035,2.52941,13.9296
6,Colombia,10,75,NaN,76.2,6.3,24.666800,23.39750,26.6059
7,Denmark,9,95,71.0,80.9,7.6,7.946250,-4.11570,19.9446
8,Estonia,8,84,53.0,77.8,5.7,5.850140,-11.87600,21.1702
9,Finland,6,95,70.0,81.5,7.6,2.080410,-16.19400,18.9200
10,France,13,81,66.0,82.4,6.5,11.211150,0.87966,22.6900
11,Germany,14,91,65.0,81.1,7.0,8.866750,-3.63500,21.5847
12,Greece,18,69,74.0,81.5,5.4,13.763150,2.29013,25.9151
13,Hungary,19,77,60.0,76.2,5.6,11.282150,-4.22460,23.4025
14,Iceland,3,99,76.0,82.3,7.5,1.528785,-5.91990,10.8606
15,Ireland,7,85,83.0,81.8,7.0,9.234125,1.78030,17.2233
16,Israel,21,67,84.0,82.5,7.2,21.144500,8.89964,29.5582
17,Italy,18,71,71.0,83.3,6.0,12.363600,1.62498,24.1030
18,Japan,14,87,36.0,84.1,5.9,11.938550,-1.90790,25.5125
19,Latvia,11,79,47.0,74.7,5.9,6.685985,-11.13700,21.1299
20,Lithuania,14,81,43.0,74.8,5.9,7.408915,-10.54900,21.2986
21,Luxembourg,12,84,69.0,82.8,6.9,9.547560,-2.42400,21.9099
22,Mexico,16,68,66.0,75.4,6.5,21.802400,14.03340,26.7604
23,Netherlands,14,93,76.0,81.6,7.4,9.882095,-1.02540,21.2702
24,New Zealand,5,89,88.0,81.7,7.3,10.015220,3.49537,17.3598
25,Norway,5,98,77.0,82.5,7.6,0.822290,-11.99600,14.9049
26,Poland,22,82,58.0,78.0,6.1,8.589850,-6.82530,21.1785
27,Portugal,10,86,48.0,81.2,5.4,14.765300,7.13467,24.3683
28,Russia,15,55,43.0,71.8,5.8,-4.637850,-29.64300,16.1930
29,Slovenia,16,90,64.0,81.3,5.9,9.515220,-3.21980,21.8982
30,South Africa,22,67,NaN,57.5,4.7,18.911800,9.62273,24.8558
31,Spain,11,72,72.0,83.4,6.3,13.118300,4.26265,24.6145
32,Sweden,6,96,75.0,82.4,7.3,2.216065,-13.00600,17.0625
33,Switzerland,15,95,78.0,83.7,7.5,6.255735,-5.33230,18.6714
34,Turkey,20,65,69.0,78.0,5.5,12.017600,-3.39930,24.8286
35,United Kingdom,11,84,69.0,81.2,6.8,8.664480,0.10307,17.1651
36,United States,10,83,88.0,78.6,6.9,7.385775,-6.84690,21.3749

In [105]:
inner_merged.shape

(37, 9)

### Left Merge

![Right Merge](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/left.png)

Conserva solo los elementos que se hayan combinado correctamente provenientes dataset `left`.

In [107]:
left_merged = pd.merge(
    left=env_heatlh_df,
    right=t_agg_df_norm,
    on="Country",
    how="left",
    sort=True,
)
left_merged

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction,t_median,t_min,t_max
0,Australia,5,93,85.0,82.5,7.3,22.743050,13.40350,29.4761
1,Austria,16,92,70.0,81.7,7.1,7.014610,-5.73770,19.3133
2,Belgium,15,84,74.0,81.5,6.9,10.097550,-1.07770,21.7403
3,Brazil,10,73,NaN,74.8,6.4,25.753850,22.74970,27.3481
4,Canada,7,91,88.0,81.9,7.4,-5.484650,-27.10300,12.9856
5,Chile,16,71,57.0,79.9,6.5,8.488035,2.52941,13.9296
6,Colombia,10,75,NaN,76.2,6.3,24.666800,23.39750,26.6059
7,Czech Republic,20,87,60.0,79.1,6.7,NaN,NaN,NaN
8,Denmark,9,95,71.0,80.9,7.6,7.946250,-4.11570,19.9446
9,Estonia,8,84,53.0,77.8,5.7,5.850140,-11.87600,21.1702
10,Finland,6,95,70.0,81.5,7.6,2.080410,-16.19400,18.9200
11,France,13,81,66.0,82.4,6.5,11.211150,0.87966,22.6900
12,Germany,14,91,65.0,81.1,7.0,8.866750,-3.63500,21.5847
13,Greece,18,69,74.0,81.5,5.4,13.763150,2.29013,25.9151
14,Hungary,19,77,60.0,76.2,5.6,11.282150,-4.22460,23.4025
15,Iceland,3,99,76.0,82.3,7.5,1.528785,-5.91990,10.8606
16,Ireland,7,85,83.0,81.8,7.0,9.234125,1.78030,17.2233
17,Israel,21,67,84.0,82.5,7.2,21.144500,8.89964,29.5582
18,Italy,18,71,71.0,83.3,6.0,12.363600,1.62498,24.1030
19,Japan,14,87,36.0,84.1,5.9,11.938550,-1.90790,25.5125
20,Korea,28,76,33.0,82.4,5.9,NaN,NaN,NaN
21,Latvia,11,79,47.0,74.7,5.9,6.685985,-11.13700,21.1299
22,Lithuania,14,81,43.0,74.8,5.9,7.408915,-10.54900,21.2986
23,Luxembourg,12,84,69.0,82.8,6.9,9.547560,-2.42400,21.9099
24,Mexico,16,68,66.0,75.4,6.5,21.802400,14.03340,26.7604
25,Netherlands,14,93,76.0,81.6,7.4,9.882095,-1.02540,21.2702
26,New Zealand,5,89,88.0,81.7,7.3,10.015220,3.49537,17.3598
27,Norway,5,98,77.0,82.5,7.6,0.822290,-11.99600,14.9049
28,OECD - Total,14,81,69.0,80.2,6.5,NaN,NaN,NaN
29,Poland,22,82,58.0,78.0,6.1,8.589850,-6.82530,21.1785
30,Portugal,10,86,48.0,81.2,5.4,14.765300,7.13467,24.3683
31,Russia,15,55,43.0,71.8,5.8,-4.637850,-29.64300,16.1930
32,Slovak Republic,21,85,66.0,77.3,6.2,NaN,NaN,NaN
33,Slovenia,16,90,64.0,81.3,5.9,9.515220,-3.21980,21.8982
34,South Africa,22,67,NaN,57.5,4.7,18.911800,9.62273,24.8558
35,Spain,11,72,72.0,83.4,6.3,13.118300,4.26265,24.6145
36,Sweden,6,96,75.0,82.4,7.3,2.216065,-13.00600,17.0625
37,Switzerland,15,95,78.0,83.7,7.5,6.255735,-5.33230,18.6714
38,Turkey,20,65,69.0,78.0,5.5,12.017600,-3.39930,24.8286
39,United Kingdom,11,84,69.0,81.2,6.8,8.664480,0.10307,17.1651
40,United States,10,83,88.0,78.6,6.9,7.385775,-6.84690,21.3749

In [109]:
bli_df.shape

(41, 25)

In [108]:
left_merged.shape

(41, 9)

### Right Merge

Conserva solo los elementos que se hayan combinado correctamente provenientes dataset `right`.

![Right Merge](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/right.png)

In [110]:
right_merged = pd.merge(
    left=env_heatlh_df,
    right=t_agg_df_norm,
    on="Country",
    how="right",
    sort=True,
)
right_merged

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction,t_median,t_min,t_max
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,14.227900,-4.17370,26.7011
1,Albania,NaN,NaN,NaN,NaN,NaN,11.624400,-0.42090,23.9754
2,Algeria,NaN,NaN,NaN,NaN,NaN,23.802400,10.67800,34.6643
3,Andorra,NaN,NaN,NaN,NaN,NaN,11.140150,0.84661,23.3238
4,Angola,NaN,NaN,NaN,NaN,NaN,22.825000,18.12080,24.7819
...,...,...,...,...,...,...,...,...,...
187,United States,10.0,83.0,88.0,78.6,6.9,7.385775,-6.84690,21.3749
188,Uruguay,NaN,NaN,NaN,NaN,NaN,18.048250,8.80987,25.8511
189,Uzbekistan,NaN,NaN,NaN,NaN,NaN,13.710350,-12.05100,29.1871
190,Vanuatu,NaN,NaN,NaN,NaN,NaN,24.326050,21.51750,26.8351
191,Venezuela,NaN,NaN,NaN,NaN,NaN,25.825800,24.28350,27.9478

In [113]:
t_agg_df_norm.shape

(192, 4)

In [111]:
right_merged.shape

(192, 9)

### Outer

Combina todos los elementos posibles y conserva todo el resto en filas independientes.

![Outer Join](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/10-Pandas3/outer.png)

In [117]:
outer_merged_df = pd.merge(
    left=env_heatlh_df,
    right=t_agg_df_norm,
    on="Country",
    sort=True,
    how="outer",
)
outer_merged_df

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction,t_median,t_min,t_max
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,14.227900,-4.17370,26.7011
1,Albania,NaN,NaN,NaN,NaN,NaN,11.624400,-0.42090,23.9754
2,Algeria,NaN,NaN,NaN,NaN,NaN,23.802400,10.67800,34.6643
3,Andorra,NaN,NaN,NaN,NaN,NaN,11.140150,0.84661,23.3238
4,Angola,NaN,NaN,NaN,NaN,NaN,22.825000,18.12080,24.7819
...,...,...,...,...,...,...,...,...,...
191,United States,10.0,83.0,88.0,78.6,6.9,7.385775,-6.84690,21.3749
192,Uruguay,NaN,NaN,NaN,NaN,NaN,18.048250,8.80987,25.8511
193,Uzbekistan,NaN,NaN,NaN,NaN,NaN,13.710350,-12.05100,29.1871
194,Vanuatu,NaN,NaN,NaN,NaN,NaN,24.326050,21.51750,26.8351
195,Venezuela,NaN,NaN,NaN,NaN,NaN,25.825800,24.28350,27.9478

In [118]:
outer_merged_df.shape

(196, 9)

In [119]:
outer_merged_df[outer_merged_df["Country"] == "OECD - Total"]

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction,t_median,t_min,t_max
131,OECD - Total,14.0,81.0,69.0,80.2,6.5,NaN,NaN,NaN

#### Con Indicador

In [121]:
outer_merged_df = pd.merge(
    left=env_heatlh_df,
    right=t_agg_df_norm,
    on="Country",
    how="outer",
    sort=True,
    indicator=True,
)
outer_merged_df

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction,t_median,t_min,t_max,_merge
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,14.227900,-4.17370,26.7011,right_only
1,Albania,NaN,NaN,NaN,NaN,NaN,11.624400,-0.42090,23.9754,right_only
2,Algeria,NaN,NaN,NaN,NaN,NaN,23.802400,10.67800,34.6643,right_only
3,Andorra,NaN,NaN,NaN,NaN,NaN,11.140150,0.84661,23.3238,right_only
4,Angola,NaN,NaN,NaN,NaN,NaN,22.825000,18.12080,24.7819,right_only
...,...,...,...,...,...,...,...,...,...,...
191,United States,10.0,83.0,88.0,78.6,6.9,7.385775,-6.84690,21.3749,both
192,Uruguay,NaN,NaN,NaN,NaN,NaN,18.048250,8.80987,25.8511,right_only
193,Uzbekistan,NaN,NaN,NaN,NaN,NaN,13.710350,-12.05100,29.1871,right_only
194,Vanuatu,NaN,NaN,NaN,NaN,NaN,24.326050,21.51750,26.8351,right_only
195,Venezuela,NaN,NaN,NaN,NaN,NaN,25.825800,24.28350,27.9478,right_only

In [122]:
outer_merged_df[outer_merged_df["_merge"] == "left_only"]

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction,t_median,t_min,t_max,_merge
43,Czech Republic,20.0,87.0,60.0,79.1,6.7,NaN,NaN,NaN,left_only
91,Korea,28.0,76.0,33.0,82.4,5.9,NaN,NaN,NaN,left_only
131,OECD - Total,14.0,81.0,69.0,80.2,6.5,NaN,NaN,NaN,left_only
157,Slovak Republic,21.0,85.0,66.0,77.3,6.2,NaN,NaN,NaN,left_only

In [123]:
outer_merged_df[outer_merged_df["_merge"] == "both"]

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction,t_median,t_min,t_max,_merge
8,Australia,5.0,93.0,85.0,82.5,7.3,22.743050,13.40350,29.4761,both
9,Austria,16.0,92.0,70.0,81.7,7.1,7.014610,-5.73770,19.3133,both
16,Belgium,15.0,84.0,74.0,81.5,6.9,10.097550,-1.07770,21.7403,both
23,Brazil,10.0,73.0,NaN,74.8,6.4,25.753850,22.74970,27.3481,both
30,Canada,7.0,91.0,88.0,81.9,7.4,-5.484650,-27.10300,12.9856,both
34,Chile,16.0,71.0,57.0,79.9,6.5,8.488035,2.52941,13.9296,both
36,Colombia,10.0,75.0,NaN,76.2,6.3,24.666800,23.39750,26.6059,both
46,Denmark,9.0,95.0,71.0,80.9,7.6,7.946250,-4.11570,19.9446,both
55,Estonia,8.0,84.0,53.0,77.8,5.7,5.850140,-11.87600,21.1702,both
60,Finland,6.0,95.0,70.0,81.5,7.6,2.080410,-16.19400,18.9200,both
61,France,13.0,81.0,66.0,82.4,6.5,11.211150,0.87966,22.6900,both
65,Germany,14.0,91.0,65.0,81.1,7.0,8.866750,-3.63500,21.5847,both
67,Greece,18.0,69.0,74.0,81.5,5.4,13.763150,2.29013,25.9151,both
76,Hungary,19.0,77.0,60.0,76.2,5.6,11.282150,-4.22460,23.4025,both
77,Iceland,3.0,99.0,76.0,82.3,7.5,1.528785,-5.91990,10.8606,both
82,Ireland,7.0,85.0,83.0,81.8,7.0,9.234125,1.78030,17.2233,both
83,Israel,21.0,67.0,84.0,82.5,7.2,21.144500,8.89964,29.5582,both
84,Italy,18.0,71.0,71.0,83.3,6.0,12.363600,1.62498,24.1030,both
86,Japan,14.0,87.0,36.0,84.1,5.9,11.938550,-1.90790,25.5125,both
95,Latvia,11.0,79.0,47.0,74.7,5.9,6.685985,-11.13700,21.1299,both
101,Lithuania,14.0,81.0,43.0,74.8,5.9,7.408915,-10.54900,21.2986,both
102,Luxembourg,12.0,84.0,69.0,82.8,6.9,9.547560,-2.42400,21.9099,both
113,Mexico,16.0,68.0,66.0,75.4,6.5,21.802400,14.03340,26.7604,both
122,Netherlands,14.0,93.0,76.0,81.6,7.4,9.882095,-1.02540,21.2702,both
124,New Zealand,5.0,89.0,88.0,81.7,7.3,10.015220,3.49537,17.3598,both
130,Norway,5.0,98.0,77.0,82.5,7.6,0.822290,-11.99600,14.9049,both
140,Poland,22.0,82.0,58.0,78.0,6.1,8.589850,-6.82530,21.1785,both
141,Portugal,10.0,86.0,48.0,81.2,5.4,14.765300,7.13467,24.3683,both
148,Russia,15.0,55.0,43.0,71.8,5.8,-4.637850,-29.64300,16.1930,both
159,Slovenia,16.0,90.0,64.0,81.3,5.9,9.515220,-3.21980,21.8982,both
162,South Africa,22.0,67.0,NaN,57.5,4.7,18.911800,9.62273,24.8558,both
165,Spain,11.0,72.0,72.0,83.4,6.3,13.118300,4.26265,24.6145,both
173,Sweden,6.0,96.0,75.0,82.4,7.3,2.216065,-13.00600,17.0625,both
174,Switzerland,15.0,95.0,78.0,83.7,7.5,6.255735,-5.33230,18.6714,both
184,Turkey,20.0,65.0,69.0,78.0,5.5,12.017600,-3.39930,24.8286,both
190,United Kingdom,11.0,84.0,69.0,81.2,6.8,8.664480,0.10307,17.1651,both
191,United States,10.0,83.0,88.0,78.6,6.9,7.385775,-6.84690,21.3749,both

In [124]:
outer_merged_df[outer_merged_df["_merge"] == "right_only"]

,Country,Air pollution,Water quality,Self-reported health,Life expectancy,Life satisfaction,t_median,t_min,t_max,_merge
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,14.22790,-4.17370,26.7011,right_only
1,Albania,NaN,NaN,NaN,NaN,NaN,11.62440,-0.42090,23.9754,right_only
2,Algeria,NaN,NaN,NaN,NaN,NaN,23.80240,10.67800,34.6643,right_only
3,Andorra,NaN,NaN,NaN,NaN,NaN,11.14015,0.84661,23.3238,right_only
4,Angola,NaN,NaN,NaN,NaN,NaN,22.82500,18.12080,24.7819,right_only
...,...,...,...,...,...,...,...,...,...,...
189,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,28.57125,16.39330,35.2123,right_only
192,Uruguay,NaN,NaN,NaN,NaN,NaN,18.04825,8.80987,25.8511,right_only
193,Uzbekistan,NaN,NaN,NaN,NaN,NaN,13.71035,-12.05100,29.1871,right_only
194,Vanuatu,NaN,NaN,NaN,NaN,NaN,24.32605,21.51750,26.8351,right_only
195,Venezuela,NaN,NaN,NaN,NaN,NaN,25.82580,24.28350,27.9478,right_only

---

## 4.- Transponer Datos

Simplemente invertir las filas por las columnas.

In [125]:
bli_df.T

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
Country,Australia,Austria,Belgium,Canada,Chile,Colombia,Czech Republic,Denmark,Estonia,Finland,...,Spain,Sweden,Switzerland,Turkey,United Kingdom,United States,OECD - Total,Brazil,Russia,South Africa
Dwellings without basic facilities,NaN,0.9,1.9,0.2,9.4,23.9,0.7,0.5,7.0,0.5,...,0.1,0.0,0.1,8.0,0.3,0.1,4.4,6.7,14.8,37.0
Housing expenditure,20.0,21.0,21.0,22.0,18.0,17.0,24.0,23.0,17.0,23.0,...,21.0,19.0,22.0,20.0,26.0,19.0,20.0,NaN,18.0,18.0
Rooms per person,NaN,1.6,2.2,2.6,1.2,1.2,1.4,1.9,1.6,1.9,...,1.9,1.7,1.9,1.0,1.9,2.4,1.8,NaN,0.9,NaN
Household net adjusted disposable income,32759.0,33541.0,30364.0,30854.0,NaN,NaN,21453.0,29606.0,19697.0,29943.0,...,23999.0,31287.0,37466.0,NaN,28715.0,45284.0,33604.0,NaN,NaN,NaN
Household net wealth,427064.0,308325.0,386006.0,423849.0,100967.0,NaN,NaN,118637.0,159373.0,200827.0,...,373548.0,NaN,NaN,NaN,548392.0,632100.0,408376.0,NaN,NaN,NaN
Labour market insecurity,5.4,3.5,3.7,6.0,8.7,NaN,3.1,4.2,3.8,3.9,...,23.1,3.2,NaN,12.5,4.5,7.7,7.0,NaN,NaN,NaN
Employment rate,73,72,63,73,63,67,74,74,74,70,...,62,77,80,52,75,70,68,61,70,43
Long-term unemployment rate,1.31,1.84,3.54,0.77,NaN,0.79,1.04,1.31,1.92,2.13,...,7.66,1.12,1.82,2.39,1.13,0.66,1.78,NaN,1.59,16.46
Personal earnings,49126.0,50349.0,49675.0,47622.0,25879.0,NaN,25372.0,51466.0,24336.0,42964.0,...,38507.0,42393.0,62283.0,NaN,43732.0,60558.0,43241.0,NaN,NaN,NaN
Quality of support network,95,92,91,93,85,89,91,95,92,95,...,93,91,93,86,94,91,89,90,89,88
Educational attainment,81.0,85.0,77.0,91.0,65.0,54.0,94.0,81.0,89.0,88.0,...,59.0,83.0,88.0,39.0,81.0,91.0,78.0,49.0,94.0,73.0
Student skills,502.0,492.0,503.0,523.0,443.0,410.0,491.0,504.0,524.0,523.0,...,491.0,496.0,506.0,425.0,500.0,488.0,486.0,395.0,492.0,NaN
Years in education,21.0,17.0,19.3,17.3,17.5,14.1,17.9,19.5,17.7,19.8,...,17.9,19.3,17.5,18.3,17.5,17.2,17.2,16.2,16.2,NaN
Air pollution,5,16,15,7,16,10,20,9,8,6,...,11,6,15,20,11,10,14,10,15,22
Water quality,93,92,84,91,71,75,87,95,84,95,...,72,96,95,65,84,83,81,73,55,67
Stakeholder engagement for developing regulations,2.7,1.3,2.0,2.9,1.3,1.4,1.6,2.0,2.7,2.2,...,1.8,2.0,2.3,1.5,3.1,3.1,2.4,2.2,NaN,NaN
Voter turnout,91,80,89,68,47,53,61,86,64,67,...,70,86,49,86,69,65,68,79,68,73
Life expectancy,82.5,81.7,81.5,81.9,79.9,76.2,79.1,80.9,77.8,81.5,...,83.4,82.4,83.7,78.0,81.2,78.6,80.2,74.8,71.8,57.5
Self-reported health,85.0,70.0,74.0,88.0,57.0,NaN,60.0,71.0,53.0,70.0,...,72.0,75.0,78.0,69.0,69.0,88.0,69.0,NaN,43.0,NaN
Life satisfaction,7.3,7.1,6.9,7.4,6.5,6.3,6.7,7.6,5.7,7.6,...,6.3,7.3,7.5,5.5,6.8,6.9,6.5,6.4,5.8,4.7
Feeling safe walking alone at night,63.5,80.6,70.1,82.2,47.9,44.4,72.3,83.5,69.0,85.1,...,82.1,75.6,85.3,59.8,77.7,73.9,68.4,35.6,52.8,36.1
Homicide rate,1.1,0.5,1.0,1.3,4.2,24.5,0.5,0.6,3.1,1.3,...,0.6,0.9,0.6,1.4,0.2,5.5,3.7,26.7,9.6,13.7
Employees working very long hours,13.04,6.66,4.75,3.69,9.72,26.56,5.65,2.34,2.42,3.81,...,4.01,1.07,0.37,32.64,12.15,11.09,11.01,7.13,0.14,18.12
Time devoted to leisure and personal care,14.35,14.55,15.7,14.56,NaN,NaN,NaN,15.87,14.9,15.17,...,15.93,15.18,NaN,14.79,14.92,14.44,14.98,NaN,NaN,14.92

In [126]:
bli_df

,Country,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,...,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health,Life satisfaction,Feeling safe walking alone at night,Homicide rate,Employees working very long hours,Time devoted to leisure and personal care
0,Australia,NaN,20.0,NaN,32759.0,427064.0,5.4,73,1.31,49126.0,...,93,2.7,91,82.5,85.0,7.3,63.5,1.1,13.04,14.35
1,Austria,0.9,21.0,1.6,33541.0,308325.0,3.5,72,1.84,50349.0,...,92,1.3,80,81.7,70.0,7.1,80.6,0.5,6.66,14.55
2,Belgium,1.9,21.0,2.2,30364.0,386006.0,3.7,63,3.54,49675.0,...,84,2.0,89,81.5,74.0,6.9,70.1,1.0,4.75,15.70
3,Canada,0.2,22.0,2.6,30854.0,423849.0,6.0,73,0.77,47622.0,...,91,2.9,68,81.9,88.0,7.4,82.2,1.3,3.69,14.56
4,Chile,9.4,18.0,1.2,NaN,100967.0,8.7,63,NaN,25879.0,...,71,1.3,47,79.9,57.0,6.5,47.9,4.2,9.72,NaN
5,Colombia,23.9,17.0,1.2,NaN,NaN,NaN,67,0.79,NaN,...,75,1.4,53,76.2,NaN,6.3,44.4,24.5,26.56,NaN
6,Czech Republic,0.7,24.0,1.4,21453.0,NaN,3.1,74,1.04,25372.0,...,87,1.6,61,79.1,60.0,6.7,72.3,0.5,5.65,NaN
7,Denmark,0.5,23.0,1.9,29606.0,118637.0,4.2,74,1.31,51466.0,...,95,2.0,86,80.9,71.0,7.6,83.5,0.6,2.34,15.87
8,Estonia,7.0,17.0,1.6,19697.0,159373.0,3.8,74,1.92,24336.0,...,84,2.7,64,77.8,53.0,5.7,69.0,3.1,2.42,14.90
9,Finland,0.5,23.0,1.9,29943.0,200827.0,3.9,70,2.13,42964.0,...,95,2.2,67,81.5,70.0,7.6,85.1,1.3,3.81,15.17
10,France,0.5,21.0,1.8,31304.0,280653.0,7.6,65,4.00,43755.0,...,81,2.1,75,82.4,66.0,6.5,70.5,0.5,7.67,16.36
11,Germany,0.2,20.0,1.8,34294.0,259667.0,2.7,75,1.57,47585.0,...,91,1.8,76,81.1,65.0,7.0,72.5,0.5,4.26,15.62
12,Greece,0.5,23.0,1.2,17700.0,150134.0,29.8,53,15.65,26064.0,...,69,1.8,64,81.5,74.0,5.4,60.0,0.8,6.42,NaN
13,Hungary,4.7,19.0,1.2,NaN,104458.0,4.7,68,1.72,22576.0,...,77,1.2,70,76.2,60.0,5.6,56.3,1.0,3.03,NaN
14,Iceland,0.0,24.0,1.6,NaN,NaN,0.7,86,0.26,61787.0,...,99,2.1,79,82.3,76.0,7.5,86.0,0.5,15.06,NaN
15,Ireland,1.0,20.0,2.1,25310.0,217130.0,7.8,67,3.23,47653.0,...,85,1.3,65,81.8,83.0,7.0,75.9,0.7,5.25,NaN
16,Israel,NaN,NaN,1.2,NaN,NaN,4.2,69,0.49,35067.0,...,67,2.5,72,82.5,84.0,7.2,69.8,1.8,15.45,NaN
17,Italy,0.7,23.0,1.4,26588.0,279889.0,12.3,58,6.59,36658.0,...,71,2.5,73,83.3,71.0,6.0,58.4,0.6,4.11,16.47
18,Japan,6.4,22.0,1.9,29798.0,305878.0,1.4,75,1.03,40863.0,...,87,1.4,53,84.1,36.0,5.9,72.5,0.2,NaN,NaN
19,Korea,2.5,15.0,1.5,21882.0,285980.0,2.6,67,0.05,35191.0,...,76,2.9,77,82.4,33.0,5.9,66.6,1.0,NaN,14.70
20,Latvia,13.9,23.0,1.2,16275.0,70160.0,9.6,70,3.35,23683.0,...,79,2.2,59,74.7,47.0,5.9,62.4,4.8,1.27,13.83
21,Lithuania,13.6,19.0,1.5,21660.0,NaN,NaN,70,2.69,24287.0,...,81,2.4,51,74.8,43.0,5.9,55.9,3.4,0.54,NaN
22,Luxembourg,0.5,21.0,1.9,39264.0,769053.0,1.7,66,2.35,63062.0,...,84,1.7,91,82.8,69.0,6.9,75.8,0.6,3.82,NaN
23,Mexico,25.5,20.0,1.0,NaN,NaN,5.5,61,0.07,15314.0,...,68,3.2,63,75.4,66.0,6.5,41.8,18.1,28.70,NaN
24,Netherlands,0.1,19.0,1.9,29333.0,157824.0,4.8,76,1.97,52877.0,...,93,2.6,82,81.6,76.0,7.4,82.0,0.6,0.42,NaN
25,New Zealand,NaN,26.0,2.4,NaN,388514.0,4.7,77,0.74,40043.0,...,89,2.5,80,81.7,88.0,7.3,65.7,1.3,15.11,14.87
26,Norway,0.0,17.0,2.1,35725.0,228936.0,NaN,74,0.66,51212.0,...,98,2.2,78,82.5,77.0,7.6,90.1,0.4,2.93,15.56
27,Poland,3.0,22.0,1.1,19814.0,210991.0,5.7,66,1.52,27046.0,...,82,2.6,55,78.0,58.0,6.1,67.3,0.7,5.95,14.42
28,Portugal,1.0,21.0,1.7,21203.0,232666.0,10.0,68,4.43,25367.0,...,86,1.5,56,81.2,48.0,5.4,73.4,1.0,8.27,NaN
29,Slovak Republic,1.2,23.0,1.1,20474.0,119696.0,9.9,66,4.78,24328.0,...,85,3.0,60,77.3,66.0,6.2,63.5,0.8,4.14,NaN
30,Slovenia,0.4,18.0,1.5,20820.0,203044.0,5.8,69,3.17,34933.0,...,90,2.5,53,81.3,64.0,5.9,86.1,0.6,4.39,14.75
31,Spain,0.1,21.0,1.9,23999.0,373548.0,23.1,62,7.66,38507.0,...,72,1.8,70,83.4,72.0,6.3,82.1,0.6,4.01,15.93
32,Sweden,0.0,19.0,1.7,31287.0,NaN,3.2,77,1.12,42393.0,...,96,2.0,86,82.4,75.0,7.3,75.6,0.9,1.07,15.18
33,Switzerland,0.1,22.0,1.9,37466.0,NaN,NaN,80,1.82,62283.0,...,95,2.3,49,83.7,78.0,7.5,85.3,0.6,0.37,NaN
34,Turkey,8.0,20.0,1.0,NaN,NaN,12.5,52,2.39,NaN,...,65,1.5,86,78.0,69.0,5.5,59.8,1.4,32.64,14.79
35,United Kingdom,0.3,26.0,1.9,28715.0,548392.0,4.5,75,1.13,43732.0,...,84,3.1,69,81.2,69.0,6.8,77.7,0.2,12.15,14.92
36,United States,0.1,19.0,2.4,45284.0,632100.0,7.7,70,0.66,60558.0,...,83,3.1,65,78.6,88.0,6.9,73.9,5.5,11.09,14.44
37,OECD - Total,4.4,20.0,1.8,33604.0,408376.0,7.0,68,1.78,43241.0,...,81,2.4,68,80.2,69.0,6.5,68.4,3.7,11.01,14.98
38,Brazil,6.7,NaN,NaN,NaN,NaN,NaN,61,NaN,NaN,...,73,2.2,79,74.8,NaN,6.4,35.6,26.7,7.13,NaN
39,Russia,14.8,18.0,0.9,NaN,NaN,NaN,70,1.59,NaN,...,55,NaN,68,71.8,43.0,5.8,52.8,9.6,0.14,NaN
40,South Africa,37.0,18.0,NaN,NaN,NaN,NaN,43,16.46,NaN,...,67,NaN,73,57.5,NaN,4.7,36.1,13.7,18.12,14.92

---

## 5.- Reorganizar datos


El dataset que usamos está relativamente ordenado.

In [127]:
bli_df.head(5).iloc[:, 0:20]

,Country,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,Quality of support network,Educational attainment,Student skills,Years in education,Air pollution,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health
0,Australia,NaN,20.0,NaN,32759.0,427064.0,5.4,73,1.31,49126.0,95,81.0,502.0,21.0,5,93,2.7,91,82.5,85.0
1,Austria,0.9,21.0,1.6,33541.0,308325.0,3.5,72,1.84,50349.0,92,85.0,492.0,17.0,16,92,1.3,80,81.7,70.0
2,Belgium,1.9,21.0,2.2,30364.0,386006.0,3.7,63,3.54,49675.0,91,77.0,503.0,19.3,15,84,2.0,89,81.5,74.0
3,Canada,0.2,22.0,2.6,30854.0,423849.0,6.0,73,0.77,47622.0,93,91.0,523.0,17.3,7,91,2.9,68,81.9,88.0
4,Chile,9.4,18.0,1.2,NaN,100967.0,8.7,63,NaN,25879.0,85,65.0,443.0,17.5,16,71,1.3,47,79.9,57.0

Sin embargo, originalmente tenía la siguiente estructura:

In [128]:
dataset_original = pd.read_csv("../../recursos/2023-02/pandas-3/bli_original.csv", keep_default_na=False)
dataset_original

,Continent,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,OC,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,,,5.40,,
1,EU,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,,,3.50,,
2,EU,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,,,3.70,,
3,NA,Canada,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,,,6.00,,
4,EU,Czech Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,,,3.10,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2364,EU,Lithuania,WL_EWLH,Employees working very long hours,L,Value,TOT,Total,PC,Percentage,0,Units,,,0.54,,
2365,SA,Colombia,WL_EWLH,Employees working very long hours,L,Value,MN,Men,PC,Percentage,0,Units,,,32.09,,
2366,EU,Lithuania,WL_EWLH,Employees working very long hours,L,Value,MN,Men,PC,Percentage,0,Units,,,0.67,,
2367,SA,Colombia,WL_EWLH,Employees working very long hours,L,Value,WMN,Women,PC,Percentage,0,Units,,,19.37,,
2368,EU,Lithuania,WL_EWLH,Employees working very long hours,L,Value,WMN,Women,PC,Percentage,0,Units,,,0.43,,

In [129]:
bli_df.loc[:, ["Country", "Labour market insecurity"]]

            Country  Labour market insecurity
0         Australia                       5.4
1           Austria                       3.5
2           Belgium                       3.7
3            Canada                       6.0
4             Chile                       8.7
5          Colombia                       NaN
6    Czech Republic                       3.1
7           Denmark                       4.2
8           Estonia                       3.8
9           Finland                       3.9
10           France                       7.6
11          Germany                       2.7
12           Greece                      29.8
13          Hungary                       4.7
14          Iceland                       0.7
15          Ireland                       7.8
16           Israel                       4.2
17            Italy                      12.3
18            Japan                       1.4
19            Korea                       2.6
20           Latvia                       9.6
21        Lithuania                       NaN
22       Luxembourg                       1.7
23           Mexico                       5.5
24      Netherlands                       4.8
25      New Zealand                       4.7
26           Norway                       NaN
27           Poland                       5.7
28         Portugal                      10.0
29  Slovak Republic                       9.9
30         Slovenia                       5.8
31            Spain                      23.1
32           Sweden                       3.2
33      Switzerland                       NaN
34           Turkey                      12.5
35   United Kingdom                       4.5
36    United States                       7.7
37     OECD - Total                       7.0
38           Brazil                       NaN
39           Russia                       NaN
40     South Africa                       NaN

In [130]:
dataset_original.loc[:, ["Country", "Indicator", "Value"]].tail(20)

        Country                          Indicator  Value
2349   Colombia                  Life satisfaction   6.30
2350  Lithuania                  Life satisfaction   5.90
2351   Colombia                  Life satisfaction   6.20
2352  Lithuania                  Life satisfaction   5.90
2353   Colombia                  Life satisfaction   6.30
2354  Lithuania                  Life satisfaction   6.00
2355  Lithuania                  Life satisfaction   6.50
2356  Lithuania                  Life satisfaction   5.60
2357   Colombia                      Homicide rate  24.50
2358  Lithuania                      Homicide rate   3.40
2359   Colombia                      Homicide rate  46.40
2360  Lithuania                      Homicide rate   5.20
2361   Colombia                      Homicide rate   4.10
2362  Lithuania                      Homicide rate   1.70
2363   Colombia  Employees working very long hours  26.56
2364  Lithuania  Employees working very long hours   0.54
2365   Colombia  Employees working very long hours  32.09
2366  Lithuania  Employees working very long hours   0.67
2367   Colombia  Employees working very long hours  19.37
2368  Lithuania  Employees working very long hours   0.43

In [131]:
dataset_original.shape

(2369, 17)

Cada fila de este dataset contiene información acerca de los paises y de los indicadores y el valor del indicador. Esta forma es conocida como **long**.

### Pivotear

![Pivot Table](https://github.com/MDS7202/MDS7202/blob/main/recursos/2026-01/05_Pandas/reshaping_pivot.png?raw=true)

Para convertirla al formato con el que hemos estado trabajando, **wide**, debemos pivotear la tabla:

In [56]:
dataset_original.head(3)

,Continent,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,OC,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,,,5.4,,
1,EU,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,,,3.5,,
2,EU,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,,,3.7,,

In [57]:
dataset_original["Indicator"].unique()

array(['Labour market insecurity',
       'Stakeholder engagement for developing regulations',
       'Dwellings without basic facilities', 'Housing expenditure',
       'Feeling safe walking alone at night', 'Rooms per person',
       'Household net adjusted disposable income', 'Household net wealth',
       'Employment rate', 'Long-term unemployment rate',
       'Personal earnings', 'Quality of support network',
       'Educational attainment', 'Student skills', 'Years in education',
       'Air pollution', 'Water quality', 'Voter turnout',
       'Life expectancy', 'Self-reported health', 'Life satisfaction',
       'Homicide rate', 'Employees working very long hours',
       'Time devoted to leisure and personal care'], dtype=object)

In [58]:
dataset_original.head().loc[:, ["Country", "Indicator", "Value"]]

          Country                 Indicator  Value
0       Australia  Labour market insecurity    5.4
1         Austria  Labour market insecurity    3.5
2         Belgium  Labour market insecurity    3.7
3          Canada  Labour market insecurity    6.0
4  Czech Republic  Labour market insecurity    3.1

> **Ejercicio ✏️**: Pivotear la tabla original de los datos de la OECD

In [137]:
pd.pivot_table(
    dataset_original, 
    index='Country', 
    columns='Indicator', 
    values='Value'
).head(5)

Indicator,Air pollution,Dwellings without basic facilities,Educational attainment,Employees working very long hours,Employment rate,Feeling safe walking alone at night,Homicide rate,Household net adjusted disposable income,Household net wealth,Housing expenditure,...,Personal earnings,Quality of support network,Rooms per person,Self-reported health,Stakeholder engagement for developing regulations,Student skills,Time devoted to leisure and personal care,Voter turnout,Water quality,Years in education
Country,,,,,,,,,,,,,,,,,,,,,
Australia,5.0,NaN,81.000000,12.840000,73.000000,64.133333,1.100000,32759.0,427064.0,20.0,...,49126.0,95.25,NaN,87.25,2.7,411.2,14.350000,91.0,92.666667,20.966667
Austria,16.0,0.9,85.000000,6.590000,72.000000,80.700000,0.466667,33541.0,308325.0,21.0,...,50349.0,92.00,1.6,70.60,1.3,492.8,14.530000,80.0,92.000000,17.000000
Belgium,15.0,1.9,77.000000,4.703333,63.333333,70.266667,1.033333,30364.0,386006.0,21.0,...,49675.0,92.00,2.2,73.60,2.0,503.8,15.663333,89.0,83.666667,19.300000
Brazil,10.0,6.7,49.000000,7.006667,61.000000,35.866667,27.000000,NaN,NaN,NaN,...,NaN,89.25,NaN,NaN,2.2,398.2,NaN,79.0,73.000000,16.166667
Canada,7.0,0.2,91.333333,3.673333,73.333333,82.500000,1.266667,30854.0,423849.0,22.0,...,47622.0,93.25,2.6,87.80,2.9,523.2,14.553333,68.0,91.000000,17.333333

> Y en qué influye index?

In [138]:
pd.pivot_table(
    dataset_original, 
    columns='Indicator', 
    values='Value'
).head(5)

Indicator,Air pollution,Dwellings without basic facilities,Educational attainment,Employees working very long hours,Employment rate,Feeling safe walking alone at night,Homicide rate,Household net adjusted disposable income,Household net wealth,Housing expenditure,...,Personal earnings,Quality of support network,Rooms per person,Self-reported health,Stakeholder engagement for developing regulations,Student skills,Time devoted to leisure and personal care,Voter turnout,Water quality,Years in education
Value,13.341463,5.057895,77.733333,7.866496,68.520325,68.464228,3.487805,28000.533333,288004.724138,20.641026,...,39912.611111,90.017857,1.636842,67.445055,2.166667,485.825,15.042319,69.536585,82.300813,17.539167

In [139]:
pd.pivot_table(
    dataset_original, 
    index='Continent', 
    columns='Indicator', 
    values='Value'
).head(5)

Indicator,Air pollution,Dwellings without basic facilities,Educational attainment,Employees working very long hours,Employment rate,Feeling safe walking alone at night,Homicide rate,Household net adjusted disposable income,Household net wealth,Housing expenditure,...,Personal earnings,Quality of support network,Rooms per person,Self-reported health,Stakeholder engagement for developing regulations,Student skills,Time devoted to leisure and personal care,Voter turnout,Water quality,Years in education
Continent,,,,,,,,,,,,,,,,,,,,,
AF,22.000000,37.000000,73.333333,17.840000,43.333333,36.333333,14.000000,NaN,NaN,18.000000,...,NaN,88.000000,NaN,NaN,NaN,NaN,14.770000,73.000000,67.000000,NaN
AS,21.000000,4.450000,87.500000,15.273333,70.222222,69.811111,1.011111,25840.000000,295929.000000,18.500000,...,37040.333333,85.818182,1.533333,49.000000,2.266667,506.266667,14.583333,67.333333,76.666667,16.422222
EU,13.178571,2.717857,79.833333,5.383690,69.345238,72.698810,1.365476,26909.791667,256162.333333,21.000000,...,40151.923077,90.620690,1.607143,67.021898,2.074074,493.678571,15.218542,70.071429,84.095238,17.820238
NA,11.000000,8.600000,73.222222,13.981111,68.333333,66.122222,8.466667,38069.000000,527974.500000,20.333333,...,41164.666667,88.307692,2.000000,82.307692,3.066667,476.200000,14.496667,65.333333,80.444444,16.566667
OC,5.000000,NaN,79.833333,13.938333,75.000000,65.200000,1.200000,32759.000000,407789.000000,23.000000,...,44584.500000,95.750000,2.400000,88.250000,2.600000,458.700000,14.616667,85.500000,90.833333,19.333333

### Melt

![Melt Table](https://github.com/MDS7202/MDS7202/blob/main/recursos/2026-01/05_Pandas/reshaping_melt.png?raw=true)

Melt es la operación opuesta a pivot, transformando a formato long, el cual puede ser más útil en algunos casos de uso.

> Cuantas columnas resultaron del pivot?

In [141]:
pd.pivot_table(
    dataset_original, 
    index='Country', 
    columns='Indicator', 
    values='Value'
).head(5)

Indicator,Air pollution,Dwellings without basic facilities,Educational attainment,Employees working very long hours,Employment rate,Feeling safe walking alone at night,Homicide rate,Household net adjusted disposable income,Household net wealth,Housing expenditure,...,Personal earnings,Quality of support network,Rooms per person,Self-reported health,Stakeholder engagement for developing regulations,Student skills,Time devoted to leisure and personal care,Voter turnout,Water quality,Years in education
Country,,,,,,,,,,,,,,,,,,,,,
Australia,5.0,NaN,81.000000,12.840000,73.000000,64.133333,1.100000,32759.0,427064.0,20.0,...,49126.0,95.25,NaN,87.25,2.7,411.2,14.350000,91.0,92.666667,20.966667
Austria,16.0,0.9,85.000000,6.590000,72.000000,80.700000,0.466667,33541.0,308325.0,21.0,...,50349.0,92.00,1.6,70.60,1.3,492.8,14.530000,80.0,92.000000,17.000000
Belgium,15.0,1.9,77.000000,4.703333,63.333333,70.266667,1.033333,30364.0,386006.0,21.0,...,49675.0,92.00,2.2,73.60,2.0,503.8,15.663333,89.0,83.666667,19.300000
Brazil,10.0,6.7,49.000000,7.006667,61.000000,35.866667,27.000000,NaN,NaN,NaN,...,NaN,89.25,NaN,NaN,2.2,398.2,NaN,79.0,73.000000,16.166667
Canada,7.0,0.2,91.333333,3.673333,73.333333,82.500000,1.266667,30854.0,423849.0,22.0,...,47622.0,93.25,2.6,87.80,2.9,523.2,14.553333,68.0,91.000000,17.333333

En melt, **Múltiples** columnas serán procesadas y los nombres de las columnas pasarán a ser valores de la nueva columna `variable`, y los valores en la nueva columna `value`. Esto le sucederá a todas las columnas salvo aquellas que se indiquen como índice con `id_vars`. Estas mantendrán su estructura pero se repetirán tantas veces como la cantidad de columnas restantes o `value_vars`.

In [142]:
bli_df.head()

,Country,Dwellings without basic facilities,Housing expenditure,Rooms per person,Household net adjusted disposable income,Household net wealth,Labour market insecurity,Employment rate,Long-term unemployment rate,Personal earnings,...,Water quality,Stakeholder engagement for developing regulations,Voter turnout,Life expectancy,Self-reported health,Life satisfaction,Feeling safe walking alone at night,Homicide rate,Employees working very long hours,Time devoted to leisure and personal care
0,Australia,NaN,20.0,NaN,32759.0,427064.0,5.4,73,1.31,49126.0,...,93,2.7,91,82.5,85.0,7.3,63.5,1.1,13.04,14.35
1,Austria,0.9,21.0,1.6,33541.0,308325.0,3.5,72,1.84,50349.0,...,92,1.3,80,81.7,70.0,7.1,80.6,0.5,6.66,14.55
2,Belgium,1.9,21.0,2.2,30364.0,386006.0,3.7,63,3.54,49675.0,...,84,2.0,89,81.5,74.0,6.9,70.1,1.0,4.75,15.70
3,Canada,0.2,22.0,2.6,30854.0,423849.0,6.0,73,0.77,47622.0,...,91,2.9,68,81.9,88.0,7.4,82.2,1.3,3.69,14.56
4,Chile,9.4,18.0,1.2,NaN,100967.0,8.7,63,NaN,25879.0,...,71,1.3,47,79.9,57.0,6.5,47.9,4.2,9.72,NaN

In [143]:
bli_df.melt(
    id_vars=["Country"]
)

           Country                                   variable  value
0        Australia         Dwellings without basic facilities    NaN
1          Austria         Dwellings without basic facilities   0.90
2          Belgium         Dwellings without basic facilities   1.90
3           Canada         Dwellings without basic facilities   0.20
4            Chile         Dwellings without basic facilities   9.40
..             ...                                        ...    ...
979  United States  Time devoted to leisure and personal care  14.44
980   OECD - Total  Time devoted to leisure and personal care  14.98
981         Brazil  Time devoted to leisure and personal care    NaN
982         Russia  Time devoted to leisure and personal care    NaN
983   South Africa  Time devoted to leisure and personal care  14.92

[984 rows x 3 columns]

In [145]:
bli_df.melt(
    id_vars=["Country"],
    var_name="Indicator",
    value_name="Value"
)

           Country                                  Indicator  Value
0        Australia         Dwellings without basic facilities    NaN
1          Austria         Dwellings without basic facilities   0.90
2          Belgium         Dwellings without basic facilities   1.90
3           Canada         Dwellings without basic facilities   0.20
4            Chile         Dwellings without basic facilities   9.40
..             ...                                        ...    ...
979  United States  Time devoted to leisure and personal care  14.44
980   OECD - Total  Time devoted to leisure and personal care  14.98
981         Brazil  Time devoted to leisure and personal care    NaN
982         Russia  Time devoted to leisure and personal care    NaN
983   South Africa  Time devoted to leisure and personal care  14.92

[984 rows x 3 columns]

In [152]:
bli_df_subset = bli_df.loc[:, 
    ["Country", "Dwellings without basic facilities", "Housing expenditure", "Rooms per person"]
]

bli_df_subset.head()

,Country,Dwellings without basic facilities,Housing expenditure,Rooms per person
0,Australia,NaN,20.0,NaN
1,Austria,0.9,21.0,1.6
2,Belgium,1.9,21.0,2.2
3,Canada,0.2,22.0,2.6
4,Chile,9.4,18.0,1.2

In [154]:
bli_df_subset.melt(
    id_vars=["Country"],
    var_name="Indicator",
    value_name="Value"
)

           Country                           Indicator  Value
0        Australia  Dwellings without basic facilities    NaN
1          Austria  Dwellings without basic facilities    0.9
2          Belgium  Dwellings without basic facilities    1.9
3           Canada  Dwellings without basic facilities    0.2
4            Chile  Dwellings without basic facilities    9.4
..             ...                                 ...    ...
118  United States                    Rooms per person    2.4
119   OECD - Total                    Rooms per person    1.8
120         Brazil                    Rooms per person    NaN
121         Russia                    Rooms per person    0.9
122   South Africa                    Rooms per person    NaN

[123 rows x 3 columns]

In [157]:
bli_df_subset.melt(
    value_vars=[
        "Dwellings without basic facilities", "Housing expenditure", "Rooms per person"
    ],
    var_name="Indicator",
    value_name="Value"
)

                              Indicator  Value
0    Dwellings without basic facilities    NaN
1    Dwellings without basic facilities    0.9
2    Dwellings without basic facilities    1.9
3    Dwellings without basic facilities    0.2
4    Dwellings without basic facilities    9.4
..                                  ...    ...
118                    Rooms per person    2.4
119                    Rooms per person    1.8
120                    Rooms per person    NaN
121                    Rooms per person    0.9
122                    Rooms per person    NaN

[123 rows x 2 columns]